- geomstats/rotations.py
- geomstats/sphere.py
- tests/test_sphere.py
Add a new manifold: n-dimensional sphere, embedded in (n+1)-dimensional euclidean space.
> Start sphere module

- geomstats/hyperbolic_space.py
- geomstats/rigid_transformations.py
- tests/test_hyperbolic_space.py
Start the n-dimensional hyperbolic space.
> Nina add hyperbolic

- geomstats/euclidean_space.py
- geomstats/hyperbolic_space.py
- geomstats/hypersphere.py
- geomstats/lie_group.py
- geomstats/matrix_lie_group.py
- geomstats/minkowski_space.py
- geomstats/riemannian_metric.py
- geomstats/special_euclidean_group.py
- geomstats/special_orthogonal_group.py
- tests/test_euclidean_space.py
- tests/test_hyperbolic_space.py
- tests/test_hypersphere.py
- tests/test_invariant_metric.py
- tests/test_lie_group.py
- tests/test_manifold.py
- tests/test_matrix_lie_group.py
- tests/test_minkowski_space.py
- tests/test_spd_matrices_space.py
- tests/test_special_euclidean_group.py
- tests/test_special_orthogonal_group.py
Add more tests (some fail, I added some TODOs).
Generalize some parts of the code, using inheritance.
Add MatrixLieGroup class.
> Nina more tests

- geomstats/euclidean_space.py
- geomstats/hyperbolic_space.py
- geomstats/hypersphere.py
- geomstats/invariant_metric.py
- geomstats/lie_group.py
- geomstats/matrix_lie_group.py
- geomstats/minkowski_space.py
- geomstats/riemannian_metric.py
- geomstats/spd_matrices_space.py
- geomstats/special_euclidean_group.py
- geomstats/special_orthogonal_group.py
- tests/helper.py
- tests/test_euclidean_space.py
- tests/test_hyperbolic_space.py
- tests/test_hypersphere.py
- tests/test_invariant_metric.py
- tests/test_lie_group.py
- tests/test_manifold.py
- tests/test_matrix_lie_group.py
- tests/test_minkowski_space.py
- tests/test_spd_matrices_space.py
- tests/test_special_euclidean_group.py
- tests/test_special_orthogonal_group.py
Address CR of branch nina-more-tests that I had merged yesterday.
> Nina cr more tests

- examples/plot_geodesics.py
- geomstats/riemannian_metric.py
- geomstats/visualization.py
- tests/test_visualization.py
I got to see where we need vectorization :) I should vectorize in the next CR.
> Nina example geodesic

- examples/plot_geodesics.py
- geomstats/euclidean_space.py
- geomstats/hyperbolic_space.py
- geomstats/hypersphere.py
- geomstats/invariant_metric.py
- geomstats/lie_group.py
- geomstats/matrix_lie_group.py
- geomstats/riemannian_metric.py
- geomstats/special_euclidean_group.py
- geomstats/special_orthogonal_group.py
- geomstats/visualization.py
- tests/helper.py
- tests/test_hypersphere.py
- tests/test_invariant_metric.py
- tests/test_matrix_lie_group.py
- tests/test_special_euclidean_group.py
- tests/test_special_orthogonal_group.py
Vectorization of special_orthogonal_group and special_euclidean_group + unit tests checking that output dimensions are correct.
> Nina vectorization

- geomstats/special_orthogonal_group.py
- tests/test_special_orthogonal_group.py
Add conversions functions from and to quaternions. Add corresponding unit tests.
> Nina quaternions

- examples/plot_geodesics_h2.py
- geomstats/visualization.py
- tests/test_euclidean_space.py
- tests/test_hyperbolic_space.py
- tests/test_hypersphere.py
- tests/test_minkowski_space.py
- tests/test_special_euclidean_group.py
- tests/test_special_orthogonal_group.py
- tests/test_visualization.py
Add plot of geodesics for the hyperbolic space in 2D, with Poincare disk visualization.
Add unit tests to check that the geodesics belong to the space for all spaces.
> Nina geodesics h2

- geomstats/invariant_metric.py
- tests/test_special_euclidean_group.py
There are bugs in the vectorization of exp, log, dist and squared dist for se3 (and probably the other modules too).
This CR adds unit tests to find the bugs. I haven't found them yet though.
> Nina se3 dist

- geomstats/riemannian_metric.py
- geomstats/spd_matrices_space.py
- tests/test_spd_matrices_space.py
Vectorization of module on symmetric positive definite matrices
> Nina vectorization spd

- geomstats/invariant_metric.py
- geomstats/special_euclidean_group.py
- geomstats/special_orthogonal_group.py
- tests/helper.py
- tests/test_special_euclidean_group.py
- tests/test_special_orthogonal_group.py
Add the regularization of the tangent vectors for SO3 and SE3.
Debug the unit tests of the diagonal metrics for SO3 and SE3.
> Nina debug nondiagonal metrics

- geomstats/special_orthogonal_group.py
- tests/test_special_orthogonal_group.py
> Fix bug in vectorization of regularization

- tests/test_examples.py
Add unit tests for the examples, preventing the figures to be shown while testing with matplotlib agg backend.
@johmathe What were your thoughts about saving the figures of the examples? Thanks.
> Nina tests examples

- geomstats/euclidean_space.py
- geomstats/hyperbolic_space.py
- geomstats/hypersphere.py
- geomstats/invariant_metric.py
- geomstats/lie_group.py
- geomstats/matrix_lie_group.py
- geomstats/minkowski_space.py
- geomstats/riemannian_metric.py
- geomstats/spd_matrices_space.py
- geomstats/special_euclidean_group.py
- geomstats/special_orthogonal_group.py
- geomstats/vectorization.py
- geomstats/visualization.py
> Add conversion to ndarray in the preprocessing fn in vectorization

- examples/plot_h2_square.py
- geomstats/hyperbolic_space.py
- geomstats/hypersphere.py
Changing tolerance enables to draw the square (almost) until the limits of the disk. The numerical issue is still there, but at least not visible to the human eye. 
Partly addressing Issue #38
> Change H and S unit norm's tolerances

- examples/plot_geodesics_h2.py
- examples/plot_h2_square.py
- geomstats/hyperbolic_space.py
- geomstats/manifold.py
- tests/test_euclidean_space.py
- tests/test_hyperbolic_space.py
- tests/test_manifold.py
- tests/test_special_euclidean_group.py
- tests/test_special_orthogonal_group.py
Taking steps towards solving issue #38 
- add a regularize function
- use regularize function to systematically regularize outputs of the exponential
- assess if a point belongs to H by checking if its squared Minkowski norm is close to -1, at the scale of its Euclidean norm (relative tolerance, not absolute tolerance.)
> Nina bug h2

- examples/gradient_descent.py
- geomstats/visualization.py
- Update viz library
- Add gradient descent module
> Johmathe gradient descent

- geomstats/invariant_metric.py
- geomstats/spd_matrices_space.py
- geomstats/special_orthogonal_group.py
- tests/test_special_orthogonal_group.py
Add first functions for the implementation of SO(n) for n!=3.
Prepare the generalization of unit tests  of SO(n) for n!=3
> Add first functions for SO(n) with n!=3

- geomstats/backend/numpy.py
- geomstats/backend/numpy_linalg.py
- geomstats/special_euclidean_group.py
- geomstats/special_orthogonal_group.py
I will order the backend functions in another PR.
> Update backend from numpy to geomstats

- geomstats/euclidean_space.py
- geomstats/hyperbolic_space.py
- geomstats/hypersphere.py
- geomstats/riemannian_metric.py
- geomstats/special_euclidean_group.py
- tests/test_euclidean_space.py
- tests/test_examples.py
- tests/test_hyperbolic_space.py
- tests/test_hypersphere.py
- tests/test_minkowski_space.py
- tests/test_special_euclidean_group.py
- tests/test_special_orthogonal_group.py
Parallelize the functions for the euclidean module, in order to add the channels. 
Fix the following bugs in other modules.
Next step is to parallelize the hypersphere module.
> Nina parallel euclidean

- examples/gradient_descent_s2.py
- tests/test_examples.py
add gradient descent example test
fix gradient descent
>  fix gradient descent example

- geomstats/backend/numpy.py
- geomstats/backend/tensorflow.py
- geomstats/backend/tensorflow_linalg.py
- geomstats/backend/tensorflow_random.py
- requirements.txt
- tests/test_tensorflow_backend.py
update backend and add tensorflow test
> update backend and add tensorflow test

- geomstats/manifold.py
- tests/test_manifold.py
get_dimension getter on the manifold
> Add the get_dimension getter on the manifold

- geomstats/product_manifold.py
- geomstats/product_riemannian_metric.py
Product manifold and product metric.
> Nina product new

- geomstats/backend/numpy.py
- geomstats/visualization.py
This CR adds two additional visualizations for the Hyperbolic space H2:
- Klein disk,
- Poincare half plane.
Both are obtained by converting the 2D coordinates of a point in the Poincare disk to their own 2D coordinates.
> Nina klein disk and poincare half plane

- geomstats/connection.py
- requirements.txt
- tests/test_connection.py
Add:
- formula for the christoffel symbols of the Levi Civita connection using automatic differentiation with autograd
- corresponding unit tests
> Debug test connection

- geomstats/connection.py
This CR adds:
- connection exponential and logarithm
- pole ladder numerical scheme to perform parallel transport
- parallel transport as a series of pole ladders.
Unit tests to come.
> Add code for pole ladder and parallel transport

- geomstats/backend/numpy.py
- geomstats/special_orthogonal_group.py
- tests/test_special_orthogonal_group.py
Add unit tests for the tait bryan angles in SO3.
> Nina debug tait bryan

- geomstats/backend/numpy.py
- geomstats/hypersphere.py
- geomstats/riemannian_metric.py
- geomstats/visualization.py
- tests/test_hypersphere.py
- tests/test_visualization.py
...and an "unbounded" version of `random_uniform` to `hypersphere.py`, that I use in the `plot_quantization_s1.py` example. I couldn't find a better name...
> Add closest_neighbor and diameter to riemannian_metric

- geomstats/backend/tensorflow.py
- geomstats/backend/tensorflow_random.py
- geomstats/hypersphere.py
- geomstats/riemannian_metric.py
- tests/test_backend_tensorflow.py
- tests/test_hyperbolic_space.py
- tests/test_hypersphere.py
> Nina tf tests bis

- geomstats/backend/numpy.py
- geomstats/backend/numpy_linalg.py
- geomstats/backend/numpy_random.py
- geomstats/backend/pytorch.py
- geomstats/backend/pytorch_linalg.py
- geomstats/backend/pytorch_random.py
- geomstats/backend/tensorflow.py
- geomstats/backend/tensorflow_linalg.py
- geomstats/backend/tensorflow_random.py
Adding backends functions for following stiefel manifold PR.
> Backends for stiefel

- geomstats/hyperbolic_space.py
- geomstats/hypersphere.py
- geomstats/matrices_space.py
- geomstats/stiefel.py
- tests/test_matrices_space.py
- tests/test_stiefel.py
Implementing the canonical metric instead of the euclidean metric on stiefel manifolds
> Nina stiefel canonical

- geomstats/hyperbolic_space.py
- geomstats/hypersphere.py
- geomstats/stiefel.py
- tests/test_stiefel.py
Lifting and retraction maps for stiefel manifolds
> Nina stiefel last

- geomstats/hyperbolic_space.py
- geomstats/hypersphere.py
- geomstats/matrices_space.py
- geomstats/stiefel.py
- tests/test_matrices_space.py
- tests/test_stiefel.py
Reverts geomstats/geomstats#174
> Revert "Revert "Nina stiefel canonical""

- geomstats/euclidean_space.py
- geomstats/hyperbolic_space.py
- geomstats/hypersphere.py
- geomstats/minkowski_space.py
- tests/test_hyperbolic_space.py
- tests/test_hypersphere.py
Adding the parameter bound when sampling from the uniform distribution, as to vary the size of the ball on which we uniformly sample.
> Adding parameter `bound` when sampling from uniform distributions

- tests/test_backend_tensorflow.py
- tests/test_connection.py
- tests/test_euclidean_space.py
- tests/test_general_linear_group.py
- tests/test_hyperbolic_space.py
- tests/test_hypersphere.py
- tests/test_minkowski_space.py
Remove the gs.eval in the unit tests asserts.
> Nina gseval

- README.md
Add badges with coverages for numpy and tensorflow.
> Nina readme coverage

- geomstats/backend/pytorch.py
Signed-off-by: Niklas Koep <niklas.koep@gmail.com>
> Use 'isinstance' to test class membership

- geomstats/geometry/discretized_curves_space.py
Function `get_mask_i_float` was moved to backend.
> Remove dead, duplicated code

- geomstats/geometry/spd_matrices_space.py
- tests/test_spd_matrices_space.py
From metric as an attribute of SPDMatricesSpace to space as an attribute of each SPDMetric
> Yanntwd spd switch space metric

- geomstats/backend/pytorch.py
- requirements.txt
It cause geomstats.hyperbolic_space log and exp function to fai (NaN value)l
> isClose() bug fixed on data type

- geomstats/tests.py
Signed-off-by: Niklas Koep <niklas.koep@gmail.com>
> tests.py: fix nose2 marker to test in parallel

- geomstats/geometry/hypersphere.py
> Vectorization of exact transport

- geomstats/backend/numpy.py
- geomstats/backend/pytorch.py
- geomstats/geometry/spd_matrices_space.py
- tests/test_spd_matrices_space.py
Power-Euclidean inner product
Test
exp_domain of the Euclidean metric
Test
gs.amin in backend.numpy (tested) and backend.pytorch (not tested)
> Yanntwd spd euclideanmetric

- geomstats/geometry/special_orthogonal_group.py
- tests/test_special_orthogonal_group.py
If n > 3 we just compute the matrix exponential.
> Fix so n group exp

- geomstats/geometry/discretized_curves_space.py
- geomstats/geometry/embedded_manifold.py
- geomstats/geometry/euclidean_space.py
Add and format docstrings within a few files of geomstats.geometry.
Only templates were added for many functions. These need to be filled in.
> Docs geom 1.py

- geomstats/geometry/spd_matrices_space.py
- tests/test_spd_matrices_space.py
Modification in inner product
Exp
Log
Tests
> Yann twd power affine exp

- .travis.yml
- geomstats/backend/tensorflow/__init__.py
- geomstats/backend/tensorflow/linalg.py
- geomstats/backend/tensorflow/random.py
- requirements.txt
- tests/test_connection.py
- tests/test_discretized_curves_space.py
- tests/test_estimators.py
- tests/test_hyperbolic_space.py
- tests/test_hyperbolic_space_coordinates.py
- tests/test_hypersphere.py
- tests/test_landmarks_space.py
- tests/test_matrices_space.py
- tests/test_poincare_polydisk.py
- tests/test_riemannian_kmeans.py
- tests/test_skew_symmetric_matrices.py
- tests/test_spd_matrices_space.py
> Travis tests for tf 2.0

- geomstats/backend/numpy/__init__.py
- geomstats/geometry/discretized_curves.py
- geomstats/learning/_template.py
- geomstats/learning/pca.py
- geomstats/visualization.py
- tests/test_estimators.py
> Convert np. to gs. everywhere

- geomstats/vectorization.py
- tests/test_vectorization.py
Start to address #338, following @cshewmake2 's recommendation about decorators.
This needs unit tests.
> Add decorator for readability in vectorization operations

- geomstats/geometry/poincare_polydisk.py
- geomstats/geometry/product_manifold.py
- geomstats/geometry/product_riemannian_metric.py
- geomstats/geometry/riemannian_metric.py
- geomstats/geometry/skew_symmetric_matrices.py
- geomstats/geometry/spd_matrices.py
- geomstats/geometry/special_euclidean.py
- geomstats/geometry/stiefel.py
Left some TODO's in here for people to fill in the technical details of certain methods. Especially in stiefel.py.
> Fix and add docstrings.

- README.md
update readme with grant number and urls
> Funding Acknowledgement

- geomstats/geometry/lie_group.py
- geomstats/geometry/special_euclidean.py
- geomstats/geometry/special_orthogonal.py
> Documentation for Lie groups, SO(n), SE(n)

- docs/conf.py
- docs/contributing.rst
- geomstats/geometry/hyperbolic.py
- geomstats/geometry/product_manifold.py
- geomstats/geometry/special_euclidean.py
This is a simple update to fix small errors in recently updated docstrings. In addition, the configuration file was modified to improve the visual display of parameters in the API Reference.
> Fix docs for sphinx build

- .travis.yml
- docs/conf.py
- requirements.txt
> Add tests with pytorch backend for python 3.8

- .pre-commit-config.yaml
See https://github.com/geomstats/geomstats/commit/f8dde53180471973d57af759f3d6a6f295fdbacf for details.
> Add flake8 plugin dependencies in pre-commit config

- geomstats/geometry/product_manifold.py
- geomstats/geometry/product_riemannian_metric.py
- geomstats/geometry/skew_symmetric_matrices.py
> Move geodesic function of product manifold

- .flake8
- .travis.yml
This fixes a syntax error in the travis config which prevented CI builds to trigger altogether.
> travis.yml: fix indentation in deploy section

- .travis.yml
- docs/conf.py
- geomstats/geometry/discretized_curves.py
- geomstats/geometry/general_linear.py
- geomstats/geometry/hypersphere.py
- geomstats/geometry/lie_algebra.py
- geomstats/geometry/poincare_polydisk.py
- geomstats/geometry/product_manifold.py
- geomstats/geometry/stiefel.py
- geomstats/learning/__init__.py
- geomstats/learning/_template.py
- geomstats/learning/kmeans.py
- geomstats/learning/online_kmeans.py
This PR cleans up various sphinx warnings during documentation builds. As a result of this clean-up, we can now enable flake8 docstring checking for the learning package.
> Sphinx clean-up

- geomstats/geometry/invariant_metric.py
- geomstats/geometry/spd_matrices.py
And fixes a typo on spd_matrices docstrings
> Doc for invariant metric

- geomstats/geometry/product_riemannian_metric.py
> Fix Nit in product_riemannian_metric

- geomstats/learning/knn.py
- tests/test_knn.py
Add the KNN classifier and its test.
> Add the KNN classifier.

- geomstats/backend/tensorflow/linalg.py
- tests/test_spd_matrices.py
> Use TF's sqrtm in TF backend

- examples/plot_knn_s2.py
- tests/test_examples.py
Add an example of the KNN classifier on the sphere and its corresponding test.
> Add an example of the KNN classifier on the sphere.

- geomstats/backend/numpy/__init__.py
- geomstats/backend/pytorch/__init__.py
- geomstats/backend/tensorflow/__init__.py
- geomstats/backend/tensorflow/common.py
- geomstats/geometry/special_euclidean.py
- geomstats/geometry/special_orthogonal.py
- tests/test_special_euclidean.py
Re PR-ing the changes on the matrix representation for SE(n), the previous branch went buggy after GitHub kind of broke down.
Direct follow-up of #474
> Special Euclidian matrix representation (again), see #474

- geomstats/vectorization.py
- tests/test_vectorization.py
This follows PR #481 that had a GitHub issue.
> Update decorator that performs automatic vectorization of functions/methods part 2

- examples/empirical_frechet_mean_uncertainty_sn.py
- geomstats/learning/frechet_mean.py
- geomstats/learning/kmeans.py
- geomstats/learning/online_kmeans.py
- tests/test_riemannian_kmeans.py
This will make it work for matrix manifolds such as SPDMatrices. However OnlineKmeans doesn't use the FrechetMean estimator so it won't work.
> add argument point_type in kmeans

- geomstats/backend/numpy/__init__.py
- geomstats/backend/pytorch/__init__.py
- geomstats/backend/tensorflow/__init__.py
- geomstats/geometry/lie_algebra.py
- geomstats/geometry/matrices.py
- geomstats/geometry/skew_symmetric_matrices.py
- tests/test_backends.py
- tests/test_lie_algebra.py
- tests/test_lie_group.py
- tests/test_matrices.py
- tests/test_skew_symmetric_matrices.py
Add is_skew_sym method and corresponding tests
> lie algebra and skew-sym

- examples/empirical_frechet_mean_uncertainty_sn.py
- geomstats/learning/frechet_mean.py
Corrected a bug for one sample changed Levenberg-Marquardt adaptive constants and doctsring in adaptive gradient descent for Frechet mean
> Xpennec bug frechetmean one sample

- .codecov.yml
Update .codecov.yml to make codecov less strict.
> Change codecov's bound for 'green' labeling

- geomstats/geometry/grassmannian.py
- geomstats/geometry/stiefel.py
- tests/test_stiefel.py
Given an orthonormal p-frame `x` in Mat(n, p) returns the projector onto its image `p = x . x*`
> add projection from St(n, p) to Gr(n, p)

- examples/learning_graph_structured_data_h2.py
- geomstats/geometry/hyperbolic.py
- tests/test_examples.py
- tests/test_hyperbolic_coords.py
Works for numpy only (currently working to make it works for pytorch):
TODO:
- Adding an other loss
- Learn using retraction methods
- Use autograd instead of defining log_sigmoid grad
- Make it works an pytorch/tensorflow
Here a gif to show how embeddings are moving during learning:
> Adding example on learning graph structured data embedding in Hyperbolic manifold

- examples/empirical_frechet_mean_uncertainty_sn.py
- examples/gradient_descent_s2.py
- geomstats/backend/numpy/__init__.py
- geomstats/backend/pytorch/__init__.py
- geomstats/backend/tensorflow/common.py
- geomstats/datasets/graph_data_preparation.py
- geomstats/geometry/beta_distributions.py
- geomstats/geometry/general_linear.py
- geomstats/geometry/invariant_metric.py
- geomstats/geometry/lie_group.py
- geomstats/geometry/product_manifold.py
- geomstats/geometry/product_riemannian_metric.py
- geomstats/geometry/spd_matrices.py
- geomstats/geometry/special_euclidean.py
- geomstats/geometry/special_orthogonal.py
- geomstats/geometry/stiefel.py
- geomstats/learning/pca.py
- geomstats/tests.py
- tests/test_estimators.py
- tests/test_hypersphere.py
This PR fixes the following deep source errors:
- unused variables
- redefining built-in functions
- unnecessary if/else statements
flagged here:
https://deepsource.io/gh/geomstats/geomstats/issues/?category=antipattern
> Fix anti-patterns errors flagged by deep source

- examples/plot_online_kmeans_s2.py
Change double quotes to single quotes in the plot_online_kmeans_s2.py file.
> Change double quotes to single quotes.

- examples/plot_knn_s2.py
- geomstats/learning/knn.py
- tests/test_knn.py
Change the default name of the parameter metric for distance in the knn classifier.
> Change parameter name in the KNN classifier.

- geomstats/_backend/__init__.py
- geomstats/_backend/numpy/__init__.py
- geomstats/_backend/pytorch/__init__.py
- geomstats/_backend/tensorflow/__init__.py
- geomstats/geometry/lie_group.py
- geomstats/learning/frechet_mean.py
This PR removes the now unnecessary compatibility layer in the Numpy/PyTorch backends we had to maintain due to TF's execution model prior to TF2.
> Remove TF1 artifacts

- geomstats/learning/exponential_barycenter.py
- geomstats/learning/pca.py
- tests/test_exponential_barycenter.py
- tests/test_pca.py
- test pca for `point_type=matrix` with non-symmetric matrices, i.e. on se3
- test exponential barycenter with verbose and linear case
> Add unit tests for pca and exponential barycenter

- geomstats/geometry/general_linear.py
- tests/test_general_linear.py
Redid #552 due which was getting confused.
Random sampling based on the fact that a random matrix is invertible with probability 1. Similarly to what is done for the hypersphere, a check on the determinant is made to have a numerically acceptable matrix.
The value of the determinant threshold is completely arbitrary, and is surely not the best one. I guess it should vary with `n`.
> Random sampling in GeneralLinear (again)

- geomstats/geometry/special_euclidean.py
- tests/test_special_euclidean.py
Debugged #548 by replacing element-wise product with outer product.
There still is the issue of the for loop used in vectorization.
> First response to #548

- geomstats/geometry/discretized_curves.py
- geomstats/geometry/landmarks.py
- geomstats/geometry/product_manifold.py
- tests/test_discretized_curves.py
- tests/test_landmarks.py
- tests/test_product_manifold.py
This PR continues to address issue #338. The strategy behind the refactorization/vectorization PRs is explained in a post in the associated issue #338.
> Vectorization of Landmarks, DiscretizedCurves and ProductManifold

- examples/empirical_frechet_mean_uncertainty_sn.py
- geomstats/_backend/pytorch/__init__.py
- geomstats/geometry/connection.py
- geomstats/geometry/matrices.py
- geomstats/learning/exponential_barycenter.py
- geomstats/learning/frechet_mean.py
- geomstats/learning/kmeans.py
- geomstats/vectorization.py
- tests/test_exponential_barycenter.py
- tests/test_frechet_mean.py
- tests/test_matrices.py
- tests/test_online_kmeans.py
- tests/test_riemannian_kmeans.py
This PR continues to address issue #338. The strategy behind the refactorization/vectorization PRs is explained in a post in the associated issue #338.
> Vectorization of FrechetMean, KMeans and ExponentialBarycenter

- geomstats/_backend/pytorch/linalg.py
- geomstats/_backend/tensorflow/linalg.py
- geomstats/geometry/hyperbolic.py
- geomstats/geometry/hypersphere.py
- geomstats/geometry/symmetric_matrices.py
- tests/test_grassmannian.py
- tests/test_hyperbolic.py
- tests/test_hypersphere.py
- tests/test_spd_matrices.py
- tests/test_stiefel.py
Pass tests in hypersphere, hyperbolic, stiefel, and grassmanian.
> Adapt code to pass more unit tests in tf and pytorch

- geomstats/_backend/numpy/__init__.py
- geomstats/_backend/pytorch/__init__.py
- geomstats/_backend/tensorflow/__init__.py
- geomstats/geometry/general_linear.py
- geomstats/geometry/hypersphere.py
- tests/test_general_linear.py
- tests/test_hypersphere.py
Reverts geomstats/geomstats#583
> Revert "Adapt random in GeneralLinear and Hypersphere to work with Tensorflow"

- README.md
- docs/first-steps.rst
This PR updates the README and:
- adds a high-level description of geomstats,
- distinguishes between pip3 and git clone installations of geomstats,
- adds a code snippet of an elementary example.
> Update README 

- geomstats/geometry/special_orthogonal.py
- requirements.txt
This PR bumps tf to 2.1.0, and addresses issue #495.
> Bump tf to newer version 2.1.0

- examples/geomstats_in_pymanopt.py
- examples/gradient_descent_s2.py
- examples/learning_graph_structured_data_h2.py
- geomstats/_backend/numpy/common.py
- geomstats/geometry/beta_distributions.py
- geomstats/geometry/hypersphere.py
- geomstats/geometry/lie_algebra.py
- geomstats/geometry/manifold.py
- geomstats/geometry/poincare_polydisk.py
- geomstats/tests.py
- geomstats/visualization.py
- tests/test_backends.py
Partially addresses issue #501.
> Clean the codebase by addressing DeepSource issues

- geomstats/_backend/pytorch/__init__.py
- geomstats/_backend/tensorflow/__init__.py
- geomstats/geometry/hypersphere.py
- geomstats/geometry/poincare_ball.py
- geomstats/tests.py
- tests/test_backends.py
- tests/test_hypersphere.py
> Debug assignment for booleans in tf and use it for Poincare ball

- .travis.yml
- README.md
- docs/first-steps.rst
- opt-requirements.txt
- requirements.txt
> Make tf and torch requirements optional

- .vscode/settings.json
- examples/geomstats_in_pymanopt.py
- geomstats/_backend/pytorch/linalg.py
- geomstats/geometry/beta_distributions.py
- tests/test_beta_distributions.py
- tests/test_discretized_curves.py
- tests/test_euclidean.py
- tests/test_grassmannian.py
- tests/test_hypersphere.py
- tests/test_invariant_metric.py
- tests/test_landmarks.py
- tests/test_manifold.py
- tests/test_matrices.py
- tests/test_minkowski.py
- tests/test_preprocessing.py
- tests/test_product_manifold.py
- tests/test_skew_symmetric_matrices.py
- tests/test_special_euclidean3.py
- tests/test_special_orthogonal.py
- tests/test_stiefel.py
- tests/test_vectorization.py
- tests/test_visualization.py
> Continue to address DeepSource issues

- examples/learning_graph_structured_data_h2.py
- examples/plot_bch_so3.py
- geomstats/datasets/graph_data_preparation.py
- geomstats/geometry/discretized_curves.py
- geomstats/geometry/hyperboloid.py
- setup.py
This finishes to address issue #501.
> Address remaining DeepSource issues

- geomstats/__init__.py
Merging this into master to update current version of PyPi.
> Bump to v2.0.0

- geomstats/learning/kernel_density_estimation_classifier.py
- geomstats/learning/radial_kernel_functions.py
- tests/test_kernel_density_estimation_classifier.py
- tests/test_radial_kernel_functions.py
Add the kernel density estimation classifier and a file containing usual kernels.
> Add the kernel density estimation classifier.

- examples/geomstats_in_pymanopt.py
[WIP]
This example has bugs, maybe following latest updates of pymanopt?
> Fix pymanopt example

- geomstats/geometry/manifold.py
- geomstats/geometry/special_orthogonal.py
- tests/test_special_orthogonal.py
- tests/test_special_orthogonal3.py
> Remove assignments in so3

- notebooks/04_simple_machine_learning_tangent_spaces.ipynb
from test to train and vice versa
> remove confusion

- geomstats/_backend/pytorch/linalg.py
Passed my local tests as well as all nose2 tests (excluding known karate club dataset import issue in a notebook).
> Change symmetric eigenvalue, eigenvector func from np to torch

- notebooks/01_data_on_manifolds.ipynb
> fix notebook typo

- examples/kalman_filter.py
- examples/loss_and_gradient_se3.py
- geomstats/_backend/pytorch/__init__.py
- geomstats/geometry/hyperbolic.py
- geomstats/geometry/poincare_half_space.py
- geomstats/geometry/special_orthogonal.py
- tests/test_hyperbolic_coords.py
- tests/test_poincare_half_space.py
Continuing #790 from @AliceLeBrigant to create a class for the Poincare Half-space representation of the hyperbolic space. However, maybe this representation could fit in the existing class, by adding the change of coordinate functions in the Hyperbolic class?
> Poincarre halfspace

- geomstats/geometry/poincare_half_space.py
- tests/test_poincare_half_space.py
Continue with development of Poincare half space.
> Poincare half space (continued)

- README.md
- geomstats/geometry/normal_distributions.py
- geomstats/geometry/poincare_half_space.py
- tests/test_normal_distributions.py
Create the manifold of normal distributions, i.e. the parameter space of normal distributions endowed with the Fisher-Rao metric, which is the Poincaré upper half plane.
> Create manifold of normal distributions

- geomstats/geometry/beta_distributions.py
- geomstats/geometry/normal_distributions.py
- tests/test_beta_distributions.py
- tests/test_normal_distributions.py
Compute pdf associated to a point in the manifold of normal distributions.
> Normal distributions

- geomstats/geometry/beta_distributions.py
- tests/test_beta_distributions.py
This answers [issue#865](https://github.com/geomstats/geomstats/issues/865).
> Fix vectorization of Exp and Log of beta distributions

- geomstats/geometry/beta_distributions.py
- geomstats/geometry/euclidean.py
- geomstats/geometry/grassmannian.py
- geomstats/geometry/hyperboloid.py
- geomstats/geometry/invariant_metric.py
- geomstats/geometry/lie_algebra.py
- geomstats/geometry/lie_group.py
- geomstats/geometry/matrices.py
- geomstats/geometry/minkowski.py
- geomstats/geometry/poincare_ball.py
- geomstats/geometry/product_riemannian_metric.py
- geomstats/geometry/riemannian_metric.py
- geomstats/geometry/skew_symmetric_matrices.py
- geomstats/geometry/special_euclidean.py
- geomstats/geometry/special_orthogonal.py
- geomstats/geometry/symmetric_matrices.py
- tests/test_beta_distributions.py
- tests/test_connection.py
- tests/test_euclidean.py
- tests/test_invariant_metric.py
- tests/test_lie_algebra.py
- tests/test_matrices.py
- tests/test_minkowski.py
- tests/test_product_manifold.py
- tests/test_special_euclidean3.py
- tests/test_special_orthogonal3.py
Compute Riemann curvature on lie groups with an invariant metric:
- renamed inner_product_matrix to metric_matrix, because it's shorter
- Add invariant metrics represented by a diagonal matrix (#702 )
This is currently tested on SO(n), but will be tested on SE(n) in a next PR: need to create its Lie Algebra first
> Invariant Metrics

- geomstats/geometry/beta_distributions.py
- geomstats/geometry/connection.py
- geomstats/geometry/invariant_metric.py
- geomstats/integrator.py
- tests/test_integrator.py
- tests/test_invariant_metric.py
These can be used in three different settings:
- Classic geodesic equation with Christoffel symbols
- Geodesic equation on a Lie group, where the acceleration is computed in the Lie algebra
- Hamiltonian systems (yet to come in geomstats #881)
> Harmonize integration schemes

- geomstats/geometry/invariant_metric.py
This continues #875 to include right-invariant metrics on Lie groups. This will be tested with #884.
> Right invariant metric on Lie Groups

- geomstats/geometry/invariant_metric.py
- geomstats/geometry/lie_algebra.py
- geomstats/geometry/lie_group.py
- geomstats/geometry/riemannian_metric.py
- geomstats/geometry/skew_symmetric_matrices.py
- geomstats/geometry/special_euclidean.py
- geomstats/geometry/special_orthogonal.py
- tests/test_invariant_metric.py
- tests/test_lie_algebra.py
- tests/test_skew_symmetric_matrices.py
- tests/test_special_euclidean.py
This addresses #879 and will allow to use #878 on the Special Euclidean group
> Add lie algebra for matrix SE(n)

- geomstats/geometry/beta_distributions.py
- geomstats/geometry/connection.py
- geomstats/geometry/dirichlet_distributions.py
- tests/test_beta_distributions.py
- tests/test_dirichlet_distributions.py
Generalizing code from ```beta_distributions``` to arbitrary dimensions. It is quite straightforward thanks to the clean code of @nguigs !
> Create dirichlet distributions

- examples/learning_graph_embedding_and_predicting.py
- geomstats/geometry/connection.py
- geomstats/geometry/invariant_metric.py
- geomstats/geometry/riemannian_metric.py
- geomstats/learning/kmedoids.py
- tests/test_hypersphere.py
- tests/test_invariant_metric.py
- tests/test_poincare_ball.py
> Parallelize pairwise_dist

- .travis.yml
- geomstats/_backend/numpy/__init__.py
- geomstats/_backend/pytorch/__init__.py
- geomstats/geometry/special_orthogonal.py
- tests/test_special_euclidean3.py
- tests/test_special_orthogonal3.py
Inplace operations in special orthogonal and euclidean groups prevent from computing gradients. This should fix #904.
> Remove inplace operations

- geomstats/geometry/connection.py
- geomstats/geometry/fiber_bundle.py
- geomstats/geometry/hypersphere.py
- geomstats/geometry/invariant_metric.py
- geomstats/geometry/pre_shape.py
- geomstats/geometry/quotient_metric.py
- geomstats/geometry/riemannian_metric.py
- tests/test_hypersphere.py
- tests/test_pre_shape.py
- tests/test_quotient_metric.py
Add O'Neill's formula to compute the curvature of Riemannian submersions, and application in Kendall shape space.
> add O'Neill's formula for curvature

- geomstats/geometry/spd_matrices.py
- geomstats/geometry/symmetric_matrices.py
- geomstats/learning/frechet_mean.py
- tests/test_examples.py
As an outcome of discussions aroud #913 and #920, this PR divides the step size by 2 in the case the gradient descent starts diverging.
> Adapt step size in Frechet Mean

- geomstats/learning/frechet_mean.py
It had slipped through the previous merge of master into local branch in #935
> use step size in gradient descent

- .gitignore
- docs/api-reference.rst
- docs/datasets.rst
Generated .rst files for datasets module and added reference to  it in api-reference.rst
> Added rst files for datasets

- .travis.yml
This is a fake PR. I have just added t pandoc --version to travis.yml to check whether pandoc is installed
> added pandoc --version to check if pandoc is installed

- geomstats/geometry/hypersphere.py
- geomstats/geometry/invariant_metric.py
- geomstats/geometry/special_orthogonal.py
- tests/test_exponential_barycenter.py
- tests/test_frechet_mean.py
- tests/test_hypersphere.py
- Fix the random uniform method of SO(n)
- Generalize the von Mises-Fisher distribution to any dimension and any mean point
> Sampling on Manifolds

- geomstats/geometry/riemannian_metric.py
- geomstats/geometry/special_orthogonal.py
- geomstats/learning/kernel_density_estimation_classifier.py
- tests/test_hypersphere.py
- tests/test_kernel_density_estimation_classifier.py
- tests/test_riemannian_kmeans.py
+ rewrite inner_product @mvesin 
+ Use taylor approx in quaternion to rot vec and back, this should help #924 @Maya95assal
> Use taylor approx for precision in quaternion to rot vec

- geomstats/geometry/special_orthogonal.py
- geomstats/learning/frechet_mean.py
- tests/test_frechet_mean.py
- tests/test_special_orthogonal.py
And add some tests to improve coverage
> use lie algebra attribute for skew to vec

- geomstats/algebra_utils.py
- geomstats/geometry/invariant_metric.py
- geomstats/geometry/lie_group.py
- geomstats/geometry/pre_shape.py
- geomstats/geometry/special_euclidean.py
- geomstats/geometry/special_orthogonal.py
- tests/test_special_euclidean.py
This PR addresses #975 
- flip determinant for rotation matrices
- check determinant in belongs of SO(n)
- factorize flip determinant in preshape
> Adress special orthogonal issues

- geomstats/_backend/pytorch/__init__.py
- geomstats/algebra_utils.py
- geomstats/geometry/invariant_metric.py
- geomstats/geometry/lie_group.py
- geomstats/geometry/poincare_ball.py
- geomstats/geometry/pre_shape.py
- geomstats/geometry/special_euclidean.py
- geomstats/geometry/special_orthogonal.py
- tests/test_algebra_utils.py
- tests/test_poincare_ball.py
- tests/test_special_euclidean.py
> Simplify code in Poincaré ball

- geomstats/geometry/grassmannian.py
- geomstats/geometry/invariant_metric.py
- geomstats/geometry/lie_group.py
- geomstats/geometry/matrices.py
- geomstats/geometry/spd_matrices.py
- geomstats/geometry/special_euclidean.py
- geomstats/geometry/special_orthogonal.py
- geomstats/geometry/symmetric_matrices.py
- geomstats/learning/frechet_mean.py
- tests/helper.py
- tests/tests_geomstats/test_grassmannian.py
- tests/tests_geomstats/test_preprocessing.py
- tests/tests_geomstats/test_special_euclidean.py
- tests/tests_geomstats/test_special_orthogonal.py
- tests/tests_geomstats/test_symmetric_matrices.py
- Avoid bug in `random_point` of `SymmetricMatrices`
- fix `to_tangent` in `Grassmannian` so that it is indeed a projection (previously sent tangent vectors to 0)
- change test for Euclidean metric: all child classes of `EuclideanMetric` were considered Euclidean in `FrechetMean`. It now works on e.g. Grassmannian metric
> Some Fixes

- geomstats/_backend/tensorflow/linalg.py
- geomstats/geometry/connection.py
- geomstats/geometry/dirichlet_distributions.py
- geomstats/geometry/hyperboloid.py
- geomstats/geometry/hypersphere.py
- geomstats/geometry/invariant_metric.py
- geomstats/geometry/pre_shape.py
- geomstats/geometry/symmetric_matrices.py
- geomstats/integrator.py
- tests/helper.py
- tests/tests_geomstats/test_dirichlet_distributions.py
- tests/tests_geomstats/test_integrator.py
- tests/tests_geomstats/test_pre_shape.py
- Reformat integration module to work with ODEs of any number of variables that must be stacked in one array instead of tuples
- Parallel transport by integration
> Parallel transport in Kendall shape spaces by integration

- geomstats/learning/frechet_mean.py
- tests/tests_geomstats/test_frechet_mean.py
> fix check for linear metrics

- geomstats/geometry/product_manifold.py
> pass n_jobs to metric

- geomstats/geometry/connection.py
- geomstats/geometry/general_linear.py
- geomstats/geometry/lie_algebra.py
- geomstats/geometry/manifold.py
- geomstats/geometry/riemannian_metric.py
- geomstats/geometry/skew_symmetric_matrices.py
- geomstats/geometry/spd_matrices.py
- geomstats/geometry/symmetric_matrices.py
- tests/tests_geomstats/test_lie_algebra.py
- Remove `OpenSet` inheritance in `SymmetricMatrices` (it's not an open set in the set of Matrices)
- Use the setter when initializing the metric (addresses #1048)
> Minor fixes

- docs/contributing.rst
> Fix link to template unit-tests

- geomstats/geometry/categorical_distributions.py
- tests/tests_geomstats/test_categorical_distributions.py
New clean PR.
The manifold of categorical distributions with $n+1$ outcomes is the $n$-simplex. The Fisher-Rao geometry is just the pullback of the hypersphere metric by the map that takes the square root of each component.
> Categorical distributions with Fisher-Rao metric

- .github/workflows/build.yml
> Add Python3.9 to unit-tests

- .github/workflows/build.yml
- dev-requirements.txt
this pr moves from nose2 to pytest
> pytest migration

- .github/workflows/format.yml
testing for black auto formatting
> auto black format

- geomstats/_backend/__init__.py
- geomstats/_backend/autograd/linalg.py
- geomstats/_backend/numpy/linalg.py
- geomstats/_backend/pytorch/linalg.py
- geomstats/_backend/tensorflow/linalg.py
- geomstats/geometry/full_rank_matrices.py
- tests/tests_geomstats/test_full_rank_matrices.py
Adding the class for full rank matrices and change the backend adding np.linalg.matrix_rank
> full rank matrices

- geomstats/_backend/tensorflow/__init__.py
- geomstats/learning/mdm.py
- notebooks/usecase_emg_sign_classification_in_spd_manifold.ipynb
- tests/tests_geomstats/test_backends.py
I am sorry, but #1188 has been merged too quickly for me: I had not commited my last developments.
> Improve MDM, 2

- geomstats/learning/mdm.py
- tests/tests_geomstats/test_mdm.py
This PR aims to:
- add the function `predict_proba` to MDM classifier;
- complete and update tests for MDM.
> Add predict_proba to MDM

- geomstats/information_geometry/dirichlet.py
- tests/tests_geomstats/test_dirichlet.py
> Fix issue #1083

- geomstats/geometry/base.py
- geomstats/geometry/full_rank_correlation_matrices.py
- geomstats/geometry/grassmannian.py
- geomstats/geometry/hyperboloid.py
- geomstats/geometry/hypersphere.py
- geomstats/geometry/pre_shape.py
- geomstats/geometry/special_euclidean.py
- geomstats/geometry/special_orthogonal.py
- geomstats/geometry/stiefel.py
- geomstats/information_geometry/categorical.py
To match the mathematical definitions of a manifold and the architecture defined in #1006.
> rename EmbeddedManifold into LevelSet

- geomstats/_backend/autograd/autodiff.py
- geomstats/_backend/pytorch/autodiff.py
- geomstats/_backend/tensorflow/autodiff.py
> Add documentation in autodiff modules

- geomstats/geometry/landmarks.py
- geomstats/geometry/riemannian_metric.py
- geomstats/integrator.py
- tests/test_integrator.py
- tests/test_landmarks.py
WIP (continuation of #881)
This is to help creating a kernel metric on the space of landmarks in R^d. Some work remains to adapt the existing integration modules to the hamiltonian equations.
> Template for lddmm metric on landmarks

- geomstats/geometry/stiefel.py
- tests/tests_geomstats/test_stiefel.py
Stiefel logarithm raises an error if point and base_point are not in the same sheet for p=n.
> Xpennec stiefel tests

- examples/empirical_frechet_mean_uncertainty_sn.py
- geomstats/learning/frechet_mean.py
> Allow to pass initial point to FrechetMean estimator

- geomstats/_backend/pytorch/linalg.py
- geomstats/_backend/tensorflow/linalg.py
- tests/tests_geomstats/test_backends.py
> add subcase to tensorflow + add test

- .deepsource.toml
> Adapt DeepSource config

- tests/conftest.py
- tests/tests_geomstats/test_symmetric_matrices.py
cleaned tests in symmetric_matrices
> clean test_symmetric_matrices

- geomstats/_backend/tensorflow/__init__.py
- geomstats/geometry/_my_manifold.py
- geomstats/geometry/base.py
- geomstats/geometry/connection.py
- geomstats/geometry/discrete_curves.py
- geomstats/geometry/euclidean.py
- geomstats/geometry/heisenberg.py
- geomstats/geometry/invariant_metric.py
- geomstats/geometry/lie_group.py
- geomstats/geometry/manifold.py
- geomstats/geometry/matrices.py
- geomstats/geometry/product_manifold.py
- geomstats/geometry/rank_k_psd_matrices.py
- geomstats/geometry/riemannian_metric.py
- geomstats/geometry/special_euclidean.py
- geomstats/geometry/special_orthogonal.py
- tests/helper.py
- tests/tests_geomstats/test_product_manifold.py
For the direct product of a given manifold repeated n times.
> Introduce n-fold manifolds

- .github/workflows/docs.yml
- docs/geometry.rst
following PR fixes docs github action
> build docs through commands not through action

- .github/workflows/docs.yml
try something diff because it's not working
> Add more conditions to docs.yml

- tests/properties.py
> create manifold properties

- tests/data_generation.py
- tests/parametrizers.py
- tests/tests_geomstats/test_stiefel.py
- tests/tests_geomstats/test_symmetric_matrices.py
this is continuation  of #1330
> Professor nina doc string pr

- tests/data_generation.py
- tests/parametrizers.py
- tests/tests_geomstats/test_backends.py
- tests/tests_geomstats/test_spd_matrices.py
- tests/tests_geomstats/test_stiefel.py
- tests/tests_geomstats/test_symmetric_matrices.py
> Spd refactoring

- geomstats/information_geometry/dirichlet.py
- tests/tests_geomstats/test_dirichlet.py
- Add `_approx_geodesic_bvp` method that solves an approximation of the boundary value problem by minimizing the energy among curves whose coefficients are polynomial functions of time
- Use this in `_geodesic_bvp` as an initialization when solving the geodesic ODE.
> Polynomial initialization of geodesics in DirichletDistributions

- geomstats/geometry/special_euclidean.py
closes #1375 #1376 #879 
Currently not tested, but we can merge and it will be tested in #1371 @SaitejaUtpala ?
> add lie algebra of SEn vector representation

- geomstats/geometry/special_euclidean.py
- tests/tests_geomstats/test_special_euclidean.py
> Add random point to SE Lie Algebra

- tests/data_generation.py
*  except exp_shape and log_shape naming conventions are finalized. Because for changing this we have to change all test_files. naming conventions in test_files along exp_shape and log_shape will be raised in another PR
> Naming conventions - I

- tests/tests_geomstats/test_general_linear.py
- tests/tests_geomstats/test_heisenberg.py
* add vector space test cases to Heisenberg
* add open space test cases to General Linear
> Use multiple parent test cases

- geomstats/geometry/manifold.py
- tests/data_generation.py
- tests/geometry_test_cases.py
- tests/tests_geomstats/test_euclidean.py
- tests/tests_geomstats/test_full_rank_correlation_matrices.py
- tests/tests_geomstats/test_full_rank_matrices.py
- tests/tests_geomstats/test_general_linear.py
- tests/tests_geomstats/test_grassmannian.py
- tests/tests_geomstats/test_heisenberg.py
- tests/tests_geomstats/test_hyperbolic.py
- tests/tests_geomstats/test_hypersphere.py
- tests/tests_geomstats/test_invariant_metric.py
- tests/tests_geomstats/test_landmarks.py
- tests/tests_geomstats/test_lower_triangular_matrices.py
- tests/tests_geomstats/test_matrices.py
- tests/tests_geomstats/test_minkowski.py
- tests/tests_geomstats/test_poincare_ball.py
- tests/tests_geomstats/test_poincare_half_space.py
- tests/tests_geomstats/test_poincare_polydisk.py
- tests/tests_geomstats/test_positive_lower_triangular_matrices.py
- tests/tests_geomstats/test_pre_shape.py
- tests/tests_geomstats/test_product_manifold.py
- tests/tests_geomstats/test_rank_k_psd_matrices.py
- tests/tests_geomstats/test_skew_symmetric_matrices.py
- tests/tests_geomstats/test_spd_matrices.py
- tests/tests_geomstats/test_special_euclidean.py
- tests/tests_geomstats/test_special_orthogonal.py
- tests/tests_geomstats/test_stiefel.py
- tests/tests_geomstats/test_symmetric_matrices.py
Based on discussion with @nguigs  @ninamiolane. also tests are skipped for product manifold (shapes of it are not correct for it to work).
> Random tangent vec in root class of Manifold and corresponding parametrized test in all manifolds (except product)

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/docs_suggestion.yml
- .github/ISSUE_TEMPLATE/general_template.yml
This PR adds issue templates.
- Bug
- Documentation
- General question
- Links to documentation and slack.
> Added issue templates.

- tests/data_generation.py
- tests/geometry_test_cases.py
- tests/tests_geomstats/test_euclidean.py
- tests/tests_geomstats/test_full_rank_correlation_matrices.py
- tests/tests_geomstats/test_general_linear.py
- tests/tests_geomstats/test_grassmannian.py
- tests/tests_geomstats/test_heisenberg.py
- tests/tests_geomstats/test_hyperbolic.py
- tests/tests_geomstats/test_hypersphere.py
- tests/tests_geomstats/test_invariant_metric.py
- tests/tests_geomstats/test_landmarks.py
- tests/tests_geomstats/test_matrices.py
- tests/tests_geomstats/test_minkowski.py
- tests/tests_geomstats/test_poincare_ball.py
- tests/tests_geomstats/test_poincare_half_space.py
- tests/tests_geomstats/test_positive_lower_triangular_matrices.py
- tests/tests_geomstats/test_pre_shape.py
- tests/tests_geomstats/test_product_manifold.py
- tests/tests_geomstats/test_skew_symmetric_matrices.py
- tests/tests_geomstats/test_spd_matrices.py
- tests/tests_geomstats/test_special_euclidean.py
- tests/tests_geomstats/test_special_orthogonal.py
- tests/tests_geomstats/test_stiefel.py
after discussion @nguigs , order is more explicit for composition. But basis_representation_then_matrix_representation_composition is crossing 89 characters(linting wouldn't pass). @ninamiolane  @nguigs  Let me know what would be ideal here
> log_exp to log_then_exp

- geomstats/geometry/grassmannian.py
> change error to ensure k < n

- .github/CODE_OF_CONDUCT.md
This PR fixes #1433 and aims at adding the code of conduct in the repository.
> Adds code of conduct

- .github/workflows/test.yml
Addresses #1198 
Here is a preview of how it works: (`assert 3==4` is a dummy line)
Note that it comments for every error found for each job in the matrix.
> Add action for pytest annotation

- geomstats/geometry/connection.py
- geomstats/geometry/grassmannian.py
- geomstats/geometry/hyperboloid.py
- geomstats/geometry/hypersphere.py
- geomstats/geometry/invariant_metric.py
- geomstats/geometry/minkowski.py
- geomstats/geometry/poincare_ball.py
- geomstats/geometry/poincare_half_space.py
- geomstats/geometry/pre_shape.py
- geomstats/geometry/spd_matrices.py
- geomstats/geometry/special_euclidean.py
- geomstats/geometry/stiefel.py
- geomstats/information_geometry/dirichlet.py
After discussions with @SaitejaUtpala and @ythanwerdas, we add a method to return the injectivity radius at a given base point.
> Add injectivity radius of all metrics

- tests/geometry_test_cases.py
Add empty tests with docstrings to help writing test functions for parent metrics.
This does not fix any issue.
N/A.
> Add signature of test functions for parent metrics.

- geomstats/geometry/matrices.py
- geomstats/geometry/spd_matrices.py
- tests/data/spd_matrices_data.py
- tests/tests_geomstats/test_spd_matrices.py
> compute log euclidean in closed form

- geomstats/_backend/__init__.py
- geomstats/_backend/autograd/__init__.py
- geomstats/_backend/numpy/__init__.py
- geomstats/_backend/pytorch/__init__.py
- geomstats/_backend/tensorflow/__init__.py
> Add trapz to backends

- geomstats/geometry/riemannian_metric.py
- tests/data/riemannian_metric_data.py
- tests/tests_geomstats/test_riemannian_metric.py
implementation of:
-normalize(vector, base_point) which normalizes vector at base_point
-random_unit_tangent_vec(base_point, n_vectors) which generates n_vectors random unit tangent vectors at base_point if base_point is a single point, and a tangent vector for each point of base_point
> updates to riemannian metric

- geomstats/learning/wrapped_gaussian_process.py
- tests/tests_geomstats/test_wrapped_gaussian_process.py
Besides simplifying some code in `WrappedGaussianProcess`, this PR aims to understand the reason for `TestWrappedGaussianProcess::test_predict_hypersphere` be failing often.
> Simplify WrappedGaussianProcess

- geomstats/_backend/__init__.py
- geomstats/_backend/autograd/__init__.py
- geomstats/_backend/numpy/__init__.py
- geomstats/_backend/pytorch/__init__.py
- geomstats/_backend/tensorflow/__init__.py
- tests/tests_geomstats/test_backends.py
Useful resources:
* [numpy.pad](https://numpy.org/doc/stable/reference/generated/numpy.pad.html)
* [tf.pad](https://www.tensorflow.org/api_docs/python/tf/pad)
* [torch.nn.functional.pad](https://pytorch.org/docs/stable/generated/torch.nn.functional.pad.html#torch.nn.functional.pad)
> Add pad to backend

- docs/governance.rst
> Enhance governance's page

- geomstats/geometry/hypersphere.py
- geomstats/geometry/pre_shape.py
- geomstats/geometry/quotient_metric.py
Fix lint issues coming from #1560 (issues passed due to error in github actions).
> Fix lint issues due to #1560

- docs/hackathons.rst
- docs/index.rst
> Add hackathon page to website

- .github/workflows/docs.yml
- .github/workflows/lint.yml
- .github/workflows/test.yml
- setup.cfg
This PR will:
-handle dependencies more clearly
-do not install all the backends during the test of a specific backend
> Improve dependency handling and CI installations

- tests/tests_geomstats/test_examples.py
This PR creates a new testing strategy for examples following what was already done for notebooks. In particular:
* any file added to `examples` will be automatically tested (e.g. currently two example were being completely ignored).
* files can be ignored by adding the to `SKIP` set
* backends in which to run can be set in `METADATA`
* any argument to pass to `example.main()` can be set in `METADATA`
> Refactor test_examples following test_notebooks strategy

- notebooks/02_foundations__connection_riemannian_metric.ipynb
> Final Draft of Instructional Notebook for the Connection and RiemannianMetric Classes

- tests/tests_geomstats/test_euclidean.py
- tests/tests_geomstats/test_lower_triangular_matrices.py
It unskips some standard tests in Euclidean
> unskip tests

- tests/conftest.py
Fix small bug introduced in #1609.
> Fix bug in collecting test data

- geomstats/geometry/discrete_curves.py
> Fix vertical -> horizontal in docstring of discrete curves

- geomstats/datasets/utils.py
- geomstats/geometry/connection.py
- geomstats/geometry/euclidean.py
- geomstats/geometry/grassmannian.py
- geomstats/geometry/heisenberg.py
- geomstats/geometry/hyperboloid.py
- geomstats/geometry/hypersphere.py
- geomstats/geometry/invariant_metric.py
- geomstats/geometry/minkowski.py
- geomstats/geometry/poincare_ball.py
- geomstats/geometry/poincare_half_space.py
- geomstats/geometry/positive_lower_triangular_matrices.py
- geomstats/geometry/pre_shape.py
- geomstats/geometry/product_manifold.py
- geomstats/geometry/product_riemannian_metric.py
- geomstats/geometry/pullback_metric.py
- geomstats/geometry/riemannian_metric.py
- geomstats/geometry/sasaki_metric.py
- geomstats/geometry/spd_matrices.py
- geomstats/geometry/stiefel.py
- geomstats/geometry/sub_riemannian_metric.py
- geomstats/learning/agglomerative_hierarchical_clustering.py
- geomstats/learning/frechet_mean.py
- geomstats/learning/geometric_median.py
- geomstats/learning/incremental_frechet_mean.py
- geomstats/learning/kernel_density_estimation_classifier.py
- geomstats/learning/knn.py
- geomstats/learning/wrapped_gaussian_process.py
Correct equations, references, bullet points, etc rendering in documentation (following #1544 and #1549).
No code modification.
There are still mistakes in the documentation formatting.
> Correct documentation rendering, 3rd part

- docs/api/learning.rst
- geomstats/learning/exponential_barycenter.py
- geomstats/learning/frechet_mean.py
- geomstats/learning/geometric_median.py
- tests/data/geometric_median_data.py
- tests/tests_geomstats/test_geometric_median.py
This PR aims to improve code, correct documentation and complete tests for geometric median.
It also suggests to add the geometric median into the API.
Related to #1565
> Improve code and complete tests for geometric median

- geomstats/_backend/autograd/autodiff.py
Adds to #1664.
@ninamiolane, if I'm not overlooking anything, the suggested implementation reduces the number of computations of `jacobian(x)` by one. The jacobian of `x` is still computed twice: one within `jacobian(func)(x)` and another in `_value_and_jacobian`, but I think it is just the way automatic differentiation works (at least in `autograd`).
> Improve jacobian_and_hessian in autograd

- notebooks/01_foundations__manifolds.ipynb
- notebooks/09_practical_methods__implement_your_own_riemannian_geometry.ipynb
> Fixes math renderings in notebook tutorials

- geomstats/geometry/manifold.py
Make comments and error more clear.
> Improve comments and error for random_tangent_vec

- README.rst
- docs/getting_started/first-steps.rst
Add conda install command
@ymontmarin : does this also work on windows with Anaconda Prompt?
> Add conda install guidelines

- geomstats/geometry/siegel.py
- tests/data/siegel_data.py
- tests/tests_geomstats/test_siegel.py
References
----------
.. [Cabanes2022] Yann Cabanes. Multidimensional complex stationary
centered Gaussian autoregressive time series machine learning
in Poincaré and Siegel disks: application for audio and radar
clutter classification, PhD thesis, 2022
.. [Cabanes2021] Yann Cabanes and Frank Nielsen.
New theoreticla tools in the Siegel space for vectorial
autoregressive data classification,
Geometric Science of Information, 2021.
https://franknielsen.github.io/IG/GSI2021-SiegelLogExpClassification.pdf
> Add siegel sectional curvature

- docs/hackathons.rst
- docs/hackathons/ihp_10_2022.rst
An initial draft of a document explaining the decisions made during the last week hackathon.
@ninamiolane, @alebrigant, @nguigs, @xpennec, @sophiaas.
> "Outputs" of ihp hackathon

- docs/gsod.rst
> Update gsod.rst: Edits on case study

- geomstats/information_geometry/normal.py
Clean computation of univariate normal metric matrix.
> Simplify univariate normal metric matrix

- geomstats/geometry/positive_reals.py
- tests/data/positive_reals_data.py
Small simplifications to `PositiveRealsMetric` that I've missed out in #1701.
> Simplify PositiveRealsMetric

- geomstats/geometry/hpd_matrices.py
- geomstats/geometry/siegel.py
Small fix in `SiegelMetric` to work with tensorflow. (missed when changed #1727).
> Fix `SiegelMetric` for tf

- geomstats/geometry/poincare_polydisk.py
- geomstats/geometry/product_manifold.py
- geomstats/geometry/product_riemannian_metric.py
- geomstats/geometry/scalar_product_metric.py
- tests/data/product_manifold_data.py
closes #1759. (Verifications for `NFoldMetric` are not being done. To address in a future PR.)
`PoincarePolydiskMetric` transformed in a `NFoldMetric` (probably of your interest @YannCabanes).
> Remove scales product manifold

- examples/empirical_frechet_mean_uncertainty_sn.py
- examples/plot_bch_so3.py
- geomstats/_backend/autograd/_common.py
- geomstats/_backend/autograd/autodiff.py
- geomstats/_backend/numpy/_common.py
- geomstats/_backend/pytorch/_common.py
- geomstats/_backend/pytorch/linalg.py
- geomstats/_backend/tensorflow/linalg.py
- geomstats/errors.py
- geomstats/geometry/discrete_curves.py
- geomstats/geometry/euclidean.py
- geomstats/geometry/stratified/graph_space.py
- geomstats/geometry/symmetric_matrices.py
- geomstats/learning/frechet_mean.py
- geomstats/learning/pca.py
- geomstats/vectorization.py
- tests/conftest.py
- tests/data/special_euclidean_data.py
- tests/tests_geomstats/test_backends2.py
- tests/tests_geomstats/test_functions.py
- tests/tests_geomstats/test_mdm.py
- tests/tests_geomstats/test_prepare_emg_data.py
Address several deep source issues in the full codebase. (just followed deep source analysis and addressed (some) meaningful comments)
> Address deep source issues

- .github/ISSUE_TEMPLATE/config.yml
Fix a few typos in github issues config.
> Fix typos and dead link for issues.

- README.rst
> Remove tf from cov flags

- setup.cfg
> Keep sphinx at v 5.3.0

- geomstats/_backend/numpy/linalg.py
Fixes linting error in commit [1a15494](https://github.com/geomstats/geomstats/commit/1a1549458838a4ca3d99954de6a10a734c13ac91)
> Fix linting in 1a15494

- geomstats/_backend/numpy/linalg.py
- geomstats/geometry/base.py
Re-open PR #1787 after the fix for `sqrtm`.
> Follow-up PR #1787 

- tests/tests_geomstats/test_beta.py
- tests/tests_geomstats/test_complex_poincare_disk.py
- tests/tests_geomstats/test_normal.py
- tests/tests_geomstats/test_poincare_polydisk.py
- tests/tests_geomstats/test_special_euclidean.py
> Skip failing tests to clean CI

- README.rst
> Fix link to contributing guide.

- geomstats/geometry/discrete_curves.py
> Fix align in SRVShapeBundle

- geomstats/geometry/riemannian_metric.py
1D distributions now has one more dimension than before (e.g. one point is of shape `(1,)` instead of `()`;  for n points, `(n,)` became `(n,1)`). For example, the code below will produce errors.
```
from geomstats.information_geometry.exponential import ExponentialDistributions
space = ExponentialDistributions()
base_point = space.random_point()
unit_vector = space.metric.random_unit_tangent_vec(base_point)
```
> Fix bad squeezes in random_unit_tangent_vec

- setup.cfg
- tests/tests_scripts/test_notebooks.py
I was following the instructions [here](https://geomstats.github.io/contributing/index.html#development-setup) to create a developer setup, ran into small issues and made the corresponding small fixes. 
- codecov has been [removed from PyPi as deprecated](https://docs.codecov.com/docs/deprecated-uploader-migration-guide#python-uploader), removed from setup.cfg so that test requirements could be installed
- Some testing requires networkx, so I added it test requirements
- Now test_notebooks.py opens notebooks with encoding utf8 to avoid UnicodeDecodeError during testing
> Minor changes so Developer setup works

- geomstats/geometry/discrete_surfaces.py
This PR implements the Discrete Surfaces with second order Sobolev elastic metrics.
> Added Discrete Surfaces with Elastic Metrics

- docs/conf.py
- pyproject.toml
This unfreezes sphinx (frozen in #1784).
> Unfreeze sphinx

- geomstats/geometry/base.py
- geomstats/geometry/product_manifold.py
- tests/data/product_manifold_data.py
- tests/tests_geomstats/test_product_manifold.py
> Fix product metric

- README.rst
> Update README.rst: Python 3.7 --> 3.11

- README.rst
- geomstats/__init__.py
- pyproject.toml
This PR prepares new release.
@ymontmarin, what should we do for the conda release?
> Prepare release 2.6.0

- geomstats/geometry/discrete_curves.py
> Small Changes of Docstring in discrete_curves.py

- geomstats/geometry/discrete_curves.py
- [ x] My pull request has a clear and explanatory title.
- [ x] My PR follows [PEP8](https://peps.python.org/pep-0008/) guidelines. (refer to comment below)
- [ x] My PR follows [geomstats coding style](https://github.com/geomstats/geomstats/blob/master/docs/contributing.rst#coding-style-guidelines) and API.
- [x ] My code is properly documented and I made sure the documentation renders properly. ([Link](https://github.com/geomstats/geomstats/blob/master/docs/contributing.rst#documentation))
> Documentation PR: discrete_curves.py

- geomstats/geometry/lower_triangular_matrices.py
- geomstats/geometry/positive_lower_triangular_matrices.py
- tests/tests_geomstats/test_geometry/data/positive_lower_triangular_matrices.py
- tests/tests_geomstats/test_geometry/test_positive_lower_triangular_matrices.py
In this PR we implement an invariant metric for positive lower triangular matrices. Additionally, we endow the PositiveLowerTriangularMatrices with a LieGroup structure and a Lie algebra.
> Add invariant metric for positive lower triangular matrices 

- README.rst
> Update README.rst: Add FnT paper with link

- geomstats/geometry/discrete_surfaces.py
- [x ] My pull request has a clear and explanatory title.
- [x ] If necessary, my code is [vectorized](https://www.geeksforgeeks.org/vectorization-in-python/).
> Fixing bugs, vectorization, and docstring in discrete_surfaces

- geomstats/information_geometry/README.rst
> Update readme of information geometry module

- geomstats/geometry/discrete_curves.py
- geomstats/numerics/finite_differences.py
- tests/tests_geomstats/test_numerics/test_finite_differences.py
This PR fixes a bug on the computation of finite differences introduced in #1955.
> Fix finite differences

- docs/getting_started/first-steps.rst
This PR fixes the getting started examples as spotted out by Mahshid.
> Fix getting started examples

- geomstats/geometry/klein_bottle.py
- tests/tests_geomstats/test_geometry/data/klein_bottle.py
- tests/tests_geomstats/test_geometry/test_klein_bottle.py
Add Klein bottle parametrization conversion from instrinsic coordinates (dimension 2) to:
- Extrinsic coordinates (4 dimensional full parametrization)
- Klein bagel coordinates (3 dimension R^3 immersion)
- Klein bottle classical parametrization (3 dimension R^3 immersion)
> Klein bottle parametrization conversions

- geomstats/geometry/connection.py
- geomstats/geometry/invariant_metric.py
- geomstats/numerics/geodesic.py
- geomstats/test_cases/geometry/connection.py
@ninamiolane, as discussed, this PR removes time from the geodesic  equation signature.
> Remove time from geodesic_equation signature

- geomstats/geometry/pre_shape.py
Similarly to #1981, this PR implements `PreShapeMetric` as a `PullbackDiffeoMetric`. With the implementation done this way, we remove unnecessary and duplicate code and make more clear the relationship between the pre-shape space and the hypersphere.
> Implement PreShapeMetric as PullbackDiffeoMetric

- geomstats/_backend/__init__.py
Related to https://github.com/geomstats/geomstats/issues/1933
Change logging level of this message, and clarify that it applies to geomstats.
Note that this is not a complete fix for https://github.com/geomstats/geomstats/issues/1933, and agree with OP that geomstats should use its own logger rather than the root logger.
> Change logging level of this message, and clarify that it applies to geomstats.

- geomstats/geometry/fiber_bundle.py
- geomstats/geometry/quotient_metric.py
> Edit docstrings: specify that the quotient space is not a manifold, only its principal stratum is + note in alternating aligner

- geomstats/__init__.py
> Bump 2.8.0

- docs/contributing/index.rst
Quick fix to contributing guide steps, spotted by @dherrera1911 in #2027 (thank you, @dherrera1911! feel free to open PRs directly when you spot this kind of things).
closes #2027
> Fix upstream in contributing guide

- geomstats/algebra_utils.py
- geomstats/distributions/lognormal.py
- geomstats/geometry/connection.py
- geomstats/geometry/diffeo.py
- geomstats/geometry/discrete_curves.py
- geomstats/geometry/euclidean.py
- geomstats/geometry/fiber_bundle.py
- geomstats/geometry/pre_shape.py
- geomstats/geometry/pullback_metric.py
- geomstats/geometry/quotient_metric.py
- geomstats/geometry/spd_matrices.py
- geomstats/geometry/special_euclidean.py
- geomstats/geometry/stratified/bhv_space.py
- geomstats/information_geometry/categorical.py
- geomstats/information_geometry/fisher_rao_metric.py
- geomstats/information_geometry/multinomial.py
- geomstats/information_geometry/normal.py
- geomstats/integrator.py
- geomstats/learning/kalman_filter.py
- geomstats/learning/radial_kernel_functions.py
- geomstats/varifold.py
Correct equations, references, bullet points, etc rendering in documentation.
No code modification.
There are many mistakes in the current documentation https://geomstats.github.io/
> Improve documentation rendering

- .github/workflows/test.yml
This PR fixes codecov upload by using [codecov-action](https://github.com/codecov/codecov-action).
> Fix codecov upload
