.gitignore, LICENSE.md, README.md, geomstats/__init__.py, setup.py
Make the module geomstats available with pip, with MIT open source license.
=> Adding package to pypi

setup.py, tests/test_hyperbolic_space.py, tests/test_special_euclidean_group.py
Some unit tests were failing when I pulled master on my Mac. I added a new relative tolerance for some unit tests, which relative to the norm of the vector that is expected.
Also, I changed the version and released geomstats-1.0 (i.e. with debugged squared distance).
=> Nina adapt tests to mac

geomstats/invariant_metric.py, tests/test_special_euclidean_group.py, tests/test_special_orthogonal_group.py
Now exp_basis and log_basis in invariant_metric don't handle vectorization. Vectorization is handled by exp and log in riemannian_metric (from which invariant_metric inherits).
In addition, changes in the tests for special orthogonal group:
- more complete vectorization tests for exp, log, squared dist and dist
=> Fix bug in vectorization of metric operations for Lie groups

README.md, geomstats/embedded_manifold.py, geomstats/euclidean_space.py, geomstats/general_linear_group.py, geomstats/hyperbolic_space.py, geomstats/hypersphere.py, geomstats/invariant_metric.py, geomstats/lie_group.py, geomstats/manifold.py, geomstats/matrices_spaces.py, geomstats/minkowski_space.py, geomstats/riemannian_metric.py, geomstats/spd_matrices_space.py, geomstats/special_euclidean_group.py, geomstats/special_orthogonal_group.py, tests/test_manifold.py
Add asserts to check that the dimension's and n's initiating manifolds and groups are integers and > 0 (or > 1 depending on the cases).
Add the `point_representation` attribute to SO(n) and SE(n) to distinguish the cases where the elements of the groups are represented as vectors or as matrices (for geomstats' inner computations).
When elements are represented as vectors (`point_representation='vector'`), computing an inner product is done by x^T.Z.y where Z is the matrix corresponding to the inner product. When elements are represented as matrices, we implement a method that performs the inner_product on the matrices directly. I add the methods `inner_product` and `inner_product_at_identity` for this purpose.
Add the jacobian for SO(n).
=> Nina jacobian n

geomstats/backend/numpy.py, geomstats/special_orthogonal_group.py, tests/test_special_euclidean_group.py, tests/test_special_orthogonal_group.py
- Remove cast in special_orthogonal_group's regularize function
- Change convention for regularizing a rotation vector of norm pi : doesn't change the sign anymore
=> Nina regularisation

geomstats/special_orthogonal_group.py, tests/test_special_orthogonal_group.py
This CR adds conversion functions for Euler angles with different conventions:
- Tait Bryan convention,
- extrinsic and intrinsic conventions,
- xyz order and zyx order conventions.
This CR also renames yaw pitch roll with Tait Bryan appelations.
Some unit tests fail and are commented.
=> Nina tait bryan

geomstats/__about__.py, geomstats/__init__.py, setup.py
This PR adds "extra" installs, which allow optional functionality to be installed only if requested. It also adds a `geomstats.__version__` string, which is generally a good practice.
I use the `<package>/__about__.py` convention to store this metadata, so it's available both within the package and without.
Happy to rework if this doesn't fit with your development workflow.
Closes #136.
=>  ENH: Support optional dependencies, geomstats.__version__ 

examples/quantization_s1.py, examples/quantization_s2.py, geomstats/riemannian_metric.py, tests/test_hypersphere.py
I have changed the name ```optimal_quantization``` to ```riemannian_quantization``` and added it as a method of the ```RiemannianMetric``` class as we previously discussed. The test is in ```test_hypersphere.py``` and I moved the examples to https://github.com/geomstats/geomstats/tree/master/examples. 
If this is to be merged eventually, it would mean deleting the quantization folder in https://github.com/geomstats/examples.
=> Add quantization as method of RiemannianMetric

examples/loss_and_gradient_se3.py, geomstats/backend/tensorflow.py, geomstats/backend/tensorflow_linalg.py, geomstats/invariant_metric.py, geomstats/lie_group.py, geomstats/riemannian_metric.py, geomstats/special_euclidean_group.py, geomstats/special_orthogonal_group.py, tests/test_special_orthogonal_group.py
- geomstats/invariant_metric.py:
inner_product_at_identity():
- ensures that tangent_vec_a and tangent_vec_b have the same cardinality
- stack self.inner_product_mat_at_identity N times w.r.t. tangent_vec
inner_product_matrix():
- stack self.inner_product_mat_at_identity N times w.r.t. base_point
- geomstats/lie_group.py:
group_log():
- ensure point and base_point cardinality match for tf.einsum()
- geomstats/special_euclidean_group.py:
jacobian_translation():
- fix assert gs.ndim(jacobian) == 3
- geomstats/special_orthogonal_group.py:
regularize_tangent_vec():
- ensure jacobian has the same cardinality as tangent_vec
- N.B. TODO: check, this fix assumes there will always be one base_point to many tangent_vec
compose():
- ensures that point_1 and point_2 have the same cardinality
- stack …
=> tf backend fixes 3

geomstats/matrices_spaces.py, geomstats/spd_matrices_space.py
Hi ! I just noticed that there was a typo in matrices_spaces.py and that the ```signature``` attribute was missing for ```SPDMetric```, which prevents one from using the ```dist``` method (although there is no problem for ```squared_dist```).
=> Minor corrections

geomstats/backend/numpy.py, geomstats/backend/pytorch.py, geomstats/hypersphere.py, geomstats/riemannian_metric.py, tests/test_hypersphere.py
Debug of pytorch unit tests of hypersphere. The general precision of the results in the unit tests is usually a little worse in pytorch than in numpy, and so I have increases the tolerances.
Still the last one ```test_optimat_quantization.py``` is not working well, because the ```gap``` variable in the ```optimal_quantization``` method of ```riemannian_metric.py```, computed as the distance between ```center_to_update``` and ```new_center```, is sometimes zero with pytorch whereas it is non zero (but close) with numpy. I have traced this to the ```inner_product``` method of the embedding Euclidean metric, which seems to be less precise in pytorch than in numpy, but I don't understand why.
=> Debug pytorch tests hypersphere

geomstats/backend/__init__.py, geomstats/backend/common.py
Define the 'GEOMSTATS_BACKEND' environment variable if it's not
explicitly given when geomstats is imported.
This change also
- makes sure we error out if we're given an invalid backend name
- removes the 'common' module of the 'backend' package' as it only
re-exports 'numpy.pi'
Signed-off-by: Niklas Koep <niklas.koep@gmail.com>
=> Set GEOMSTATS_BACKEND if not given

geomstats/geometry/special_orthogonal_group.py
In SO(n) the inverse of a matrix can be easily caclulated by transposing the matrix. Depending on the input of points (vectorized or not) we have to keep the first index fixed (or not).
=> Improve SO(n) inverse

.travis.yml
Remove unit tests in tensorflow to temporarily speed-up travis continuous integration
=> Remove TF from travis backends

.travis.yml
Temporarily remove some CI to speed-up the hackathon
=> Remove unit tests in python 3.5 and 3.5-dev

geomstats/backend/pytorch.py
There was an unused rand function defined in the pytorch.py backend file. The current usage relies on the pytorch_random file.
=> remove vestigial rand function from pytorch.py backend

geomstats/backend/pytorch.py
The pytorch backend was missing the prod function despite its presence in the numpy backend. nose2 tests run before and after the change show no new errors. The pytorch prod function produces equivalent results as the numpy prod function.
=> Add prod function to pytorch backend

geomstats/__init__.py, geomstats/tests.py, tests/test_backend_numpy.py, tests/test_backend_tensorflow.py, tests/test_connection.py, tests/test_discretized_curves_space.py, tests/test_euclidean_space.py, tests/test_examples.py, tests/test_general_linear_group.py, tests/test_grassmannian.py, tests/test_hyperbolic_space.py, tests/test_hypersphere.py, tests/test_invariant_metric.py, tests/test_landmarks_space.py, tests/test_lie_group.py, tests/test_manifold.py, tests/test_matrices_space.py, tests/test_minkowski_space.py, tests/test_poincare_polydisk.py, tests/test_quantization.py, tests/test_spd_matrices_space.py, tests/test_special_euclidean_group.py, tests/test_special_orthogonal_group.py, tests/test_stiefel.py, tests/test_visualization.py
This change makes sure that we don't switch the backend unnecessarily when testing a specific backend. This effectively suppresses curious messages like "Using numpy backend" when running tests for tensorflow. Similiarly, running the test suite on the numpy backend now no longer produces tensorflow deprecation warnings as we don't import tensorflow in the first place.
=> Restrict backend tests

geomstats/geometry/matrices_space.py, tests/test_matrices_space.py
add vectorised matrix transpose. 
N.B:  this is only a first push to expose a vectorized transpose map with **correct shape signature**. 
Many other methods resort to matrix transposition usually via an inline implementation and resorting to `gs.to_ndim` for vectorisation. They might have inconsistent vectorization behaviour, next step is to check this, point to `Mat.transpose` while checking `spd_matrices` stays ok. 
For instance: 
+ `is_symmetric`
+ `make_symmetric`
+ `inverse` on orthogonal matrices!
+ ... 
Look at the implementation to see how array shapes should be checked, and pass the correct `axes` argument to `gs.transpose`. 
```
tr = MatricesSpace.transpose
a = gs.array([
[1, 0],
[0, 1]])
b = tr(a) 
tr([a, b]) 
>>> [b, a]
```
=> matrix transpose

geomstats/backend/numpy.py, geomstats/backend/numpy_linalg.py, geomstats/backend/numpy_random.py, geomstats/backend/pytorch.py
The majority of functions defined in the numpy backend were straightforward forward-calls to the bare numpy functions. This change simply forward-exports these functions rather than adding wrapper functions which simply pass along their `*args, **kwargs` arguments.
=> Forward-export numpy functions

.travis.yml, geomstats/backend/pytorch/__init__.py
This PR also explicitly specifies to nose2 to do test discovery only in the tests directory, which likely would have fixed the issues encountered in the CI tests of https://github.com/geomstats/geomstats/pull/264.
=> Simplify pytorch version check in backend

CONTRIBUTING.md, README.md
Fixes #345 
I removed the links from CONTRIBUTION.MD, because you can not link to 3rd level headers in markdown.
=> Fix Link to Contribution.Md

.travis.yml, examples/loss_and_gradient_se3.py, examples/loss_and_gradient_so3.py, geomstats/backend/pytorch/__init__.py, geomstats/backend/pytorch/linalg.py, geomstats/geometry/invariant_metric.py, geomstats/geometry/special_orthogonal_group.py, requirements.txt, tests/test_examples.py
Since tensorflow 2.0 does not support python 3.8, we avoid testing in tf 2.0 in the 3.8 version.
=> Add python 3.8 in travis

geomstats/geometry/product_manifold.py, tests/test_product_manifold.py
Start to address #377 :
- Add `point_type` to `ProductManifold` constructor to distinguish between the two possible representations.
- Start unit tests that were non-existing for `product_manifold`.
=> Add point_type to ProductManifold + Start unit tests on ProductManifold

.travis.yml
This should fix the problem @ythanwerdas mentioned in https://github.com/geomstats/geomstats/pull/359#issuecomment-576285413, by running the flake8 check only on the files that differ in the submitted PR from master.
=> Run flake8 only on files differing from master

.travis.yml
Recent pip upgrade breaks geomstats' travis. This is a hot fix, thanks to @nkoep .
https://github.com/pypa/pip/issues/7620
=> Hot fix following pip upgrade

.travis.yml, README.md, geomstats/geometry/general_linear.py, geomstats/geometry/grassmannian.py, geomstats/geometry/matrices.py, geomstats/geometry/spd_matrices.py, tests/test_matrices.py, tests/test_spd_matrices.py
This merge updates the `Matrices` class to provide with convenience methods discussed: equal, transpose, is_symmetric etc. 
I spent some time recabling the tests as well, while doing so I noticed many of them had really inconsistent shape signatures and this fixes them. 
This merge is an important step towards unifying vectorization behaviour across matrices-related files. Inline implementations are bug-prone and sometimes really hard to find.
I should also mention the convoluted way SPD(n) resorted to symmetry checks: 
```python
SPD.__init__:
SPDn.embedding_manifold = GLn
SPD.belongs:
#gs.to_ndarray cooking
return self.embedding_manifold.is_symmetric(...)
GL.is_symmetric: 
```
=> Merge matrices.py

examples/geomstats_in_pymanopt.py
This implements a simple toy example from pymanopt on top of geomstats. I've intentionally not included the example in `tests/test_examples.py`, as the example obviously requires pymanopt to run, which we probably shouldn't add as a (hard) dev dependency. The example merely demonstrates how to adapt geomstats to pymanopt's manifold interface.
=> Add simple example using geomstats in pymanopt

tests/test_stiefel.py
The test test_random_uniform_and_belongs is flaky when using tensorflow backend. 
Updating tolerance for flaky test to 1e-4
Fixes:  #405
=> updating tolerance for flaky test

geomstats/geometry/riemannian_metric.py, tests/test_connection.py, tests/test_examples.py, tests/test_special_orthogonal.py
fixes issue #380 
ignores UserWarnings on Numpy and PyTorch backends when running the command `nose2 tests`. Only Sklearn deprecated FutureWarning is left in (can be ignored upon request).
Unfortunately I'm unable to see the results using the Tensorflow backend due to the following issue and my computer being a bit older:
[github.com/tensorflow/tensorflow/issues/17411](https://github.com/tensorflow/tensorflow/issues/17411)
=> Fix nose2 warnings

geomstats/backend/pytorch/__init__.py
Fixes part of issue #380 
This PR replaces the numpy version of less_equal( ) with the equivalent PyTorch version torch.le( )
=> Replace np.less_equal with torch.le

.flake8, examples/tangent_pca_h2.py, examples/tangent_pca_s2.ipynb, examples/tangent_pca_s2.py, examples/tangent_pca_so3.py, geomstats/geometry/riemannian_metric.py, geomstats/learning/pca.py
Tangent PCA algorithm was present twice: 
- as a method of the class RiemannianMetric
- as an algorithm in the folder geomstats/learning
This PR removes the first one and cleans docstrings.
=> Remove redundant code of tangent pca in the RiemannianMetric class

geomstats/backend/numpy/__init__.py
This removes any functions already exposed in `geomstats.backends.numpy.random` from the numpy backend's top-level module. This seems to be an oversight due to a rebase after the hackathon, where the functions should have been removed already.
=> Remove superfluous numpy backend functions

.flake8, .pre-commit-config.yaml, .travis.yml, ci-requirements.txt, dev-requirements.txt, docs/contributing.rst, geomstats/tests.py
Apart from general clean-up of the travis config, this PR adds a [pre-commit](https://pre-commit.com/) config to the source tree. This is an opt-in feature, which adds a git pre-commit hook if enabled that currently
1. checks for byte-order markers
2. checks for filename case conflicts (macos and windows file systems are case-insensitive by default)
3. checks for left-over merge conflict markers
4. runs flake8
5. checks for mixed line-endings
6. prevents direct commits to master
7. cleans up trailing whitespace
If the `pre-commit` package is installed, the hook can be enabled by running `pre-commit install` in the repository root. The hook only checks files staged for commit. Most importantly, this means that it only checks for flake8 violations in modified and staged files rather than …
=> Add pre-commit config

tests/test_examples.py
Continuing improvements to issue #380 
This PR ignores the RuntimeWarnings that are generated when more than 20 figures have been opened during the numpy nose2 tests
=> ignore RuntimeWarning: More than 20 figures open

.travis.yml, README.md, setup.py
This PR sets up travis to automatically deploy a new geomstats build to pypi when tags get pushed to the geomstats repository.
=> Automatically deploy tags to pypi

examples/empirical_frechet_mean_uncertainty_sn.py, examples/geomstats_in_pymanopt.py, examples/gradient_descent_s2.py, examples/loss_and_gradient_se3.py, examples/loss_and_gradient_so3.py, examples/plot_geodesics_h2.py, examples/plot_geodesics_s2.py, examples/plot_geodesics_se3.py, examples/plot_geodesics_so3.py, examples/plot_grid_h2.py, examples/plot_kmeans_manifolds.py, examples/plot_online_kmeans_s1.py, examples/plot_online_kmeans_s2.py, examples/plot_square_h2_klein_disk.py, examples/plot_square_h2_poincare_disk.py, examples/plot_square_h2_poincare_half_plane.py, examples/tangent_pca_h2.py, examples/tangent_pca_s2.py, examples/tangent_pca_so3.py, geomstats/backend/__init__.py, geomstats/learning/frechet_mean.py, geomstats/learning/kmeans.py, geomstats/learning/online_kmeans.py
Fixes part of issue #429 
This PR addresses the uniform handling of print / logging / warnings. Work is in progress as some warning statements still need to be changed.
**Note:**
Because nose2 introduces its own logging configuration, the logging **format** will not be displayed as implemented in `geomstats/backend/__init__py` during testing. I tried to find a way around this problem but everything I tried just introduced more issues. 
Nevertheless, the correct logging format will be displayed when running examples or other task that do not involve nose2 testing.
=> Uniformize logging

.codecov.yml, .travis.yml
This commit adds a .codecov.yml that allows to set options relative to
code coverage with codecov. Specifically, the option to ignore data/ and
imgs/ folder from the examples/ is added.
=> Add options for code coverage

geomstats/geometry/grassmannian.py, tests/test_grassmannian.py
Given two projectors `p1` and `p2`, a rotation from `p1` to `p2` is given by the square root of their composed symmetries (see Batzies et al in docstring) 
```
U = (2. p2 - 1) . (2. p1 - 1)
```
And the log can be computed as `Gr.metric.log(p2, p1) = (1/2) logm(U)`
Tests pass on numpy but we still lack a matrix logarithm on pytorch, would it be ok to use `scipy.linalg.logm` as a workaround @ninamiolane ? (on a separate backend PR!)
=> add grassmannian logarithm

requirements.txt
This fixes a potential bug.
With a former version of joblib, nose2 tests would fail on product_manifold.py at:
`pool = joblib.Parallel(n_jobs=self.n_jobs, prefer='threads')` with the error:
`TypeError: __init__() got an unexpected keyword argument 'prefer'`
=> Add joblib version in requirements.txt

geomstats/geometry/invariant_metric.py, tests/helper.py, tests/test_invariant_metric.py
- test when base_point=None
- test when inner_product_mat_at_identity=None: there was a duplicate check in this case, and a reference to self.group before assignment
=> Improve unit tests of the invariant metric

geomstats/__init__.py, geomstats/_logging.py, geomstats/backend/__init__.py, geomstats/learning/frechet_mean.py
This moves the `logging` module configuration to its own module in the toplevel `geomstats` package.
=> Don't configure logging module in backend

geomstats/tests.py, tests/test_backends.py, tests/test_connection.py, tests/test_hyperbolic.py, tests/test_minkowski.py, tests/test_special_orthogonal.py
With the move to TF2, we no longer need to run TF tests inside sessions since TF2 uses eager execution by default.
=> Remove tensorflow sessions

geomstats/backend/pytorch/__init__.py, geomstats/backend/tensorflow/__init__.py, geomstats/geometry/hyperbolic.py, geomstats/geometry/hypersphere.py, geomstats/geometry/special_orthogonal.py, tests/test_backends.py, tests/test_product_manifold.py, tests/test_special_orthogonal.py, tests/test_vectorization.py
This PR adapts the einsum function is tf and pytorch backends:
- Pytorch was using numpy's einsum function the cover, now pytorch's einsum is used. This has led to a few modifications in the code and the unit tests.
- Tf's and pytorch's einsum are less flexible on ellipsis than numpy. For example, einsum('...i,...i->...', a, b) with a of shape [1, d] and b of shape [n, d] does not work with tf and pytorch. This PR adapts the einsum's code in both tf and pytorch backends to address this.
The unit tests are added correspondingly.
=> Adapt einsum functions in tf and pytorch backends

geomstats/geometry/invariant_metric.py
Because of differing shapes, this condition was never satisfied.
=> Replace 'is' evaluation by isclose

tests/test_hyperbolic.py
The method `projection_to_tangent_space` was not tested by a separate test. This PR corrects this.
=> Add unit test for projection_to_tangent_space in hyperbolic.py

.codecov.yml, geomstats/geometry/hypersphere.py
This PR:
- Removes the codecov flags that are not triggered
- Update the target options for `default` and `patch` code coverage: set their respective coverage targets to 90%.
- Address a FIXME in the hypersphere, in order to test these coverage updates.
=> Update codecov options to set explicit coverage targets during PR

.codecov.yml
This PR adds flags to have automatic checks about coverage during Travis unit tests.
=> Add flag -unit to codecov.yml to trigger coverage with github

examples/plot_bch_so3.py, geomstats/backend/numpy/__init__.py, geomstats/backend/pytorch/__init__.py, geomstats/backend/tensorflow/__init__.py, tests/test_backends.py, tests/test_special_euclidean.py
Debugged assignment in non-trivial cases (e.g., vectorizing along axis!=0), and allowed assigning even when the former element was non-zero. Added unit tests for both cases.
Note that assignment_by_sum seems a bit redundant, especially in the case of numpy and pytorch.
Added corresponding docstrings.
I also thought of a way of documenting evolving shapes along a provided axis :
new_x: array_like, shape=[dimension[:axis], n_samples, dimension[axis:]]
What do you think @ninamiolane @nguigs @nkoep  ?
(Also corrected a typo in plot_bch_so3)
=> Assignment debug, documentation, and unit test

docs/contributing.rst
I tried to modify the contrib .rst file to include a point on arrays of variable shape. Don't know if it works on GitHub.
I also took the opportunity to reduce the lines to 79 characters (except links)
=> Contributing guideline with array of variable shape

geomstats/backend/pytorch/__init__.py, geomstats/geometry/special_euclidean.py, tests/test_special_euclidean.py
Only failing tests are Pytorch and Tensorflow giving wrong output in some log and exp tests (especially Pytorch), for which the decorator `@...np_only` was kept.
I removed the other decorators around the tests which all backends succeed, except `dist_is_symmetric` which takes ages. Better to slow down even the tests even more, or coverage completeness ? (Tensorflow is already tested with less testcases)
`logical_and` and `array` were modified in Pytorch backend to have behavior more similar to numpy's: the former can be applied to a bool and a Tensor for instance; the latter gives an nd_array with the same dimension.
=> Inverse and random_uniform work in matrix form with all backends

examples/empirical_frechet_mean_uncertainty_sn.py, geomstats/geometry/invariant_metric.py, geomstats/geometry/special_euclidean.py, geomstats/geometry/special_orthogonal.py, tests/test_examples.py, tests/test_invariant_metric.py, tests/test_special_orthogonal.py
- re-implement inner_product when `point_type='matrix'`
- fix `regularize_tangent_vec` in special_orthogonal
- add parameter to example on empirical_frechet_mean to run it only once when unit-testing
Generally, I think there is a confusion between the methods of invariant-metric and the exponential on groups. Using the group exp at identity to implement the left-invariant metric Riemannian exp is only valid for bi-invariant metrics, with identity inner-product matrix at identity.
=> Add unit tests for invariant metrics when `point_type='matrix'`

geomstats/geometry/hypersphere.py, geomstats/learning/frechet_mean.py, tests/test_frechet_mean.py
- override `squared_dist` method for hypersphere using `dist(point_b, point_a)` instead of using `squared_norm(log(point_b, point_a))` which is slower.
- fix error from previous commit, to return point when only one sample is given to the `_adaptive_gradient_distance`.
=> Square distance on hypersphere

examples/empirical_frechet_mean_uncertainty_sn.py, tests/test_examples.py
The full example has been moved to the application repo, so the example empirical_frechet_mean_uncertainty_sn can be shortened.
=> remove multi_plot in empirical_frechet_mean_uncertainty_sn example

geomstats/vectorization.py, tests/test_vectorization.py
This PR prepares the vectorization refactorization, as mentioned in issue #338.
It builds on the vectorization decorator, to be put on top of some (as less as possible) geomstats functions, in order to:
- convert their arguments into their fully-vectorized forms,
- call the function,
- reshape the output if needed.
This PR enhances the decorator by allowing it to take into account kwargs arguments.
=> Adapt vectorization decorator to kwargs arguments

geomstats/geometry/general_linear.py, tests/test_general_linear.py
This PR removes a few decorators where possible to improve testing with the pytorch backend.
Only the log, which is not yet implemented with pytorch if I understood remains not tested.
=> Test GenralLinear with pytorch

geomstats/geometry/special_euclidean.py, tests/test_special_euclidean.py
Add the method to regularize tangent vectors represented by matrices for the special euclidean group, without assignement so that it works will all backends
=> Regularize tangent vec special euclidean

geomstats/_backend/numpy/__init__.py, geomstats/_backend/pytorch/__init__.py, geomstats/_backend/tensorflow/__init__.py, tests/test_special_orthogonal.py
Documentation for `get_slice`, `array_from_sparse` and `get_mask_i_float` backend functions, which are exported but not "straightforward" to understand.
=> Docstring on some backend functions

geomstats/_backend/pytorch/__init__.py, tests/test_special_orthogonal.py
Currently, pytorch's cos and sin only accept tensors as inputs. However, numpy accepts both arrays and values as inputs.
This PR:
- adapts the behavior of cos/sin from pytorch's backend to match numpy's behavior,
- adapts special_orthogonal's unit tests to use the new syntax.
@pchauchat @nguigs
=> Adapt cos/sin from pytorch's backend to match numpy's behavior

geomstats/vectorization.py, tests/test_vectorization.py
This PR continues to address issue #338, by adding the 'point_type' logic to the decorator, which can now reads the `point_type` parameter, which can be 'vector' or 'matrix' and adapt the types of the input args or kwargs.
Additionally, this PR:
- allows the decorator to know if the expected type of the output is meant to be a scalar - this allows to distinguish between scalars and 1D vectors, that appear in SO(2) for example,
- clean the code of the vectorization module to improve readability.
=> Add `point_type` logic to vectorization's decorator

geomstats/_backend/pytorch/__init__.py, geomstats/_backend/tensorflow/__init__.py, geomstats/geometry/hyperboloid.py, geomstats/geometry/riemannian_metric.py, tests/test_backends.py, tests/test_poincare_polydisk.py
The new einsum in tf and pytorch can:
- Add a singleton dimension on axis 0,
- Remove it to send the result if both input tensors didn't have that dimension to start with.
This allows to do:
```
a = gs.array([1])
b = gs.array([[1, 2, 3]])
gs.einsum('...,...i->...i', a, b)
```
gives [[1, 2, 3]]
but:
```
a = gs.array(1)
b = gs.array([1, 2, 3])
gs.einsum('...,...i->...i', a, b)
```
gives [1, 2, 3],
which follows numpy's behavior.
=> Generalize tf's and pytorch's einsum to match numpy behavior on squeezed dims

geomstats/_backend/pytorch/__init__.py, tests/test_backends.py
This commit aims at having `array` functions with behaviors as similar as possible between the various backends, and especially Pytorch.
A few points are open questions, which need to be discussed @ninamiolane @nkoep @nguigs 
- The main problem was that Pytorch's `array` did not allow things like `gs.array([gs.ones(2), [0,0]])`, which numpy and tensorflow would seamlessly deal with. This is now dealt with recursively (to handle, e.g., `array([[[gs.ones(2)], [gs.ones(2)]]])`)
- Pytorch is restrictive when  `dtypes` are considered : it won't stack a `float32` tensor with a `float64` one, for instance. I had to add casting "on the fly", and an arbitrary type order to get a unified dtype at the end. This is (slightly) unelegant, and more importantly I don't know how much that could impact the …
=> Make Pytorch's array closer to Numpy's

geomstats/geometry/invariant_metric.py, geomstats/geometry/lie_group.py, geomstats/geometry/special_euclidean.py, geomstats/geometry/special_orthogonal.py, tests/test_invariant_metric.py, tests/test_special_euclidean.py, tests/test_special_orthogonal.py
This PR continues to address issue #338. The strategy behind the refactorization/vectorization PRs is explained in a post in the associated issue #338.
This PR gets rid of the vectorization decorators in lie_group and invariant_metric.
=> Vectorization of LieGroup and InvariantMetric

geomstats/_backend/__init__.py, geomstats/_backend/numpy/__init__.py, geomstats/_backend/pytorch/__init__.py, geomstats/_backend/tensorflow/__init__.py, tests/test_backends.py
This PR adds various `dtype` options to the `array` unit test. It also adds `uint8` to the backend functions accessible outside. This is for the test only at the moment.
=> Include dtype option in array unit test

geomstats/learning/frechet_mean.py, tests/test_frechet_mean.py
Add `transform, fit_transform, inverse_transform` to the Frechet Mean estimator, addressing #570.
The next step will be to refactor these methods in the PCA estimator to use the ones in Frechet Mean, and do the same for exponential barycenter
=> Transformer for Frechet Mean

geomstats/_backend/pytorch/__init__.py, geomstats/_backend/tensorflow/__init__.py, geomstats/geometry/hypersphere.py, tests/test_product_manifold.py
This PR adresses #567 : `split` functions are defined in Pytorch and Tensorflow to match the behavior of Numpy's one. This is done by inferring the right arguments to pass to them from the arguments that are normallygiven when using Numpy.
=> Adapt split of tf and pytorch to Numpy's

geomstats/_backend/numpy/__init__.py, geomstats/_backend/pytorch/__init__.py, geomstats/_backend/tensorflow/__init__.py, geomstats/geometry/general_linear.py, geomstats/geometry/hypersphere.py, tests/test_general_linear.py, tests/test_hypersphere.py
This PR adapts the code for limit cases in sampling for GeneralLinear and Hypersphere (i.e., when determinants or norms are too low respectively) to work with Tensorflow. It uses the `assignment` backend function. This might be quite slow, but since it is a fairly rare case it should be fine.
The piece of code used for replacement is factored in an internal function, to be able to test it without resorting to extensive random seed trials.
=> Adapt random in GeneralLinear and Hypersphere to work with Tensorflow

requirements.txt
Testing `tests/test_beta_distributions.py` was failing on my local with a previous version of autograd.
=> Force version of autograd 1.3 (latest) in requirements

docs/index.rst, tests/test_invariant_metric.py
Last PR made the table of contents disappear from the doc website. This PR fixes it.
=> Bring back the table of contents in docs

geomstats/geometry/general_linear.py, tests/test_general_linear.py
This addresses issue #399 about the use of `gs.where`.
=> Address issue #399 by removing gs.where in GL.belongs

examples/geomstats_in_pymanopt.py
Following the PRs on vectorization in geomstats, there is no need to squeeze the outputs of the Hypersphere methods in the pymanopt example.
=> Remove squeeze decorator in pymanopt example

geomstats/_backend/numpy/__init__.py, geomstats/_backend/pytorch/__init__.py, geomstats/_backend/tensorflow/__init__.py, geomstats/geometry/general_linear.py, geomstats/geometry/hypersphere.py, tests/test_general_linear.py, tests/test_hypersphere.py
This PR allows gs.assignment to work with booleans (and indices given as tensors) in tf.
It is a follow-up on #583 and #593 
gs.assignment was heavily refactored to take into account arrays and booleans. For numpy and pytorch, I tried to take as much advantage as possible of their slicing opportunities, to keep the cost low (although I don't guarantee anything).
I defined more general check functions, to see if an object is some kind of boolean (mostly a native one or an array of bools), and if it is iterable (list, tuple, array of dim > 0). Maybe it will be useful for other functions too.
Some lines are left untested, I will add the corresponding tests later.
=> Move commits of old PR #593 on assignment to a new one post-rebase

geomstats/geometry/spd_matrices.py, geomstats/learning/frechet_mean.py, geomstats/learning/preprocessing.py, tests/test_frechet_mean.py, tests/test_preprocessing.py
This addresses comments made in the #577 to address #570 in a specific module rather than in FrechetMean, thus leaving the possibility to use any base point and not only the FrechetMean as base_point to lift data points to a tangent space.
=> Move FrechetMean transform to a preprocessing module

geomstats/_backend/numpy/__init__.py, geomstats/_backend/pytorch/__init__.py, geomstats/_backend/tensorflow/__init__.py, tests/test_backends.py
This PR adds a new use case to tf's `assignment` and the sum version (which was already accessible for numpy and pytorch): vectorization with non-constant values. This simply means that , if `ndim(x) == 3`:
`x = gs.assignment(x, [1, 2, 3], (0, 0), axis=2) <=> x[0, 0, :] = [1, 2, 3]`.
The docstring of assignment is also updated to try and cover its use cases.
=> Update of tf's assignment

tests/test_backends.py
Some values of theta and phi make this test fails (? @pchauchat). 
This PR removes the randomness in sampling theta and phi to fix master.
[Edit]: Removing the randomness is not enough. This test keeps failing 15% of the time (?). But inverting the computations `gs` and `_np` fixes it.
=> Hot fix in assignment_by_sum tests: remove randomness

docs/contributing.rst, geomstats/geometry/beta_distributions.py, geomstats/geometry/connection.py, geomstats/geometry/discretized_curves.py, geomstats/geometry/embedded_manifold.py, geomstats/geometry/euclidean.py, geomstats/geometry/general_linear.py, geomstats/geometry/grassmannian.py, geomstats/geometry/hyperbolic.py, geomstats/geometry/hyperboloid.py, geomstats/geometry/hypersphere.py, geomstats/geometry/invariant_metric.py, geomstats/geometry/lie_algebra.py, geomstats/geometry/lie_group.py, geomstats/geometry/manifold.py, geomstats/geometry/matrices.py, geomstats/geometry/minkowski.py, geomstats/geometry/poincare_ball.py, geomstats/geometry/poincare_polydisk.py, geomstats/geometry/product_manifold.py, geomstats/geometry/product_riemannian_metric.py, geomstats/geometry/riemannian_metric.py, geomstats/geometry/skew_symmetric_matrices.py, geomstats/geometry/spd_matrices.py, geomstats/geometry/special_euclidean.py, geomstats/geometry/special_orthogonal.py, geomstats/geometry/stiefel.py, geomstats/geometry/symmetric_matrices.py
This PR suggests changing the way we indicate shape of array-like inputs in docstrings.
Instead of:
```
tangent_vec : array-like, shape=[n_samples, dim] or shape=[dim,]
```
we use:
```
tangent_vec : array-like, shape=[..., dim]
```
In addition, this allows avoiding ambiguities in the BetaDistribution manifold, where `n_points` and `n_samples` notations were conflicting.
However, using `[...,` instead of `[n_samples,` could be slightly less explicit for users looking at the documentation. What do you think? @nguigs @stefanheyder @cshewmake2
=> Change docstring convention for shape=

geomstats/_backend/tensorflow/__init__.py
This PR defines tensorflow's `assignment` and `assignment_by_sum` as two variants of the same internal `_assignment` function, avoiding significant redundancy.
=> Refactor assignment and assignment_by_sum

geomstats/geometry/hypersphere.py
There were discussions about whether:
- a Manifold should have an attribute `metric`,
- a Connection/RiemannianMetric should have an attribute `space`,
since having both results in `maximum depth exceeded` error, since both objects would call themselves.
This PR suggests to address this with the following logic (only on Hypersphere for now):
- add a private class `_Hypersphere`, with *no* `self.metric`,
- add a `self._space` private attribute in the class `HypersphereMetric`. 
- For example, this private attribute will allow to:
-  use `geomstats.errors.check_belongs(point, self._space)` in order to consistently check that input parameters of `exp`, `log`, etc., do belong to the manifold on which the metric is used, 
- use space's methods that convert coordinate types,
- etc.
- This …
=> Add logic to allow Manifolds having the attribute metric

geomstats/errors.py, geomstats/geometry/beta_distributions.py, geomstats/geometry/connection.py, geomstats/geometry/grassmannian.py, geomstats/geometry/invariant_metric.py, geomstats/geometry/lie_algebra.py, geomstats/geometry/manifold.py, geomstats/geometry/matrices.py, geomstats/geometry/product_manifold.py, geomstats/geometry/special_euclidean.py, geomstats/geometry/special_orthogonal.py, geomstats/geometry/stiefel.py, geomstats/learning/frechet_mean.py, tests/test_backends.py, tests/test_errors.py
Clean geomstats.errors module:
- geomstats.error -> geomstats.errors to be consistent with geomstats.tests (plural)
- clean check_belongs method, no need for manifold's name as parameter
- add unit tests
=> Clean geomstats.errors

geomstats/geometry/hypersphere.py, tests/test_hypersphere.py
This addresses #701 so that parallel transport can be applied to:
1. n base_points, n tan_a, n tan_b
2. 1 bp, n tan_a, n tan_b
3. 1 bp, 1 tan_a, n tan_b
4. 1 bp, n tan_a, 1 tan_b
5. 1 bp, 1 tan_a, 1 tan_b
The five cases are tested and work with numpy and tensorflow. Only cases 1 and 5 work with pytorch: it seems einsum is not entirely consistent with that of numpy?
=> Vectorize parallel transport on the hypersphere

geomstats/_backend/__init__.py, geomstats/_backend/numpy/__init__.py, geomstats/_backend/pytorch/__init__.py, geomstats/_backend/tensorflow/__init__.py, tests/test_backends.py
This PR starts to address issue #769 .
This PR adds the function `convert_to_wider_dtype` in the backends. This function casts arrays from a list of arrays into arrays of dtype the "wider" dtype. For example, a list of int32 and float32 arrays is cast to float32 and float32 arrays.
This allows einsum to work with arrays of different dtypes.
Note: The code of `convert_to_wider_dtype` is essentially the same for all backends. Could we factorize it somewhere? I tried to put it in a file `_backend/casting.py` but this leads to failure of backend's imports. @nkoep
=> Allow einsum to work with arrays of different dtypes

geomstats/learning/pca.py, tests/test_pca.py
In tPCA. point_type is not a degree of liberty but it has to match metric.default_point_type. This ill avoid some issues
=> Point_type in PCA

geomstats/_backend/pytorch/__init__.py, geomstats/geometry/discrete_curves.py, tests/test_discrete_curves.py
- Implement a vectorize method for pytorch. It may not behave exactly like the numpy one (which is flexible thanks to the signature argument)
- Remove decorators so that all methods are tested in the three backends
Remaining problems: The discrete curve class is thought for points on manifolds which have vector representations, it won't work for curves of matrices...
=> Adapt discrete curve to pytorch and tf

ci-requirements.txt, docs/.nblink, docs/conf.py, docs/index.rst
Following issue #453, this PR starts integrating the notebooks directly to the documentation website.
=> Have notebooks directly integrated into the documentation website

geomstats/datasets/utils.py, notebooks/tangent_pca_s2.ipynb, tests/test_notebooks.py
This PR addresses #803 
On Windows, it seems the file encoding needed to be explicitly given in order for `json` to be able to load `cities`.
`NamedTemporaryFile` already opens the file in question, so having `check_call` inside the `with` tries to open it twice, which appears to be forbidden on Windows.
For some reason, the use of `chdir` was also needed for the `tangent_pca_s2` notebook (I simply pasted the same first cell used in the other two notebooks).
=> Changes to make notebooks and dataset loading work on Windows.

geomstats/geometry/special_euclidean.py, geomstats/geometry/special_orthogonal.py, tests/test_special_euclidean2.py, tests/test_special_orthogonal2.py, tests/test_special_orthogonal3.py
This PR adds the vector parametrization of SO(2) and SE(2), following the way the 3-dimensional case is treated.
For SE(2), the focus is on the group structure for now.
The tests for SO(2) follow those of SO(3), this might be a bit of an overkill, but at least it is more or less exhaustive.
=> Vector parametrisation for SO(2) and SE(2)

geomstats/_backend/__init__.py, geomstats/_backend/numpy/__init__.py, geomstats/_backend/numpy/autograd.py, geomstats/_backend/pytorch/__init__.py, geomstats/_backend/pytorch/autograd.py, geomstats/_backend/tensorflow/__init__.py, geomstats/_backend/tensorflow/autograd.py, geomstats/geometry/connection.py, tests/test_backends.py, tests/test_connection.py
This PR adds an autograd module to the backend so that automatic differentiation can be used with all backends. This is a proof of concept that it works for the computation of the log on the sphere using Christoffel symbols (already existed before but with numpy only).
For the gradient descent, the scipy solver is used, so we go back and forth between torch/tensorflow tensors and numpy arrays, but it remains simpler than using torch/tensorflow optimizers.
=> Factorize gradient computation in the backends

geomstats/visualization.py
Seaborn changes the default matplotlib plotting style, by setting a grey background, which is not very nice IMO (you can see the difference on the notebooks). It will be better for the paper with plain white background.
=> remove seaborn style

geomstats/geometry/stiefel.py
Theorem 3.1 in the reference below provides a method for determining the Riemannian logarithm on the Stiefel manifold. It involves solving a matrix equation via an iterative approach, and provides a break condition in the form of a certain matrix norm being sufficiently small. This (modest) PR implements that break condition and closes Issue [#711](https://github.com/geomstats/geomstats/issues/711).
- [R. Zimmermann. A Matrix-Algebraic Algorithm for the Riemannian Logarithm on the
Stiefel Manifold under the Canonical Metric.](https://arxiv.org/pdf/1604.05054.pdf)
=> Add break condition to calculation of log on Stiefel manifold

docs/first-steps.rst
The code snippets given in the first steps of the online documentation were not updated to follow the latest API.
This PR corrects it + fix another typo.
=> Fix typos in documentation

geomstats/learning/expectation_maximization.py, tests/test_expectation_maximization.py
The current implementation for EM on the Poincare ball in the RiemannianEM class only allows for random initialization of the cluster centroids. This PR adds the option for performing Riemannian  KMeans instead for initialization.
This should close issue #791
=> Adding kmeans initialization for EM algorithm on Poincare Ball

.gitignore, geomstats/_backend/tensorflow/__init__.py, geomstats/_backend/tensorflow/linalg.py, geomstats/geometry/euclidean.py, geomstats/geometry/grassmannian.py, geomstats/geometry/matrices.py, tests/test_backends.py, tests/test_grassmannian.py
This PR adds tools for the Grassmann Manifold, following up on #572:
- remove hard coded dimension
- add belongs, is_tangent, to_tangent methods
- change exp and log to take and return tangent vectors instead of skew-sym matrices
- add random_uniform method
- change the metric to inherit MatricesMetric so that inner products and norms can be computed with the Frobenius dot prod.
@opeltre
=> Kristianeschenburg grassmann belongs

geomstats/_backend/pytorch/linalg.py, geomstats/_backend/tensorflow/linalg.py, geomstats/geometry/matrices.py, geomstats/learning/pca.py, tests/test_backends.py, tests/test_matrices.py
Address #861 
Use native SVD of each back-end
remove check array from sklearn because it returns a numpy array, whichever backend
Works with pytorch but not tensorflow because of another sklearn function.
=> Fix tangent PCA with pytorch

examples/plot_geodesics_se2.py, geomstats/_backend/__init__.py, geomstats/_backend/numpy/__init__.py, geomstats/_backend/pytorch/__init__.py, geomstats/_backend/tensorflow/__init__.py, geomstats/geometry/connection.py, geomstats/geometry/general_linear.py, geomstats/geometry/hypersphere.py, geomstats/geometry/invariant_metric.py, geomstats/geometry/lie_algebra.py, geomstats/geometry/lie_group.py, geomstats/geometry/manifold.py, geomstats/geometry/matrices.py, geomstats/geometry/skew_symmetric_matrices.py, geomstats/geometry/special_euclidean.py, geomstats/geometry/special_orthogonal.py, geomstats/geometry/symmetric_matrices.py, geomstats/visualization.py, tests/test_examples.py, tests/test_invariant_metric.py, tests/test_lie_algebra.py, tests/test_skew_symmetric_matrices.py, tests/test_special_euclidean.py, tests/test_symmetric_matrices.py, tests/test_visualization.py
This PR continues #878, #884 and #886. It
- adds a module for visualisation of SE(2) in the plane
- adds a class for the left-invariant metric on matrix SE(n). It is a product metric with closed-form formulas. It is checked that they coincide with the vector implementations.
- adds an example where the geodesics with the different structures are plotted.
- Harmonize 2 and 3 dimensional bases of the space of skew symmetric matrices with conventions
=> Visualisation on SE(2) and Canonical left-invariant metric

geomstats/_backend/numpy/linalg.py, geomstats/_backend/pytorch/linalg.py, geomstats/_backend/tensorflow/linalg.py, tests/test_backends.py, tests/test_pre_shape.py
In the particular case where A=B is a Symmetric Non-Negative Definite matrix, the solution to AX + XB = Q can be computed with an eigenvalue decomposition of A. It turns out that this is much faster than vectorizing the scipy solver.
This allows to extend all the methods in the Kendall shape spaces to run with tensorflow, and could be used in #889.
=> Add sylvester solve for tf in backend

geomstats/_backend/__init__.py, geomstats/_backend/numpy/linalg.py, geomstats/_backend/pytorch/linalg.py, geomstats/_backend/tensorflow/linalg.py, geomstats/geometry/connection.py, geomstats/geometry/embedded_manifold.py, geomstats/geometry/fiber_bundle.py, geomstats/geometry/general_linear.py, geomstats/geometry/lie_algebra.py, geomstats/geometry/pre_shape.py, geomstats/geometry/quotient_manifold.py, geomstats/geometry/quotient_metric.py, geomstats/geometry/skew_symmetric_matrices.py, geomstats/geometry/spd_matrices.py, geomstats/geometry/symmetric_matrices.py, opt-requirements.txt, tests/test_backends.py, tests/test_invariant_metric.py, tests/test_quotient_manifold.py, tests/test_quotient_metric.py, tests/test_skew_symmetric_matrices.py, tests/test_spd_matrices.py, tests/test_special_orthogonal3.py, tests/test_symmetric_matrices.py
This PR defines an abstract class for fiber bundles and quotient metrics. There are different scenarios depending on the available methods (whether the submersion is explicitly defined or not). This is tested in two different cases: 
- kendall shape space: the quotient space is abstract and computations are carried out in a section of the total space
- Bures Wasserstein metric on spd: everything is explicit
@ythanwerdas
=> add abstract class for quotient spaces

geomstats/learning/frechet_mean.py, tests/test_expectation_maximization.py
The variance function uses `metric.squared_dist`, which can be replaced by `metric.norm(logs)`, where logs have already been computed. This avoids computing the logs twice.
Also fixed `test_weighted_frechet_mean` which was wrong as the `weights` arguments was not used...
=> remove redundant call to variance function

.travis.yml, ci-requirements.txt
Travis.yml is not installing requirements from  docs/requirements.doc.txt. This will fix the 'build-failing' because the sphinx-gallery is added as dependency in  docs/requirements.doc.txt
=> install from docs/requirements.doc.txt as well

geomstats/learning/frechet_mean.py
It was returning the intial value instead of point[0] with only one point.
=> Corrected a bug in _adaptive_gradient_descent

geomstats/geometry/_my_manifold.py, geomstats/geometry/euclidean.py, geomstats/geometry/grassmannian.py, geomstats/geometry/hyperboloid.py, geomstats/geometry/hypersphere.py, geomstats/geometry/invariant_metric.py, geomstats/geometry/lie_group.py, geomstats/geometry/manifold.py, geomstats/geometry/pre_shape.py, geomstats/geometry/quotient_metric.py, geomstats/geometry/riemannian_metric.py, geomstats/geometry/special_orthogonal.py, geomstats/geometry/stiefel.py, tests/tests_geomstats/test_euclidean.py, tests/tests_geomstats/test_hypersphere.py, tests/tests_geomstats/test_invariant_metric.py, tests/tests_geomstats/test_lie_algebra.py
- Fix dimension in KendallShapeMetric
- In most cases `base_point` is not optional in `is_tangent` and `to_tangent`, and a missing argument error is much more informative than one raised by manipulating None
=> Dimension of Kendall shape metric

geomstats/geometry/connection.py, tests/tests_geomstats/test_connection.py, tests/tests_geomstats/test_hypersphere.py
The previous method `geodesic` did not work when only one base_point was passed.
I am wondering whether the shape of the output should be `(n_initial_conditions, n_times, {dim, [n, n]})` or  `(n_times, n_initial_conditions, {dim, [n, n]})`? So far the second option is returned
=> Fix vectorization of geodesic

requirements.txt
Add newer versions for requirements of matplotlib: plotting geodesics on the sphere errors if users have an older version of matplotlib.
=> Add versions for matplotlib

.github/workflows/build.yml, .github/workflows/docs.yml, doc-requirements.txt, opt-requirements.txt, requirements.txt, setup.py
This PR:
- puts `jupyter` requirement outside of the main `requirements.txt`, see issue #1093 
- puts >= signs in requirements.txt
- puts >= signs in opt-requirements.txt
- bump tensorflow version >= 2.2 to have it work with python 3.8
- removes python version 3.5 in the setup.py since we do not test it anymore
=> Update on requirements

geomstats/geometry/pullback_metric.py, geomstats/geometry/riemannian_metric.py, geomstats/geometry/symmetric_matrices.py, tests/tests_geomstats/test_pullback_metric.py
This PR:
- uses joblib in the computation of the metric_matrix (couldn't use Symmetric.to_matrix since it uses scipy internally which does not handle ArrayBox structure from autograd)
- used gs.autograd instead of autograd to make it compatible with torch and tf backends
=> Address code review comments for tests on PullbackMetric structure

README.rst, environment.yml
This PR:
- adds an `environment.yml` file so that users can easily install the requirements for geomstats into a conda environment,
- adds an explanation into the README about it.
=> Add environment.yml for conda

geomstats/algebra_utils.py, tests/tests_geomstats/test_algebra_utils.py
This PR adds a `num_diag` argument to `from_vector_to_diagonal_matrix` to transform a vector into a lower diagonal (`num_diag < 0`) or upper diagonal (`num_diag > 0`), just like [np.diag](https://numpy.org/doc/stable/reference/generated/numpy.diag.html). When `num_diag=0` the function is the same as before.
=> From vector to lower or upper diagonal

examples/geodesic_regression_hypersphere.py, examples/geodesic_regression_se2.py, geomstats/_backend/autograd/autodiff.py, geomstats/_backend/autograd/random.py, geomstats/_backend/numpy/autodiff.py, geomstats/_backend/numpy/random.py, geomstats/_backend/tensorflow/autodiff.py, geomstats/geometry/special_euclidean.py, geomstats/geometry/special_orthogonal.py, geomstats/learning/geodesic_regression.py, tests/tests_geomstats/test_autodiff.py, tests/tests_geomstats/test_examples.py, tests/tests_geomstats/test_geodesic_regression.py
This PR adds unit tests for geodesic regression on SE2, with the backends tf and autograd (torch is missing the implementation of the matrix expm?).
=> Add unit tests for geodesic regression on SE2

.pre-commit-config.yaml
Fix version of python in pre-commit yml so that the precommit can run with any python 3.x version.
=> Fix pre-commit python version

geomstats/geometry/hypersphere.py, tests/tests_geomstats/test_hypersphere.py
Add functions to work with spherical coordinates
=> add extrinsic to spherical and its tangent

geomstats/_backend/pytorch/linalg.py
Replacing `symeig` implementation of `eigh` with `torch.linalg.eigh`. (Ref: https://github.com/geomstats/geomstats/issues/1200)
=> updating symeig with eigh

geomstats/_backend/__init__.py, geomstats/_backend/autograd/linalg.py, geomstats/_backend/numpy/linalg.py, geomstats/_backend/pytorch/linalg.py, geomstats/_backend/tensorflow/linalg.py, geomstats/geometry/graphspace.py, tests/tests_geomstats/test_graphspace.py
metric space for unlabelled graphs
=> Graphspace

.github/workflows/lint.yml
Addresses #1198 
Change Log:
- flake8 is moved before black+isort. (So that failure of black, isort still allows annotations to be made).
- [PENDING]: The current modification only works on `/geomstats`. Need to call on `/tests` as well. 
Open to suggestions! :)
=> Add annotation in code review

geomstats/geometry/base.py, geomstats/geometry/euclidean.py, geomstats/geometry/general_linear.py, geomstats/geometry/heisenberg.py, geomstats/geometry/lie_algebra.py, geomstats/geometry/lower_triangular_matrices.py, geomstats/geometry/matrices.py, geomstats/geometry/skew_symmetric_matrices.py, geomstats/geometry/special_euclidean.py, geomstats/geometry/symmetric_matrices.py, tests/tests_geomstats/test_general_linear.py, tests/tests_geomstats/test_lower_triangular_matrices.py, tests/tests_geomstats/test_matrices.py, tests/tests_geomstats/test_symmetric_matrices.py
The `basis` is turned into a property of all vector spaces. It is only created and stored if needed, to avoid memory overload.
closes #1336
=> add Matrix basis and General linear algebra

geomstats/geometry/base.py, geomstats/geometry/lie_algebra.py, geomstats/geometry/matrices.py
It will initialize `_basis`, instead of `basis` in VectorSpace instantiation.
=> Make VectorSpace basis property more consistent

geomstats/geometry/rank_k_psd_matrices.py
closes #1352 
This PR is to remove LogEclidean and AffineInvariant metrics for PSD matrices manifold defined in `rank_k_psd_matrices`.
=> Correct metrics for PSD matrices

geomstats/geometry/spd_matrices.py
Trying to use Bures-Wasserstein metric, we realize that is possible to avoid inverting a matrix in the parallel transport for Affine Invariant metric by using a rewriting of the squareroot of a product: sqrtm(AB^-1) being rewrite as B^1/2(B^-1/2 A B^-1/2)B^-1/2 instead.
Tests on random points shows a speedup of 1.3x for small dimension (5) up to 3x for larger dimension (100-150) with the different backend. The code results in the same results, up to the machine precision.
=> speedup parallel transport on SPD manifold

tests/data_generation.py, tests/tests_geomstats/test_hypersphere.py
An amplitude parameter is added in the log_exp composition test to stay within the injectivity radius of exp. This will allow to test exp_log_composition
=> add amplitude param to test exp_log_composition

geomstats/geometry/spd_matrices.py, tests/data_generation.py, tests/tests_geomstats/test_spd_matrices.py
- The log is now implemented using only eigen decomposition of symmetric matrices instead of linalg.sqrtm
- An `amplitude` parameter is added in the log_exp composition test to stay within the injectivity radius of exp
=> Fix tests for composition of exp and log of BW metric on SPD

geomstats/geometry/special_euclidean.py
closes #1400 
The projection method of _SpecialOrthogonalVectors is inconsistent though, because it expects a matrix input.
=> add projection for vector representations of SEn

.github/workflows/greetings.yml
This PR fixes #1425 
This PR adds a point of contact i.e Slack and Email for new contributors.
It also modifies the words of the existing greetings.yml
=> Add POC and modified wordings in greetings.yml

geomstats/_backend/pytorch/__init__.py, geomstats/learning/kmeans.py, tests/tests_geomstats/test_riemannian_kmeans.py
Improve KMeans by:
- adding KMeans++ initialization (choose one centroid randomly, then choose the others by maximizing the distance to the centroids already chosen)
- adding prints in the verbose mode, in particular the evolution of the convergence criterion
-  returning the variance of the clustering, to be able to compare different solutions obtained by running kmeans several times and picking best one.
- returning the clustering labels at the `.fit` method so that one does not need to run the `.predict` method if the set of points is the same.
=> Add KMeans++ initialization

tests/data_generation.py, tests/geometry_test_cases.py, tests/helper.py, tests/tests_geomstats/test_euclidean.py, tests/tests_geomstats/test_full_rank_correlation_matrices.py, tests/tests_geomstats/test_general_linear.py, tests/tests_geomstats/test_grassmannian.py, tests/tests_geomstats/test_heisenberg.py, tests/tests_geomstats/test_hyperbolic.py, tests/tests_geomstats/test_hypersphere.py, tests/tests_geomstats/test_invariant_metric.py, tests/tests_geomstats/test_landmarks.py, tests/tests_geomstats/test_matrices.py, tests/tests_geomstats/test_minkowski.py, tests/tests_geomstats/test_poincare_ball.py, tests/tests_geomstats/test_poincare_half_space.py, tests/tests_geomstats/test_positive_lower_triangular_matrices.py, tests/tests_geomstats/test_pre_shape.py, tests/tests_geomstats/test_product_manifold.py, tests/tests_geomstats/test_rank_k_psd_matrices.py, tests/tests_geomstats/test_skew_symmetric_matrices.py, tests/tests_geomstats/test_spd_matrices.py, tests/tests_geomstats/test_special_euclidean.py, tests/tests_geomstats/test_special_orthogonal.py, tests/tests_geomstats/test_stiefel.py
The composition is clearer when expressed as f after g than by g then f because the former respects the order of writing with \circ
=> change then by after

tests/tests_geomstats/test_invariant_metric.py, tests/tests_geomstats/test_quotient_metric.py
`test_dist_point_to_itself_is_zero()` seems to work fine with reduced precision. 
`test_inner_product` in test_quotient metric keeps failing even `1e-1` so I am skipping it for 32-bit backends. 
@ninamiolane
=> run invariant metric dist(a,a)=0

tests/conftest.py
This pull request adds option `skip_all` for tests. If `skip_all=True`, then all the tests are skipped.
**Why is this required?** We are starting to allow some parts of the library to be handled only by a subset of the available backends (e.g. stratified spaces). Therefore, we need a robust way to skip tests for the unsupported backends. Currently, such goal can be reached using a decorator (e.g. `np_only`). The main issue with the decorator is that it acts too late, i.e. data is generated anyway and then pytest is informed the test should be skipped. This, besides adding useless computational time,  is problematic when the data generation uses methods that are not available in all the backends.
With this approach, one can do e.g. `skip_all = not np_backend()`.
Am I missing something …
=> Add skip_all flag to tests

geomstats/learning/kmeans.py, tests/tests_geomstats/test_riemannian_kmeans.py
Sometimes users have domain-specific knowledge on where to expect cluster centers. This MR lets them provide initial cluster centers to nudge k-means towards this guess. If the guess is good, this improves the convergence rate and produces a clustering matching the user's expectation.
**I updated the documentation but failed to compile it due to many unrelated errors.** I also had to run the relevant unit tests manually due to issues with the current version of the `werkzeug` library.
This closes #1500.
=> Allow passing starting centroids to RiemannianKMeans

README.rst
By updating the use of `here` within two consecutive links and removing the `raw` directive, we can make our README render properly in PyPI (e.g. https://test.pypi.org/project/geomstats/2.5.0a0/).
I couldn't find a proper rst directive to reach the same result of `raw` (`image` simply displays the image first).
=> Make readme render in PyPI

docs/api-reference.rst
In the [file](https://github.com/geomstats/geomstats/blob/master/docs/api-reference.rst)
seamlessly was mispelled
=> fixing the typo in docs

tests/tests_geomstats/test_backends.py
Closes #1519 (thanks for spotting this @shubhamtalbar96).
@ninamiolane I've just changed slightly the logic of the test by hardcoding the expected results instead of "collecting" results with `gs` and comparing it with `torch.`
=> Fix torch import in tests_backends

geomstats/geometry/connection.py, tests/data/connection_data.py, tests/tests_geomstats/test_connection.py
We modify exp of connection to make it vectorized: it did not work with the use case (one base_point, n tangent_vectors) before. It failed to raise errors before because the exps returned in the test files were not that of connection but those of the test geometries.
Moreover, we add n_steps as a potential argument in geodesic, as it was =N_STEPS=(10?) before.
=> vectorization of connection.exp, addition of n_steps as argument in geodesic

geomstats/_backend/__init__.py, geomstats/_backend/autograd/__init__.py, geomstats/_backend/numpy/__init__.py, geomstats/_backend/pytorch/__init__.py, geomstats/_backend/tensorflow/__init__.py, tests/tests_geomstats/test_backends.py
Adds `take` to the backend.
Useful for the following case (common in classification tasks):
```
vec = gs.array([0, 1])
indices = [0, 0, 1, 0, 1]
prediction = gs.take(vec, indices)
```
=> Add take to the backend

tests/conftest.py, tests/geometry_test_cases.py, tests/tests_geomstats/test_backends.py, tests/tests_geomstats/test_frechet_mean.py, tests/tests_geomstats/test_full_rank_correlation_matrices.py, tests/tests_geomstats/test_graphspace.py, tests/tests_geomstats/test_heisenberg.py, tests/tests_geomstats/test_hypersphere.py, tests/tests_geomstats/test_pre_shape.py, tests/tests_geomstats/test_product_manifold.py, tests/tests_geomstats/test_spd_matrices.py, tests/tests_geomstats/test_special_euclidean.py, tests/tests_geomstats/test_special_orthogonal.py
This replaces `gs.assertAllClose(., True)` by `assertTrue` for more meaningful error messages. Besides `assertAllEqual` is added for better comparison of arrays of `int` and `bool`.
=> Use assertTrue and add assertAllEqual

geomstats/geometry/matrices.py
The align method in geomstats/geometry/pre_shape.py invokes align_matrices from matrices.py that employs singular value decomposition for which autodiff fails if a full set of left/right singular vectors are requested. However, providing the flag 'full_matrices=False' to svd avoids this pitfall and yields the same alignment.
This pull request fixes the issue [autodiff fails on svd in matrices.py #1545](https://github.com/geomstats/geomstats/issues/1545).
The issue originally appeared in the [ICLR Computational Geometry & Topology Challenge 2022](https://github.com/geomstats/challenge-iclr-2022/issues/8) when trying to perform geodesic regression in Kendall shape space.
=> matrices.py: add 'full_matrices=False' to svd call

geomstats/_backend/pytorch/__init__.py, tests/tests_geomstats/test_backends.py
This PR acts specially in `array` for `torch` backend. It avoids unnecessary conversions to `numpy`.
Additionally, `dtype` has been added to `from_numpy` to `cast` when required. It needs to be extended to the other backends for compatibility, but it will play a role when `scipy` is used with `torch` or `tensorflow` (to ensure precision is kept).
`einsum` is also simplified. @ninamiolane the tests are not failing with this simplification, but I'm not sure if I'm missing something (I was not able to understand why `einsum` had such a complex wrapper). If you have an example that justifies the wrapper, please let me know so I revert the changes  there.
It closes #1537 and starts paving the path to better performance in GPU.
=> Fix and simplify pytorch backend: array, einsum, from_numpy

geomstats/geometry/hypersphere.py, geomstats/geometry/pre_shape.py, geomstats/geometry/quotient_metric.py
The constructors of HypersphereMetric and KendallShapeMetric do not (not correctly) handle the shape parameter. In fact, it gets lost on the way down to RiemannianMetric. 
It can be solved with some slight modifications in the constructors of HypersphereMetric, KendallShapeMetric and QuotientMetric.
This closes #1559 (Shape not set correctly for HypersphereMetric and KendallShapeMetric).
=> Fix shape of HypersphereMetric and KendallShapeMetric

geomstats/_backend/__init__.py, tests/conftest.py
Follows @captain-pool suggestion in #1285 to give an easy way to know what's the backend being used. (Already used it in tests.)
=> Add clean way of getting backend name

geomstats/_backend/tensorflow/__init__.py, geomstats/geometry/functions.py, tests/tests_geomstats/test_functions.py
Fix `functions` module to work with `tensorflow` (probably of your interest @kiranvad).
`tensorflow.linspace` is also updated in backend because output is `float64` (why?) when everywhere else it is `float32`.
=> Fix functions to work with tensorflow

geomstats/_backend/__init__.py, tests/conftest.py
Update `gs.backend` name to `geomstats.{_BACKEND}` for more meaningful error messages.
e.g.
`gs.min` raises `module 'geomstats.numpy' has no attribute 'min'` instead of `module 'numpy' has no attribute 'min'`.
=> Update backend name for more meaningful error messages

geomstats/datasets/_base.py, geomstats/datasets/utils.py
Large datasets should not be shipped with `geomstats` to avoid having a unnecessarily large source code. Besides, we can argue they should not even be part of the repo (e.g. 100mb is the limit in a push, if I'm not mistaken).
sklearn uses [figshare](https://figshare.com/account/home) to host datasets (notice it is very "academically" oriented, even requiring connection to ORCID). I think this is a very good solution.
As example, I've created a record for emg data available in `geomstats` (see [this](https://figshare.com/s/9a81e8f83a55c5e55e49)). With this, we can have code such as:
```
from geomstats.datasets._base import _fetch_remote
url = "https://figshare.com/ndownloader/files/35875382?private_link=9a81e8f83a55c5e55e49"
file_path = _fetch_remote(url, 'test.csv')
data = …
```
=> Add utils to download remote datasets

geomstats/geometry/discrete_curves.py, geomstats/geometry/euclidean.py, tests/tests_geomstats/test_discrete_curves.py, tests/tests_geomstats/test_euclidean.py, tests/tests_geomstats/test_geodesic_regression.py
This PR:
- adds unit-tests for geodesic regression on Euclidean space (sanity check)
- following failures in the above unit-tests, adds `parallel_transport` method to Euclidean metric
- adds unit-tests corresponding to the new `parallel_transport` method
- sets up unit-tests for geodesic regression on DiscreteCurves (this fails in all backends)
- following failures in the above unit-tests, adds `projection` method to DiscreteCurves 
- adds the unit-tests corresponding to the new `projection` method
Issue #1575 is one of the reasons why the unit-tests fail when performing geodesic regression on DiscreteCurves.
=> Add tests for geodesic regression on Euclidean space (sanity check) and DiscreteCurves

geomstats/learning/frechet_mean.py, tests/tests_geomstats/test_frechet_mean.py
This PR fixes issue #1578 by:
- computing the FrechetMean of discrete curves directly in SRV space,
- adds tests on the FrechetMean of discrete curves in test_frechet_mean.
Notes: 
- this only fixes #1578 by avoiding the computational problem (in the vectorization of pointwise_inner_products)
- the logs of the points at the frechet mean are not inverse, only their srv are. This is because of the computations of the starting points.
=> Fix: Frechet mean of discrete curves by computing in SRV space

geomstats/geometry/product_manifold.py, geomstats/geometry/product_riemannian_metric.py, tests/tests_geomstats/test_product_manifold.py
The organization of files and associated inheritance of Python classes in the Product (Manifold/Metric), NFold (Manifold/Metric), Landmarks, Curves and their metric is a mess.
This PR starts addressing this problem by addressing a few tasks of Issue #1492
=> Start fixing inheritance in Product/NFold/Landmarks/Curves Spaces

.gitignore, geomstats/geometry/discrete_curves.py
This PR starts the refactoring of DiscreteCurves, see issue #1183  and:
- make SRVMetric inherit from ElasticMetric : SRVMetric is an ElasticMetric with a=1 and b=0.5
- adapt the signatures of the methods, specifically the signatures of the constructors,
- add error messages if the user tries to use ElasticMetric with an ambient space different from R2.
=> Start Refactoring of Discrete Curves

geomstats/geometry/grassmannian.py, tests/data/grassmannian_data.py, tests/tests_geomstats/test_grassmannian.py
The goal of this PR is to use a consistent variable in `grassmannian.py`. Currently, the rank referred in the module and its document is either `p` or `k`.
https://github.com/geomstats/geomstats/issues/1557
=> Use `p` for the rank of Grassmannian manifolds

examples/empirical_frechet_mean_uncertainty_sn.py, geomstats/learning/expectation_maximization.py, geomstats/learning/frechet_mean.py, geomstats/learning/kmeans.py, geomstats/learning/mdm.py, geomstats/learning/pca.py, notebooks/11_real_world_applications__cell_shapes_analysis.ipynb, notebooks/12_real_world_applications__emg_sign_classification_in_spd_manifold.ipynb, notebooks/13_real_world_applications__graph_embedding_and_clustering_in_hyperbolic_space.ipynb, tests/tests_geomstats/test_expectation_maximization.py, tests/tests_geomstats/test_frechet_mean.py, tests/tests_geomstats/test_mdm.py, tests/tests_geomstats/test_riemannian_kmeans.py
This PR removes `point_type` argument from `FrechetMean` and updates dependent algorithms to not use it either if related with FrechetMean call.
**Why?** Only reason for `point_type` is a scalar multiplication. This can be done with einsum without really knowing if it is a vector or a matrix.  More interestingly, FrechetMean can be now applied even for ndim > 2 (may be relevant for e.g. Sasaki metric (#1568)).
A strong assumption now, that was already being used in another learning algorithms, but not in `FrechetMean`, is that the first dimension of `X` represents `n_samples`. This follows `sklearn` behavior. Therefore, if a single point is passed to `fit`, it will not work.
I've also taken advantage of this PR to clean a bit the code in `FrechetMean`.
**Points that deserve further …
=> Refactor FrechetMean

tests/conftest.py, tests/tests_geomstats/test_backends2.py
This change will allow to do something like:
```python
def test_func(self, a, b, c=3):
pass
```
This is achieved by changing the function signature to e.g. `(self, a, b, c)` and passing the default as data value if not encountered in the datum.
This feature is handy sometimes to reduce verbose in data creation.
=> Add ability of using kwargs in test functions

geomstats/_backend/__init__.py, geomstats/_backend/autograd/__init__.py, geomstats/_backend/numpy/__init__.py, geomstats/_backend/pytorch/__init__.py, geomstats/_backend/tensorflow/__init__.py, geomstats/geometry/skew_symmetric_matrices.py, geomstats/geometry/special_euclidean.py, geomstats/geometry/special_orthogonal.py, geomstats/geometry/symmetric_matrices.py, tests/data/backends_data.py, tests/tests_geomstats/test_backends.py, tests/tests_geomstats/test_backends2.py
This PR makes `array_from_sparse` more general by allowing creation of arrays with dimensions other than 2. Handling of dtype is also improved in pytorch.
Following this change:
* the computation of basis for some cases is simplified by avoiding using of `gs.stack`.
* `get_mask_i_float` is removed from backend as it is a particular case (this pruning of backend functions is valuable to ensure we keep it slim and tested properly)
=> Make `array_from_sparse` more general

setup.cfg
geomstats does not work properly with scipy 1.9. We need to identify better the reason, meanwhile let's limit max version to have the tests running.
=> Fix max version of scipy

tests/data_generation.py
**Main idea**: in most cases, vectorization testing can be handled at data generation level. That is, the same test that asserts a particular case can be used to assert any of the possible combinations of (vectorized) inputs. Thus, data generation should handle the creation of all possible combinations.
**Assumption**: repeating a given input `n_reps` times and compare the repeated output against the non-repeated expected output repeated `n_reps` is a strong way of testing the vectorization correctness of a method.
**Examples**
1) Assume a function takes a point e.g. `point = gs.ones(3)` and outputs itself. The possible input combinations are:
* `point = gs.ones(3)` -> `out = gs.ones(3)`
* `point = gs.ones(1, 3)` -> `out = gs.ones(3)` (due to the way geomstats handles single points)
* …
=> Add strategy to vectorize tests during data generation

geomstats/geometry/connection.py
With the current implementation of log(), the geodesics competed by connection are not necessarily minimizing geodesics
This PR fixes this (assuming Injectivity_radius() is implemented)
=> FIX: adding inject_radius constraint to enforce minimizing geodesics

geomstats/geometry/discrete_curves.py, geomstats/learning/frechet_mean.py, geomstats/visualization/spd_matrices.py, notebooks/10_practical_methods__shape_analysis.ipynb, notebooks/11_real_world_applications__cell_shapes_analysis.ipynb, tests/data/discrete_curves_data.py, tests/data/landmarks_data.py, tests/data_generation.py, tests/tests_geomstats/test_discrete_curves.py, tests/tests_geomstats/test_frechet_mean.py, tests/tests_geomstats/test_geodesic_regression.py, tests/tests_geomstats/test_landmarks.py, tests/tests_geomstats/test_visualization.py
This PR:
- renames `n_sampling_points` into `k_sampling_points`
- adds `k_sampling_points` as an input parameter and attribute for the spaces of curves
- modifies the belongs functions accordingly
- modifies the dimension of the spaces accordingly
- adapts the unit-tests.
This continues to address Issue #1183 .
This allows:
- to become more consistent with spaces of landmarks, that takes `k_landmarks` as input
- to avoid existing confusions between `n_points` (number of points on a given manifold)
- to allow the spaces of (closed) discrete curves to have the right dimension (which was set to infinity before).
What remains to be done:
- potentially make the changes in the metrics defined on curves.
=> Add k_sampling_points as an attribute for spaces of curves

geomstats/information_geometry/README.rst
In the README file of the information geometry module:
- Update broken link to information geometry notebook
- Add link to Sao Paulo traffic optimization notebook
=> Update information geometry readme

geomstats/_backend/__init__.py, geomstats/_backend/autograd/__init__.py, geomstats/_backend/numpy/__init__.py, geomstats/_backend/pytorch/__init__.py, geomstats/_backend/tensorflow/__init__.py, tests/tests_geomstats/test_backends.py
Simply adding `gs.quantile`, mirroring `np.quantile`, `torch.quantile`, and `tfp.stats.percentile`.
I am using this in a project of mine because I am constructing SPD matrices using a kernel, and automatically setting the length scale of the kernel according to the median distance between points.
=> added backend function gs.quantile

geomstats/geometry/connection.py
This PR reverts #1621: as can be seen [here](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.minimize.html), constraints are implemented only for "COBYLA, SLSQP and trust-constr". Therefore, the addition is being ignored by `minimize`. (This is one of the reasons I don't like scipy optimization API @ninamiolane.)
This is something to take into consideration in #1552.
Probably of your interest @franciscoeacosta.
=> Revert #1621

examples/plot_expectation_maximization_ball.py
Update example to work with last version of matplotlib.
closes #1645.
=> Fix use of "projection" in visualization example

.github/workflows/docs.yml, .github/workflows/lint.yml, .github/workflows/test.yml
`ubuntu-18.04` will be deprecated, so we use `latest` now.
=> Update ubuntu version in workflows due to deprecation warning

geomstats/geometry/pullback_metric.py, tests/data/pullback_metric_data.py, tests/tests_geomstats/test_pullback_metric.py
This PR:
- fixes a bug in the computation of the pullback metric when manifold has dim 1.
- adds unit-tests to test_pullback_metric, ensuring that the computations work in the case of an immersed circle.
=> Fix pullback metric for manifolds of dim 1

geomstats/geometry/grassmannian.py, geomstats/geometry/special_euclidean.py, geomstats/geometry/special_orthogonal.py
`GrassmanianCanonicallMetric` -> `MatricesMatrices` -> `EuclideanMetric` -> `RiemannianMetric`, therefore inheritance from  `RiemannianMetric` is redundant (-> means "inherits from").
`SpecialEuclidean` and `SpecialOrthogonal` are interfaces, so they need to inherit from anything else.
=> Fix inheritance of GrassmanianCanonicallMetric, SpecialEuclidean and SpecialOrthogonal

geomstats/_backend/autograd/linalg.py, geomstats/_backend/numpy/linalg.py, setup.cfg
`scipy.linalg.expm` is vectorized since 1.9.1. This PR changes `gs.linalg.expm` for `numpy` and `autograd` backends to work with `scipy` (1.9.1). 
It breaks compatibility with previous versions of `scipy`, but I think it is better to use the most up-to-date version.
closes #1620, #1637, #1657.
=> Fix expm due to changes in scipy.linalg.expm

geomstats/_backend/__init__.py, geomstats/_backend/autograd/__init__.py, geomstats/_backend/autograd/autodiff.py, geomstats/_backend/numpy/__init__.py, geomstats/_backend/numpy/autodiff.py, geomstats/_backend/pytorch/autodiff.py, geomstats/_backend/tensorflow/__init__.py, geomstats/_backend/tensorflow/autodiff.py, geomstats/geometry/pullback_metric.py, geomstats/geometry/riemannian_metric.py, tests/data/pullback_metric_data.py, tests/tests_geomstats/test_pullback_metric.py
This PR:
- overwrites the method `inner_product_derivative_matrix` in PullbackMetric, childclass of RiemannianMetric
to fix a bug in the automatic differentiation required in this method,
- adds corresponding unit tests.
The parallel transport of the pullback metric is extremely slow, thus its test is skipped in autograd and tensorflow to avoid slowing down the CI.
The bug:
In pullback metric, the metric matrix comes from the automatic differentiation of the immersion defining the pullback.
Differentiating again the result of this differentiation was creating an error.
The fix:
In the case of the pullback metric, we have a closed form for the derivative of the metric matrix that we can use.
This closed form requires the computation of the hessian of the immersion.
For this reason, …
=> Fix bug in the autodiff of pullback metric matrix

tests/tests_geomstats/test_dirichlet.py, tests/tests_geomstats/test_gamma.py, tests/tests_geomstats/test_stiefel.py
This PR skips unit-tests that fail too often.
With @lpereira95  we noted that the failures of the tests on the Stiefel manifold may come from a problem in the mathematical formulation, because it produces NaNs. Possibly coming from the 2 leafs of the Stiefel.
Failures of the Dirichlet may come from the negative curvature.
=> Skip unit-tests that are failing too often (Stiefel, Gamma, Dirichlet)

geomstats/geometry/full_rank_correlation_matrices.py, geomstats/geometry/grassmannian.py, geomstats/geometry/special_euclidean.py, tests/data/special_euclidean_data.py
=> Remove unnecessary use of metric as property and fix SpecialEuclideanMatrixCanonicalLeftMetric name

geomstats/visualization/hypersphere.py
The visualization library for the Circle and the Sphere is inconsistent in the use of ```gs.linspace``` and ```gs.arange``` in the creation of the mesh.
In addition there is an overlap in the mesh in the circle class (n_angles are actually n_angles-1 unique angles, since two are overlapping) and there is a visible gap in both meridian and latitude circles due to the ```gs.arange``` function excluding the end value.
According to the numpy [1.23] documentation:
> When using a non-integer step, such as 0.1, it is often better to use ```numpy.linspace```.
therefore ```gs.linspace``` is used for consistency.
=> Consistency fix in visualization of Sphere/Circle

geomstats/geometry/poincare_half_space.py, geomstats/geometry/pullback_metric.py, geomstats/information_geometry/normal.py, tests/data/poincare_half_space_data.py, tests/tests_geomstats/test_normal.py, tests/tests_geomstats/test_poincare_half_space.py
This PR:
- redefines the metric on normal distributions using `PullbackDiffeoMetric` 
- changes the scaling of the embedding metric `PoincareHalfSpaceMetric` to 2.
=> Fix wrong scaling in NormalMetric

geomstats/geometry/euclidean.py, geomstats/geometry/hermitian.py, geomstats/geometry/hypersphere.py, geomstats/geometry/minkowski.py, tests/tests_geomstats/test_product_manifold.py
In some subclasses of `RiemannianMetric`, the `metric_matrix` method only returned a single copy of the matrix, regardless of the array passed as `base_point`. This PR corrects that in `HermitianMetric`, `HypersphereMetric` and `MinkowskiMetric`. It amends the method in `EuclideanMetric` to use `gs.broadcast_to` instead of `gs.tile` as this method permits more flexibility in the array shape.
=> Vectorization of metric_matrix

geomstats/geometry/complex_manifold.py, geomstats/geometry/complex_riemannian_metric.py, geomstats/geometry/hermitian.py
Remove `CDTYPE = gs.get_default_cdtype()` from the complex manifolds hermitian.py, complex_manifold.py and complex_riemannian_metric.py.
This PR is related to the issue: https://github.com/geomstats/geomstats/issues/1696 opened by @lpereira95.
=> Remove CDTYPE = gs.get_default_cdtype() from complex manifolds

geomstats/information_geometry/normal.py, tests/tests_geomstats/test_normal.py
This PR adds the formula for the constant sectional curvature of the normal distributions (equal to -1/2).
It adds the corresponding test.
Note that the tests of the normal distributions do not leverage the hierarchy of tests.
=> Add sectional curvature of univariate normal distributions + tests

geomstats/information_geometry/multivariate_normal.py, tests/data/multivariate_normal.py, tests/tests_geomstats/test_multivariate_normal.py
Add the statistical manifold of multivariate diagonal normal distributions.
It is a product manifold of the statistical manifold of univariate normal distributions.
`MultivariateDiagonalNormalDistributions` and `MultivariateDiagonalNormalMetric` store data points and tangent vectors by stacking the location (mean vector) and the diagonal of the covariance matrix in a vector.
=> Add statistical manifold of multivariate diagonal normal distributions

geomstats/geometry/complex_manifold.py
For coherence, (for now) complex objects emulate `Manifold` inheritance structure, but do not inherit from any `Manifold` object.
This will very soon need to be rethought (it will be easier now, as we have several complex objects), as it leads to a lot of (almost) code duplication.
Test inheritance structure will be make consistent soon.
=> Fix complex manifold inheritance structure

geomstats/_backend/tensorflow/__init__.py, geomstats/geometry/siegel.py, tests/data/siegel_data.py
The Siegel Riemannian logarithm is was failing when `point` equals the null matrix.
The Siegel Riemannian exponential map is failing when `tangent_vec` equals the null matrix.
These errors are due the the matrix inversion of a null matrix.
This PR fix these errors and add the corresponding tests.
=> Fix Siegel log and exp errors for zero matrices

geomstats/errors.py, tests/tests_geomstats/test_errors.py
`geomstats.errors.check_point_shape` is amended so that it does not always raise a `ShapeError` if the shapes do not match. It is possible to simply check the shape by setting the optional parameter `suppress_error=True` and obtain a boolean return value. This is as requested by other developers during the IHP hackathon
We can use this to provide checks on inputs in methods for all `Manifold` and `RiemannianMetric` subclasses, if that seems worthwhile. In that case we should probably implement a method `check_point_shape` in those classes which wraps this, so that it can simply be called as `self.check_point_shape(point)`.
=> Amend errors.check_point_shape 

geomstats/_backend/_dtype_utils.py, geomstats/_backend/autograd/_dtype.py, geomstats/_backend/autograd/random.py, geomstats/_backend/numpy/_dtype.py, geomstats/_backend/numpy/random.py, geomstats/_backend/pytorch/_dtype.py, geomstats/_backend/pytorch/random.py, geomstats/_backend/tensorflow/_dtype.py, geomstats/_backend/tensorflow/random.py, tests/data/backends_data.py, tests/tests_geomstats/test_backends2.py
Generalizes #1721 by creating proper decorators and applying them to other distributions.
Additional tests were added to ensure imaginary numbers are handled properly.
Necessary for #1739.
=> Update backend random distributions to accept complex type

geomstats/_backend/autograd/__init__.py, geomstats/_backend/tensorflow/__init__.py, geomstats/geometry/base.py, geomstats/geometry/complex_manifold.py, geomstats/geometry/euclidean.py, geomstats/geometry/manifold.py, geomstats/geometry/matrices.py, geomstats/geometry/skew_symmetric_matrices.py, geomstats/geometry/special_euclidean.py, geomstats/information_geometry/binomial.py, tests/data/binomial_data.py, tests/geometry_test_cases.py, tests/tests_geomstats/test_binomial.py, tests/tests_geomstats/test_geodesic_regression.py
This PR:
**1)** sets the expectations for point shapes of manifolds of dimension 1 (relevant for you @YannCabanes):
* point: `(1,)`; multiple points `(n_points, 1)`
* several reasons for this:
i. spaces that also work with higher dimensions naturally represent points for case `dim=1` as `(1,)` (e.g. `Euclidean`)
ii. `()` treatment would require several exceptions in the code: e.g. `ProductManifold`; `gs.random.rand` use to create a generic function to create random points 
* points are represented by `gs.array`, never `float`
**2)** fixes several general functions in abstract classes (building on top of previous point)
**3)** fixes several vectorizations in abstract classes when `point` is ignored
**4)** fixes docstrings of abstract classes regarding points shapes
**5)** modifies …
=> Fix point shapes

geomstats/_backend/autograd/autodiff.py
value comes from free when computing gradient, so we don't need to recompute it. This is especially relevant for cases where computation of value is expensive (which is often the case in `geomstats`).
=> Fix autograd value_and_grad to avoid duplicate computation of value

geomstats/information_geometry/fisher_rao_metric.py, tests/data/fisher_rao_metric_data.py, tests/tests_geomstats/test_fisher_rao_metric.py
Fix `FisherRaoMetric.inner_product_derivative_matrix`.
Previous formula was incorrect. Validation done against univariate normal distributions (further validation to be done soon).
Updated docstrings and added back earlier removed tests.
Done with @alebrigant.
=> Fix FisherRaoMetric inner product derivative matrix

geomstats/learning/_sklearn_wrapper.py, geomstats/learning/agglomerative_hierarchical_clustering.py, geomstats/learning/kernel_density_estimation_classifier.py, geomstats/learning/knn.py
Last sklearn release ([1.2.0](https://pypi.org/project/scikit-learn/1.2.0/)) needs all the class parameters to be stored as class attributes when inheriting from a sklearn estimator object. This is done in this PR to ensure compatibility. No backwards compatibility broken.
=> Fix learning algorithms to work with last sklearn version

geomstats/geometry/scalar_product_metric.py, tests/tests_geomstats/test_scalar_product_metric.py
Following a review by @YannCabanes in #1727 and #1761 of all the scaling factors, it is clear that INVERSE_QUADRATIC_LIST should be INVERSE_SQRT_LIST instead. This PR corrects that error.
=> Correct scaling in ScalarProductMetric

examples/plot_geodesics_poincare_polydisk.py, geomstats/geometry/_hyperbolic.py, geomstats/geometry/complex_poincare_disk.py, geomstats/geometry/hpd_matrices.py, geomstats/geometry/hyperbolic.py, geomstats/geometry/hyperboloid.py, geomstats/geometry/manifold.py, geomstats/geometry/poincare_ball.py, geomstats/geometry/poincare_half_space.py, geomstats/geometry/poincare_polydisk.py, geomstats/geometry/positive_reals.py, geomstats/geometry/riemannian_metric.py, geomstats/geometry/scalar_product_metric.py, geomstats/geometry/siegel.py, geomstats/information_geometry/normal.py, tests/data/complex_poincare_disk_data.py, tests/data/hyperboloid_data.py, tests/data/poincare_half_space_data.py, tests/data/poincare_polydisk_data.py, tests/data/positive_reals_data.py, tests/data/siegel_data.py, tests/tests_geomstats/test_complex_poincare_disk.py, tests/tests_geomstats/test_hyperboloid.py, tests/tests_geomstats/test_poincare_half_space.py, tests/tests_geomstats/test_poincare_polydisk.py, tests/tests_geomstats/test_scalar_product_metric.py, tests/tests_geomstats/test_siegel.py
Closes #1757 and closes #1758 by removing the `scale` parameter from various manifolds.
These are the `Hyperbolic`, `HPDMatrices` and `PoincarePolydisk` manifolds, along with all their related classes.
@YannCabanes The tests are failing on `PoincarePolydisk` and I don't understand the objects well enough to remedy the issue. Maybe you could have a look?
=> Reserve `scale` parameter to ScalarProductMetric

geomstats/geometry/product_manifold.py, geomstats/geometry/product_riemannian_metric.py
There's a lot of (unnecessary) code duplication in `ProductManifold` and `ProductManifoldMetric`.
This PR uses a mixins approach to remove code duplication. A more functional-based approach could have been used, but it would probably require functions with very long signatures.
`_IterateOverFactorsMixins` is implemented in the file `product_riemannian_metric.py` only to avoid circularity imports. Probably these two files  should be merged soon.
@johnharveymath, do you think this abstraction makes the code easier to manipulate or is it better to maintain the current code duplication (or find an alternative solution)?
=> Remove code duplication in ProductManifold and ProductManifoldMetric

geomstats/_backend/tensorflow/__init__.py
Allows `gs.stack` to accepts array of different dtypes in tensorflow (this behavior is already allowed in the other backends). If conversion is needed, it converts to wider dtype.
Required for #1764.
=> Allow gs.stack to receive arrays of different dtypes in tf

geomstats/geometry/product_manifold.py, geomstats/geometry/product_riemannian_metric.py
Extend product manifold to handle factors with different fields (i.e. some factors are real manifold/metric, other are complex).
Product manifold points are, in this case, represented with complex arrays. Only the real part is sent for the computations within real manifolds. @YannCabanes, this is the reason I didn't want you to care about complex arrays when developing real manifolds.
Required for #1764.
=> Extend product manifold to handle factors with different fields

geomstats/geometry/base.py, geomstats/geometry/euclidean.py, geomstats/geometry/full_rank_correlation_matrices.py, geomstats/geometry/general_linear.py, geomstats/geometry/heisenberg.py, geomstats/geometry/hermitian.py, geomstats/geometry/invariant_metric.py, geomstats/geometry/lie_algebra.py, geomstats/geometry/lie_group.py, geomstats/geometry/lower_triangular_matrices.py, geomstats/geometry/skew_symmetric_matrices.py, geomstats/geometry/special_euclidean.py, geomstats/geometry/special_orthogonal.py, geomstats/geometry/symmetric_matrices.py, geomstats/learning/kalman_filter.py, tests/data/invariant_metric_data.py, tests/data/special_euclidean_data.py, tests/data/special_orthogonal_data.py, tests/tests_geomstats/test_invariant_metric.py, tests/tests_geomstats/test_special_euclidean.py, tests/tests_geomstats/test_special_orthogonal.py
This PR brings some fixes and improvements developed while refactoring tests in #1767. Since #1767 is a long PR and will take a while to get finished, some fixes and improvements done there are merged separately here.
Changes include:
1. closes #1694 by using `n_la` and `n_lg` in `MatrixLieAlgebra` and `MatrixLieGroup`, respectively.
2. for consistency, `get_identity` is removed from several files and only `identity` is kept (as a property)
3. vectorization is fixed in `FullRankCorrelationMatrices.tangent_submersion`
4. `left_or_right="left"` is replaced by `left=True` in several places (bools are more robust than strings)
5. `from_vector` is added to `LowerTriangularMatrices` for consistency with other matrix vector spaces
6. special_euclidean `homogeneous_representation` is simplified …
=> Fixes and improvements coming from test refactoring

.codecov.yml, .github/workflows/test.yml
After some months deliberating, we finally decided to drop support to `tensorflow`. This PR turns the CI tests off for `tf`. Soon to come a PR fully removing it. (with @ninamiolane)
=> Stop tf tests in CI

geomstats/_backend/numpy/linalg.py, geomstats/geometry/base.py
Adds a check for complex matrices which ensures that the scipy.linalg.logm method is used. This avoids bugs that arise otherwise.
The logm method implemented here gives incorrect answers for matrices that are symmetric and complex, but works fine for real symmetric matrices.
=> Fix bugs that arise for complex matrices

geomstats/_backend/autograd/__init__.py, geomstats/_backend/pytorch/linalg.py, geomstats/geometry/positive_lower_triangular_matrices.py
In `scipy` 1.10, [`linalg.sqrtm`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.sqrtm.html) doubles the precision of the output if complex. This behavior breaks the conversion back to `torch` tensor.  This PR fixes it.
=> Fix sqrm for pytorch due to changes in scipy

geomstats/geometry/hpd_matrices.py, geomstats/geometry/siegel.py, tests/data_generation.py, tests/geometry_test_cases.py
This PR ensures consistency of output types in complex metrics. In particular, new tests are added for inner_product, dist, log, and exp.
It results from the discussion in #1764.
=> Fix complex output types

setup.cfg
Version `23.1.0` of `black` behaves very differently than previous one (e.g. "would reformat" message).
For now it is better to keep using previous one.
=> Freeze black version due to breaking updates

.github/workflows/docs.yml, .github/workflows/lint.yml, .github/workflows/test.yml, setup.cfg
Changes made by this PR can be summarized as follows:
- Set the `cache` and `cache-dependency-path` argument to enable caching to speed up CI times.
=> feat(ci): add `pip` caching to CI

geomstats/_backend/pytorch/__init__.py
Modify `torch.linspace` to get the same behaviours as `numpy.linspace` (accept array-like `start` or `stop`, even lists). Original `torch.linspace` only works with `start` and `stop` inputs of type `Number` or `0D-Tensor`.
Use `torch.broadcast_arrays` to get final result shape, stack results after looping over flattened inputs and return results after reshaping.
```
import os
os.environ["GEOMSTATS_BACKEND"] = "pytorch"
print(gs.linspace(0, 1, 10))  # 1D
print(gs.linspace(gs.array(0), gs.array(1), 10))  # 1D
print(gs.linspace(gs.array([0]), gs.array([1]), 10))
print(gs.linspace(gs.array(0), gs.array([1]), 10))
print(gs.linspace(gs.array([0.9]), 0, 10))
print(gs.linspace(gs.array([0, 9]), gs.array([1, 10]), 10))
print(gs.linspace(gs.array([[[0, 9, 4]]]), gs.array([[1], [15], [5]]), 10))
```
=> Make torch.linspace accept array-like inputs

geomstats/geometry/stiefel.py, tests/data/stiefel_data.py, tests/tests_geomstats/test_frechet_mean.py
This PR refactors Stiefel by removing the `log`  computation to an external object (a solver). This way, numerical parameters are easy to control and we can implement new algorithms to compute the log. Additionally, `lifting` is fixed (it was not working) and a tolerance is added to a test that fails recurrently.
It should be said that the `log` has problems, as during the iterative process it starts getting complex numbers as result. This comes from `logm`. We should address this is a new PR.
=> Refactor Stiefel

geomstats/geometry/discrete_curves.py, geomstats/information_geometry/binomial.py, geomstats/information_geometry/exponential.py, geomstats/information_geometry/geometric.py, geomstats/information_geometry/poisson.py, geomstats/learning/geodesic_regression.py, pyproject.toml, tests/geometry_test_cases.py, tests/tests_geomstats/test_pre_shape.py
`autograd==1.6.2.` (released last friday) seems to solve the issue created by `numpy==1.25` (see #1866). Therefore, I'm unfreezing it again.
It also updates the code to work properly with last release of `scipy` (last sunday).
=> Unfreeze numpy and update code for scipy 1.11.0

geomstats/geometry/spd_matrices.py, tests/tests_geomstats/test_spd_matrices.py
Fixes SPDBuresWassersteinMetric parallel transport following @GitZH-Chen suggestion in #1859.
closes #1859
=> Fix in-place operation in SPDBuresWassersteinMetric parallel transport

geomstats/geometry/complex_poincare_disk.py
Fix minor error in variable name in method `squared_dist` of the class `ComplexPoincareDiskMetric`: the variable name `sq_dist` is used instead of `dist`.
=> Fix minor error in variable name in method squared_dist of the class ComplexPoincareDiskMetric

geomstats/geometry/product_manifold.py, geomstats/geometry/product_positive_reals_and_poincare_disks.py, tests/data/invariant_metric_data.py, tests/data/product_manifold_data.py, tests/tests_geomstats/test_product_positive_reals_and_poincare_disks.py
The methods `squared_dist`, `norm` and `squared_norm` of the class `ProductPositiveRealsAndComplexPoincareDisksMetric` return complex data type.
This PR fixes this issue.
=> Fix complex data type in squared_dist, norm and squared_norm in the manifold ProductPositiveRealsAndComplexPoincareDisks

geomstats/geometry/pullback_metric.py, tests/data/pullback_diffeo_metric_data.py, tests/geometry_test_cases.py
=> add geodesic to pullbackdiffeometric

geomstats/_backend/pytorch/__init__.py
Hi, 
I didn't check all boxes, but this is just a minor change. I have created an extended version of the _backend of geomstats for my [pyRecEst](https://github.com/FlorianPfaff/pyRecEst) library and now I want to see if you are interested in "mainlining" some fixes.
This fix concerns backend.mod. Currently, mod uses pytorch's fmod. However torch.fmod behaves like np.fmod. np.fmod and np.mod do not behave identically. A key difference is the handling of negative values. Hence, I changed torch.mod to use torch.remainder instead, which behaves like np.mod.
=> Use "remainder" instead of "fmod" for mod for pytorch backend

geomstats/geometry/connection.py, geomstats/geometry/poincare_half_space.py, geomstats/geometry/riemannian_metric.py, geomstats/information_geometry/base.py, geomstats/information_geometry/beta.py, geomstats/information_geometry/binomial.py, geomstats/information_geometry/categorical.py, geomstats/information_geometry/dirichlet.py, geomstats/information_geometry/exponential.py, geomstats/information_geometry/gamma.py, geomstats/information_geometry/geometric.py, geomstats/information_geometry/multinomial.py, geomstats/information_geometry/normal.py, geomstats/information_geometry/poisson.py, geomstats/numerics/bvp.py, geomstats/vectorization.py, pyproject.toml, tests/data/binomial_data.py, tests/data/multinomial_data.py, tests/tests_geomstats/test_categorical.py, tests/tests_geomstats/test_dirichlet.py
This PR fixes several issues in information geometry (most of them related with vectorization) and cleans several parts of the code by taking more advantage of inheritance and/or new vectorization functions.
The main addition is the notion of `RandomVariable`, in particular `ScipyRandomVariable`. This comes from the fact that the `InformationManifold` method `sample` uses `scipy.stats.<distribution>.rvs`. We just need to "translate" the inputs from geomstats to `scipy`, which can be done in a generic way (or at least in two: one for univariate distributions, and another for multivariate). We also take advantage of the `scipy.stats.<distribution>.pdf`: for some manifolds we directly use this method, for others we use it to validate our implementations (in new tests framework - coming very …
=> Fix and clean information geometry

docs/contributing/index.rst, docs/getting_started/first-steps.rst, docs/hackathons.rst, geomstats/information_geometry/multinomial.py, geomstats/information_geometry/poisson.py, geomstats/visualization/pre_shape.py, geomstats/visualization/spd_matrices.py, notebooks/00_foundations__introduction_to_geomstats.ipynb, notebooks/01_foundations__manifolds.ipynb, notebooks/02_foundations__connection_riemannian_metric.ipynb
I've fixed a few typos in docs, docstrings and tutorial notebooks.
=> Fix typos in docs, docstrings and tutorial notebooks

geomstats/geometry/open_hemisphere.py, tests/tests_geomstats/test_geometry/data/open_hemisphere.py, tests/tests_geomstats/test_geometry/test_open_hemisphere.py
This PR builds on top of #1904  and #1908 to add the open hemisphere and the corresponding pullback diffeo metric (from the hyperboloid). This space will be used later to add PHC (poly-hyperbolic-Cholesky) metrics on the space of full-rank correlation matrices.
The open hemisphere can be defined as 
```math
\mathrm{HS}^{k-1}=\left\{x \in \mathbb{R}^k: \|x\|=1\text { and } x_0>0\right\}
```
There's freedom in the choice of the coordinate that is set to >0. We've done it in the first coordinate for compatibility with the hyperboloid model.
This space is diffeomorphic to the hyperboloid model, so we added the diffeomorphism and the corresponding pullback diffeo metric.
(Done in collaboration with @olivierbisson.)
NB: the "base" PRs need to be merged first. Tests will pass after it is done.
=> Add open hemisphere and pullback diffeo metric

geomstats/geometry/spd_matrices.py, tests/tests_geomstats/test_geometry/data/spd_matrices.py, tests/tests_geomstats/test_geometry/test_spd_matrices.py
This PR builds on top of  https://github.com/geomstats/geomstats/pull/1872 to implement a `LieCholeskyMetric`, which is a `PullbackDiffeoMetric` by the Cholesky map, on the `SPDMatrices`. The diffeomorphism is between the `SPDMatrices` and the `PositiveLowerTriangularMatrices` equipped with an invariant metric.
(with @olivierbisson)
=> Add LieCholeskyMetric on SPDMatrices

geomstats/geometry/positive_lower_triangular_matrices.py
This PR adds a more robust random point generation strategy to positive lower triangular matrices (PLT) to reduce the frequency of generation of points close to singularities (i.e. null eigenvalues) as it greatly affects computations (in particular, `logm`).
=> Add more robust random point generation for PLT

geomstats/datasets/prepare_graph_data.py, geomstats/distributions/lognormal.py, geomstats/geometry/discrete_curves.py, geomstats/geometry/invariant_metric.py, geomstats/geometry/pre_shape.py, geomstats/geometry/product_manifold.py, geomstats/geometry/quotient_metric.py, geomstats/geometry/sub_riemannian_metric.py, geomstats/information_geometry/multinomial.py, geomstats/learning/agglomerative_hierarchical_clustering.py, geomstats/learning/radial_kernel_functions.py, geomstats/learning/wrapped_gaussian_process.py
Correct equations, references, bullet points, etc rendering in documentation.
No code modification.
Can you also indicate how to correct these equations? @luisfpereira
(see error "Double exponents: use braces to clarify")
https://geomstats.github.io/api/geomstats.geometry.html#geomstats.geometry.quotient_metric.QuotientMetric.curvature_derivative
https://geomstats.github.io/api/geomstats.geometry.html#geomstats.geometry.pre_shape.KendallShapeMetric.directional_curvature_derivative
https://geomstats.github.io/api/geomstats.geometry.html#geomstats.geometry.quotient_metric.QuotientMetric.directional_curvature_derivative
=> Improve documentation rendering, 2nd part

geomstats/_backend/autograd/autodiff.py, geomstats/_backend/pytorch/autodiff.py, geomstats/geometry/discrete_surfaces.py, geomstats/geometry/fiber_bundle.py, geomstats/geometry/grassmannian.py, geomstats/geometry/special_euclidean.py, geomstats/geometry/sub_riemannian_metric.py, geomstats/information_geometry/fisher_rao_metric.py, geomstats/learning/geodesic_regression.py, geomstats/numerics/optimizers.py, geomstats/test_cases/backend/autodiff.py, tests/tests_geomstats/test_backend/data/autodiff.py, tests/tests_geomstats/test_backend/test_autodiff.py
Inspired by #1929, this PR is the first of a series of PRs that intends to fix and clean the `autodiff` backend module.
In this PR, the focus is the `value_and_grad` function. The following is done:
* vectorization is fixed, i.e. `value_and_grad` is now able to handle (correctly) batches of points
* `point_ndims` variable is added, following a similar behavior as `argnums` (used both in `autograd` and `pytorch`). This variable is required to handle vectorization properly
* custom gradient is fixed for `pytorch` to allow a custom computation of the squared distance gradient (see `SpecialEuclidean` and `Grassmannian`). Before this was only working for `autograd`
* custom gradient is improved for `pytorch` backend with potential gains in performance for the cases where only the gradient wrt …
=> Fix and clean value_and_grad

geomstats/learning/expectation_maximization.py, geomstats/learning/kmeans.py, tests/tests_geomstats/test_learning/test_kmeans.py
This fixes an error generated by using `RiemannianKMeans` with `space=Euclidean()`.
This code for example creates an error:
```
from geomstats.geometry.euclidean import Euclidean
from geomstats.learning.kmeans import RiemannianKMeans
r2 = Euclidean(2)
points = r2.random_point(10)
clustering = RiemannianKMeans(space=r2, n_clusters=2)
clustering.fit(points)
```
@luisfpereira this is probably not be the optimal way to fix the error, tell me what you think !
=> Fix KMeans error with Euclidean space

geomstats/_backend/pytorch/__init__.py, geomstats/algebra_utils.py, geomstats/geometry/siegel.py
The function `siegel.metric.isometry` returns an error when used on PyTorch GPU.
When I run the following code in a Google Colab environment with the execution type "T4 GPU":
```
%env GEOMSTATS_BACKEND=pytorch
try:
import geomstats
except ImportError:
!pip install geomstats["pytorch"]
import geomstats
import geomstats.backend as gs
import torch
import torch.cuda
from geomstats.geometry.siegel import Siegel, SiegelMetric
device = torch.device("cuda:0")
point = torch.tensor([[0.5 + 0.2j, 0], [0, 0.5]], requires_grad=True, device=device)
point_to_zero = torch.tensor([[-0.5, 0], [0.1j, 0]], requires_grad=True, device=device)
siegel = Siegel(n=2)
isometry = siegel.metric.isometry(point=point, point_to_zero=point_to_zero)
```
I obtain the following error message:
```
env: …
```
=> Simplify creation of identity matrices in the Siegel manifold

geomstats/geometry/discrete_curves.py, tests/tests_geomstats/test_geometry/data/discrete_curves.py, tests/tests_geomstats/test_geometry/test_discrete_curves.py
This PR follows #1924 to:
* fix `IterativeHorizontalGeodesicAligner.discrete_horizontal_geodesic` vectorization
* raise `NotImplementedError` in new fiber bundles to avoid recursion errors when calling the log on the quotient metrics
* improve SRVReparametrizationBundle tests:
* by removing skips
*  testing for both even and odd `k_sampling_points` due to different behavior in Euler step (this should probably be done in a specific test for the aligner later)
* improve discrete curves tests by adding tests for all quotient metrics
* remove empty quotient metrics  (closes #1931)
=> Fix discrete curves vectorization and remove empty quotient metrics

geomstats/geometry/discrete_curves.py, geomstats/geometry/fiber_bundle.py, geomstats/geometry/full_rank_correlation_matrices.py, geomstats/geometry/manifold.py, geomstats/geometry/pre_shape.py, geomstats/geometry/quotient_metric.py, geomstats/geometry/rank_k_psd_matrices.py, geomstats/test/random.py, geomstats/test_cases/geometry/discrete_curves.py, geomstats/test_cases/geometry/fiber_bundle.py, geomstats/test_cases/geometry/pre_shape.py, tests/tests_geomstats/test_geometry/test_discrete_curves.py, tests/tests_geomstats/test_geometry/test_fiber_bundle.py, tests/tests_geomstats/test_geometry/test_full_rank_correlation_matrices.py, tests/tests_geomstats/test_geometry/test_pre_shape.py, tests/tests_geomstats/test_geometry/test_quotient_metric.py, tests/tests_geomstats/test_geometry/test_rank_k_psd_matrices.py
This PR improves `FiberBundle`/`QuotientMetric` API (builds on top of https://github.com/luisfpereira/geomstats/pull/8) by making `total_space` a private attribute of `FiberBundle` (cf. `space` is a private method of `Connection`), and `QuotientMetric` receive `total_space` (which is stored privately) instead of `fiber_bundle`.
This design avoids weird code as `total_space.quotient.metric.fiber_bundle.total_space`, which was possible before. (Now it is possible to do `total_space.quotient.metric._total_space`, but private attributes are not supposed to be accessed from outside.)
Another reason for this PR is to hide a bit more the notion of `FiberBundle` from the user API (only power users may need to instantiate fiber bundles), so the learning curve for working with quotient spaces in …
=> Improve FiberBundle/QuotientMetric API

.github/workflows/docs.yml, .github/workflows/lint.yml, .github/workflows/test.yml
Due to deprecation of Node.js 16 (see https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/).
Stopped using `rbialon/flake8-annotations@v1` because does not have Node.js 20 version (and https://pypi.org/project/flake8-github-annotations/ looks like a good alternative).
=> Update versions of github actions

geomstats/geometry/invariant_metric.py, geomstats/numerics/geodesic.py, geomstats/numerics/ivp.py, tests/tests_geomstats/test_numerics/test_exp.py
Following #1944, this PR simplifies `ExpODESolver` by designing a less flexible interface for `ODEIVPSolver` (consequently, `ScipySolveIVP` was updated and previously existing geomstats API kept).
Goal of this PR is to improve code readability. More to come on this.
=> Simplify ExpODESolver

geomstats/geometry/discrete_surfaces.py, tests/tests_geomstats/test_geometry/test_discrete_surfaces.py
This PR refactors `DiscreteSurfaces`, in particular the operations that are required to compute path energy (i.e. all the methods inner product calls).
Vectorization is fully fixed. Performance is hugely increased. Correctness of inner product computation was verified against original code (https://github.com//emmanuel-hartman/H2_SurfaceMatch). 
Next steps consist on improving exp and log solvers. #1957 already starts this (for the log). (NB: this PR does not address them at all, meaning they're still slow.)
=> Refactor DiscreteSurfaces (part 1)

geomstats/geometry/base.py, geomstats/geometry/symmetric_matrices.py, geomstats/test_cases/geometry/base.py, tests/tests_geomstats/test_geometry/data/symmetric_matrices.py, tests/tests_geomstats/test_geometry/test_symmetric_matrices.py
This PR builds on top of #1946 to add the matrix vector space `SymmetricHollowMatrices` and a permutation-invariant metric on it `HollowMatricesPermutationInvariantMetric`.
It also fixes small inheritance issues in `geometry.base`. In particular, deletes an abstract method which is also defined at manifold level in order to allow proper multiple inheritance from `LevelSet` and `MatrixVectorSpace`.
This is a first step to bring in pullback metrics on `Cor+` via the off-log diffeomorphism.
NB: merging this PR before #1946 also merges it.
=> Add SymmetricHollowMatrices and corresponding permutation-invariant metric

geomstats/geometry/full_rank_correlation_matrices.py, tests/tests_geomstats/test_geometry/data/full_rank_correlation_matrices.py, tests/tests_geomstats/test_geometry/test_full_rank_correlation_matrices.py
This PR builds on top of #1949 to add off-log metrics on full-rank correlation matrices `Cor+`. The diffeomorphism `OffLogDiffeo` is also added, since `OffLogMetric` is implemented as a `PullbackDiffeoMetric`.
NB: merging this PR also merges #1949.
=> Add off-log metrics on Cor+

geomstats/geometry/group_action.py, geomstats/test_cases/geometry/group_action.py, tests/tests_geomstats/test_geometry/data/group_action.py, tests/tests_geomstats/test_geometry/test_group_action.py
This PR adds the `GroupAction` abstraction. Design of the class follows similar ideas as `Diffeo` (e.g. group and space are not explicitly provided to the action, as the same implementation can be used for several groups acting on several manifolds).
Class has a main method (`__call__`) which implements the action of the group element on a point of a manifold.  An example of use:
```python
space = SPDMatrices(n=3, equip=False)
group = GeneralLinear(n=3, equip=False)
group_action = CongruenceAction()
point = space.random_point()
group_elem = space.random_point()
orbit_point = group_action(group_elem, point)  # NB: it looks like a function
```
I've also added the method `inverse_element`, which should retrieve the inverse element of the group wrt the group action. I've implemented it mostly …
=> Add GroupAction abstraction

geomstats/geometry/scalar_product_metric.py, geomstats/test_cases/geometry/scalar_product_metric.py
A new class method is added to `ScalarProductMetric` called `add_scaled_method` which allows the user to configure how a method from RiemannianMetric should be scaled.  The lists become class variables to allow them to be edited.
This fixes #1760.
###Tests
The added feature does not seem amenable to unit testing, but the following code does demonstrate that it works:
```
from geomstats import geomstats
from geomstats.geometry.scalar_product_metric import ScalarProductMetric
from geomstats.geometry.hypersphere import Hypersphere
sphere = Hypersphere(2)
point = sphere.random_point(1)
print(sphere.metric.injectivity_radius(point))
new_metric = 2.0 * sphere.metric
print(new_metric.injectivity_radius(point))
ScalarProductMetric.add_scaled_method('injectivity_radius', 'linear')
new_metric = 2.0 …
```
=> Add method to change the lists in `scalar_product_metric.py`

geomstats/geometry/discrete_surfaces.py, geomstats/geometry/pullback_metric.py, geomstats/numerics/geodesic.py, geomstats/numerics/interpolation.py, geomstats/numerics/optimizers.py, geomstats/numerics/path.py, geomstats/test/test_case.py, geomstats/test_cases/geometry/discrete_surfaces.py, geomstats/test_cases/numerics/geodesic.py, tests/tests_geomstats/test_geometry/data/discrete_surfaces.py, tests/tests_geomstats/test_geometry/test_discrete_surfaces.py, tests/tests_geomstats/test_numerics/data/geodesic.py, tests/tests_geomstats/test_numerics/data/interpolation.py, tests/tests_geomstats/test_numerics/data/log.py, tests/tests_geomstats/test_numerics/data/path.py, tests/tests_geomstats/test_numerics/test_exp.py, tests/tests_geomstats/test_numerics/test_interpolation.py, tests/tests_geomstats/test_numerics/test_log.py, tests/tests_geomstats/test_numerics/test_path.py
This PR generalizes implementation of  path-straightening algorithm already available on `discrete_surfaces`.
The algorithm minimizes the Riemannian geometry of a path.
Given the discretized nature of the path, I've created `numerics.path` with utils to compute the path energy of a uniformly-sampled path. Notice that there's a numerical analysis choice here: what finite-difference scheme to use? This implementation uses forward differences, but can easily be extended (not the same as @emmanuel-hartman original code).
Given the discretized nature of the output (the geodesic path is a collection of points), I've created `UniformlySampledPath` to interpolate between these points, such that `geodesic` is now a callable (and not an array). This relies on a 1d interpolator.
I've added a simple …
=> Add path-straightening algorithm

geomstats/geometry/connection.py, geomstats/geometry/discrete_surfaces.py, geomstats/geometry/invariant_metric.py, geomstats/geometry/pullback_metric.py, geomstats/geometry/stiefel.py, geomstats/information_geometry/dirichlet.py, geomstats/information_geometry/gamma.py, geomstats/numerics/geodesic.py, geomstats/numerics/path.py, geomstats/test_cases/numerics/geodesic.py, tests/tests_geomstats/test_geometry/data/discrete_curves.py, tests/tests_geomstats/test_geometry/data/positive_lower_triangular_matrices.py, tests/tests_geomstats/test_information_geometry/data/gamma.py, tests/tests_geomstats/test_learning/data/exponential_barycenter.py, tests/tests_geomstats/test_numerics/test_exp.py, tests/tests_geomstats/test_numerics/test_log.py, tests/tests_geomstats/test_numerics/test_path.py
This PR homogenizes signatures for solvers (and other objects) in numerics. In particular, space is removed from most signatures and passed at instantiation when required. This means methods defined in the solver that are common with methods from connection/metric have now exactly the same signature.
Additionally, some docstrings were improved (still need to improve more!).
In the initially design of solvers, space was passed in the methods instead of init to promote reusability of solvers in e.g. a script. Though this new design is stiffer wrt this use case, this is rarely required in our code (can't actually remember an example).
On the other hand, this new design allows validation at instantiation level  and/or the use of interfaces (as we do with learning methods). In fact, by …
=> Homogenize numerics signatures

geomstats/errors.py, geomstats/geometry/_my_manifold.py, geomstats/geometry/base.py, geomstats/geometry/complex_riemannian_metric.py, geomstats/geometry/connection.py, geomstats/geometry/euclidean.py, geomstats/geometry/grassmannian.py, geomstats/geometry/hermitian.py, geomstats/geometry/hpd_matrices.py, geomstats/geometry/hyperboloid.py, geomstats/geometry/hypersphere.py, geomstats/geometry/invariant_metric.py, geomstats/geometry/klein_bottle.py, geomstats/geometry/manifold.py, geomstats/geometry/poincare_ball.py, geomstats/geometry/poincare_half_space.py, geomstats/geometry/positive_lower_triangular_matrices.py, geomstats/geometry/pre_shape.py, geomstats/geometry/pullback_metric.py, geomstats/geometry/quotient_metric.py, geomstats/geometry/rank_k_psd_matrices.py, geomstats/geometry/riemannian_metric.py, geomstats/geometry/spd_matrices.py, geomstats/geometry/special_euclidean.py, geomstats/geometry/stiefel.py, geomstats/geometry/sub_riemannian_metric.py, geomstats/information_geometry/dirichlet.py, geomstats/information_geometry/exponential.py, geomstats/information_geometry/geometric.py, geomstats/information_geometry/normal.py
This PR removes uses of kwargs when unnecessary/misleading and makes use of `base_point=None` more consistent.
=> Clean signatures wrt kwargs and base_point=None

tests/tests_geomstats/test_visualization.py
Fix some tests due to pytest version update (use of `staticmethod` breaks them now).
=> Fix tests due pytest update

geomstats/geometry/discrete_surfaces.py, geomstats/numerics/geodesic.py, geomstats/numerics/interpolation.py, geomstats/test_cases/geometry/discrete_surfaces.py
This PR cleans the exponential solver in discrete surfaces by taking advantage of machinery introduced in #1957. It also fixes small bugs in path straightening and interpolation. Performance is expected to be the same (no relevant improvement done), except for geodesic coming from the use of a tangent vector and a base point (which now takes advantage of the `path` module). Discrete geodesic ivp is also made public (following path straightening).
=> Clean discrete surfaces exp solver

geomstats/geometry/complex_manifold.py, geomstats/geometry/manifold.py, geomstats/geometry/product_hpd_and_siegel_disks.py, geomstats/geometry/product_positive_reals_and_poincare_disks.py, geomstats/geometry/riemannian_metric.py, geomstats/geometry/scalar_product_metric.py, geomstats/information_geometry/normal.py, geomstats/test_cases/geometry/scalar_product_metric.py, tests/tests_geomstats/test_geometry/data/scalar_product_metric.py, tests/tests_geomstats/test_geometry/test_nfold_manifold.py, tests/tests_geomstats/test_geometry/test_scalar_product_metric.py, tests/tests_geomstats/test_geometry/test_spd_matrices.py
Changes the signature of `ScalarProductMetric` to take `space` instead of `metric` as suggested in #1968.
This means that `Manifold` and `ComplexManifold` needed changing: `equip_with_metric` must be able to take an instantiated metric, and not just a class. In particular, they can now be equipped with the specific `ScalarProductMetric`.
The `RiemannianMetric.__mul__` and `ScalarProductMetric.__mul__` methods can now only accept metrics that have been equipped by a particular space. I included a check here, as the user would probably expect `metric` to be scaled by this operation but it is `metric._space.metric` that is scaled. It could be quite confusing.
A number of other classes and tests use `ScalarProductMetric` and these have been refactored.
Closes #1968
One issue with putting this …
=> Scalar product metric API

geomstats/test/parametrizers.py, pyproject.toml
This PR updates strategy for running notebooks in tests to use `nbconvert` as a library instead of as a cli tool. It started as an attempt to solve  an error that started happening today in our CI (later discovered to be due to latest release of [ipython](https://github.com/ipython/ipython) ([8.23.0](https://pypi.org/project/ipython/8.23.0/))) .
=> Update notebook running on tests

geomstats/geometry/spd_matrices.py, tests/tests_geomstats/test_geometry/data/spd_matrices.py
This is a response to [Bug: Error due to complex number distance in Bures-Wasserstein metric, using pytorch backend #1882 ](https://github.com/geomstats/geomstats/issues/1882) (closes #1882)
I've been working with Bures-Wasserstein for spd matrices. The issue is the result of the sqrtm function being used. The solution I have found is to use the fact that spd matrices are orthogonally diagonalizble (due to being symmetric) and full rank (due to positive definite) to calculate square roots via diagonalization. This both fixes the issue of imaginary outputs (even for matrices with spd.belongs(sigma)==True -- see Bures_distance_check), and increases the speed. I also have a torch implementation that allows for batch computation on the gpu (of space.metric.dist_pairwise), which greatly speeds …
=> Update SPDBuresWassersteinMetric.squared_dist to fix numerical stability issues

geomstats/geometry/discrete_curves.py, geomstats/geometry/fiber_bundle.py, geomstats/geometry/full_rank_correlation_matrices.py, geomstats/geometry/group_action.py, geomstats/geometry/rank_k_psd_matrices.py, geomstats/geometry/stratified/graph_space.py, geomstats/geometry/stratified/quotient.py, geomstats/test_cases/geometry/fiber_bundle.py, tests/tests_geomstats/test_geometry/data/fiber_bundle.py, tests/tests_geomstats/test_geometry/test_discrete_curves.py, tests/tests_geomstats/test_geometry/test_fiber_bundle.py
This PR updates `FiberBundle` to:
1. use an `AlignerAlgorithm`: follows what was already being done in discrete curves and graph space (notice the abstraction was initially defined within the graph space context)
2. definitely moves `group_action` to the total space by removing it from fiber bundle
For 1., the main advantages are i) an easier control of the numerical parameters, ii) homogenization of the code among all the uses of quotient spaces (including graph space), iii) it becomes easier and more natural to plugin different aligner algorithms (this has already being taken advantage of within discrete curves).
For 2., we use `space.equip_with_group_action` method and make everything consistent, i.e. a group action endows the total space. Notice that a group action can simply be a …
=> Use aligner abstraction within fiber bundle and rely on group action on total space

geomstats/geometry/base.py, geomstats/geometry/complex_manifold.py, geomstats/geometry/full_rank_correlation_matrices.py, geomstats/geometry/manifold.py, geomstats/geometry/symmetric_matrices.py, tests/tests_geomstats/test_geometry/data/diffeo.py, tests/tests_geomstats/test_geometry/data/full_rank_correlation_matrices.py, tests/tests_geomstats/test_geometry/data/symmetric_matrices.py, tests/tests_geomstats/test_geometry/test_full_rank_correlation_matrices.py, tests/tests_geomstats/test_geometry/test_symmetric_matrices.py
This PR implements the log scaled metrics on full-rank correlation matrices (see "[Permutation-invariant log-Euclidean geometries on full-rank correlation matrices](https://hal.science/hal-03878729)").
To accomplish the goal, other spaces, metrics, and diffeos are created: 
* diffeos: `LogScalingDiffeo`, `ConstantValueRowSumDiffeo`
* spaces: `NullRowSumsSymmetricMatrices`
* abstract spaces: `DiffeomorphicVectorSpace`, `DiffeomorphicMatrixVectorSpace`
* metrics: `LogScaledMetric`, `NullRowSumsPermutationInvariantMetric`
`projection` is also moved to `Manifold` to avoid inheritance problems.
Done in collaboration with @olivierbisson.
=> Add LogScaled metrics on Cor+

geomstats/geometry/discrete_curves.py, tests/tests_geomstats/test_geometry/data/discrete_curves.py, tests/tests_geomstats/test_geometry/test_discrete_curves.py
This PR fixes the dynamic programming algorithm. In particular, we ensure the end point of the aligned curve corresponds to the end point of the curve. I'm afraid we are not there yet, but hopefully this is a first step towards correctness.
Moreover, I've tried to improve naming in order to make the code more readable, but I'm afraid it is still too hard to follow.
**Known issues** (also occur in previous implementation)
The dynamic programming outputs a squared dist. After alignment, we can also compute a distance using the total space metric (this is the distance quotient metric outputs).
For more complex cases (thinking about birds), I've realized these distances are similar, but slightly off. Moreover, when we swap `point` and `base_point`, the dynamic programming squared dist is the …
=> Fix dynamic programming algorithm

geomstats/geometry/discrete_curves.py, geomstats/geometry/fiber_bundle.py
This PR adds the possibility of obtaining the horizontal projection of a tangent vector from the alignment method.
Assuming `horizontal_projection` is not overriden, this method tries to obtain the horizontal projection from:
1) the vertical projection
2) the horizontal lift of the tangent submersion
3) (new) the alignment method
These different possibilities come from the fact that different methods are easier to define in certain bundles.
This is motivated by the `SRVRotationBundle`, where `align` is straighforward (and we didn't have an implementation for horizontal projection; now we use the generic one).
=> Add horizontal projection from alignment

geomstats/geometry/discrete_surfaces.py, geomstats/test_cases/geometry/discrete_surfaces.py
This PR cleans the discrete surfaces elastic metric:
* einsums are replaced by proper backend functions
* docstrings are fixed and simplified
* default solvers are only instantiated if an autodiff-based backend is used (this way we can compute inner products with numpy)
* a potential bug is solved in `_inner_prod_a2` (@emmanuel-hartman, could you please confirm we should multiply by vertex areas instead of divide? this comes from the original implementation)
=> Clean discrete surfaces elastic metric

geomstats/geometry/base.py, geomstats/geometry/manifold.py
When there are multiple basepoints, both implementations of `random_tangent_vec` (the implementations in `manifold.py` and `base.py`) should now check that `n_samples` matches the number of basepoints. If the values do not match, then in case `n_samples == 1` (default option), it resets it to be equal to the number of basepoints. Otherwise an error is raised.
Docstrings have been updated to clarify that the vectors generated have no statistical value.
Fixes #1989 insofar as the bug is no longer present. The reference to uniformity of direction understated the difficulty of that problem, so it should probably be ignored.
=> Correct number of samples for `VectorSpace.random_tangent_vec`

geomstats/_backend/pytorch/__init__.py
In the pytroch backend, the argument used for padding values was "constant_value". However, the naming in jax and numpy is constant_value**s**. See https://numpy.org/doc/stable/reference/generated/numpy.pad.html
and https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.pad.html. I also added passing on the "mode" argument, which is supported by pytorch.
This patch ensures that passing "constant_values" is compatible with all backends.
=> Fix + add argument to pad for pytorch backend

geomstats/geometry/discrete_curves.py, tests/tests_geomstats/test_geometry/data/discrete_curves.py, tests/tests_geomstats/test_geometry/test_discrete_curves.py
This PR replaces uses of "reparameterization" by "reparametrization". Though both are valid, the goal is to reduce confusion, as `space.equip_with_group_action("reparametrizations")` expects this exact spelling.
=> Homogenize use of reparametrization

geomstats/learning/_sklearn.py, geomstats/learning/aac.py, geomstats/learning/wrapped_gaussian_process.py, pyproject.toml
This PR is a quick fix for issues that appear with [sklearn 1.5.0. release](https://pypi.org/project/scikit-learn/1.5.0/) when  using `torch` as backend. `sklearn` now checks the device, in a way that invalidates passing `torch` tensors for some functions. 
For now, a quick and dirty wrapper does the job. We should think about a strategy for the long term though. I believe that changes in `sklearn` can actually benefit us in the long run, but we should confirm where they're aiming towards.
=> Fix issues with sklearn 1.5.0

geomstats/geometry/discrete_curves.py, geomstats/geometry/fiber_bundle.py, geomstats/test_cases/geometry/discrete_curves.py, tests/tests_geomstats/test_geometry/data/discrete_curves.py, tests/tests_geomstats/test_geometry/test_discrete_curves.py
This PR updates SRVReparametrizationBundle to handle any elastic parameter (the code was already prepared for that) and renames it `ReparametrizationBundle`.
@alebrigant, regarding `SRVRotationBundle`, the `SRV` stands for the SRV transformation or for the elastic parameters of  the total space? In other words, if I use different a, b, is the alignment wrt rotations still proper?
EDIT: `SRVRotationBundle` -> `RotationBundle`. It uses the diffeo available in the `PullbackDiffeoMetric` that endows the space.
=> Update curves bundles

geomstats/_backend/__init__.py
This PR fixes the backend import for Python 3.12 which is not working due to changes on how `sys.meta_path` works (see [docs](https://docs.python.org/3/library/sys.html#sys.meta_path)).
The fix is compatible with previous python versions.
Full tests on correctness of all the code for Python 3.12 haven't been carried out yet.
closes #1951
=> Fix backend import for py312

.github/workflows/test-python-backwards.yml
This PR adds a manually triggered workflow to test other supported python versions. It runs the same tests as usual testing workflow, but for other python versions.
I think it is enough to have it manually triggered instead of running every time to save compute.
=> Add manually triggered workflow to test other supported python versions

geomstats/geometry/discrete_curves.py
After this PR, to instantiate `Landmarks` with `L2CurvesMetric`:
```python
discrete_curves = DiscreteCurves(
k_sampling_points=200,
ambient_dim=2,
starting_at_origin=False)
```
and to instantiate `DiscreteCurvesStartingAtOrigin` with `ElasticMetric`/`SRVMetric`:
```python
discrete_curves = DiscreteCurves(
k_sampling_points=200,
ambient_dim=2,
starting_at_origin=True)
```
I think `starting_at_origin=True` by default is more natural, as this is the natural space to use for shape analysis. Thoughts?
=> Add syntax sugar to DiscreteCurves

.github/workflows/docs.yml, .github/workflows/lint.yml, .github/workflows/test-python-backwards.yml, .github/workflows/test.yml, docs/contributing/index.rst, pyproject.toml
Given the success with 3.12 tests (see [this](https://github.com/geomstats/geomstats/actions/runs/9499512495/)), I suggest to start testing the package with Python 3.12 (which has been released more than 6 months ago).
I've also dropped support to Python 3.8, as e.g. `numpy` asks for >=3.9.
=> Upgrade to python 3.12

geomstats/geometry/discrete_surfaces.py, geomstats/geometry/quotient_metric.py, tests/tests_geomstats/test_geometry/data/discrete_surfaces.py, tests/tests_geomstats/test_geometry/test_discrete_surfaces.py
This PR adds a very basic `L2SurfacesMetric` to put on `DiscreteSurfaces` that is basically a standard L2 metric on landmarks with inner products being weighted by number of vertices.
=> Add L2SurfacesMetric

geomstats/_backend/pytorch/_common.py, geomstats/geometry/full_rank_correlation_matrices.py, geomstats/numerics/optimizers.py, tests/tests_geomstats/test_geometry/data/full_rank_correlation_matrices.py, tests/tests_geomstats/test_geometry/test_full_rank_correlation_matrices.py
This PR improves on  #1980 to make more clear what is the problem being solved by `SPDScalingFinder` (previously `UniquePositiveDiagonalMatrixAlgorithm`).
This class finds the unique scaling of an SPD matrix, i.e. the matrix D such that `D A D e = e`, where `A` is an SPD matrix and `e` a vector of ones. Following [Thanwerdas, 2024](https://epubs.siam.org/doi/full/10.1137/22M1538144), this is accomplished by finding the roots of the gradient of a particular function.
Up until now, we were hardcoding a Newton method to solve this problem. This PR brings in `scipy.optimize.root` in a similar way as it has been done for `scipy.optimize.minimize` and implements the Newton method in a general way that is also compatible with `ScipyMinimize`. 
(It probably interests you @olivierbisson.)
=> Add root finders and improve SPDScalingFinder

geomstats/_backend/__init__.py, geomstats/_backend/autograd/__init__.py, geomstats/_backend/numpy/__init__.py, geomstats/_backend/pytorch/__init__.py, geomstats/geometry/discrete_surfaces.py, geomstats/geometry/fiber_bundle.py, geomstats/geometry/full_rank_correlation_matrices.py, geomstats/geometry/pullback_metric.py, geomstats/numerics/optimizers.py
In some parts of the code, we are verifying if the backend is not `numpy` in order to use autodiff capabilities. This PR adds `has_autodiff` to the backend in order to make this verification more robust. Then, we make use of the function when needed.
=> Add has_autodiff to backend

geomstats/_backend/__init__.py, geomstats/_backend/_shared_numpy/linalg.py, geomstats/_backend/autograd/linalg.py, geomstats/_backend/numpy/linalg.py, geomstats/_backend/pytorch/linalg.py
This PR adds [polar decomposition](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.polar.html) to the backend (`gs.linalg.polar`). It directly uses scipy function (also for pytorch). Adding this as I need it in for a different PR.
=> Add polar decomposition to backend

geomstats/geometry/discrete_surfaces.py, geomstats/numerics/geodesic.py, tests/tests_geomstats/test_numerics/test_log.py
This PR builds on top of #1957 to:
1. add a multiresolution path straightening method
2. add a symmetrized version of the already-existing `PathStraightening`
Multiresolution means a sequence of optimization problems is solved (instead of a unique optimization problem), where the solution for a resolution is used as initialization for the next.
Symmetrization means that instead of minimizing the energy of a path A-B, we minimize the mean energy of paths A-B and B-A, given we expect the geodesic to be "symmetric". Results seem to be more accurate with this flag.
Everything is fully tested against Poincaré ball closed-form solution.
=> Add multiresolution path straightening

geomstats/_backend/__init__.py, geomstats/_backend/autograd/linalg.py, geomstats/_backend/numpy/linalg.py, geomstats/_backend/pytorch/linalg.py, geomstats/algebra_utils.py, geomstats/geometry/diffeo.py, geomstats/geometry/full_rank_correlation_matrices.py, geomstats/geometry/lower_triangular_matrices.py, geomstats/geometry/matrices.py, geomstats/geometry/positive_lower_triangular_matrices.py, geomstats/test_cases/algebra_utils.py, geomstats/test_cases/geometry/positive_lower_triangular_matrices.py, tests/tests_geomstats/data/algebra_utils.py, tests/tests_geomstats/test_geometry/data/full_rank_correlation_matrices.py, tests/tests_geomstats/test_geometry/data/lower_triangular_matrices.py, tests/tests_geomstats/test_geometry/data/positive_lower_triangular_matrices.py, tests/tests_geomstats/test_geometry/test_full_rank_correlation_matrices.py, tests/tests_geomstats/test_geometry/test_lower_triangular_matrices.py, tests/tests_geomstats/test_geometry/test_positive_lower_triangular_matrices.py
This PR adds the metrics defined in sections 7.4.2 (`EuclideanCholeskyMetric`) and 7.4.3 (`LogEuclideanCholeskyMetric`) of [thanwerdas2022](https://hal.science/tel-03698752).
To accomplish this, we add the following spaces:
* `PLTUnitDiagMatrices`
* `StrictlyLowerTriangularMatrices`
And the following diffeos:
* `LowerMatrixLog`
* `EuclideanCholeskyDiffeo`
* `LogEuclideanCholeskyDiffeo`
For code readability, we also add a bunch of new functions: `columnwise_scaling`, `rowwise_scaling`, `matrix_matrix_transpose`, `tangent_matrix_matrix_transpose`.
Lastly, `matrix_power` is added to the backend.
Everything is fully tested.
(Done with @olivierbisson)
=> Add (log-)Euclidean-Cholesky diffeo and metrics on Cor+

.github/workflows/test-python-backwards.yml, .github/workflows/test.yml, geomstats/_backend/_shared_numpy/linalg.py, geomstats/_backend/autograd/linalg.py, geomstats/_backend/numpy/linalg.py, tests/tests_geomstats/test_geometry/data/product_hpd_and_siegel_disks.py
This PR fixes `numpy` backend to work with numpy `2.x.x`. `solve` signature has changed in `numpy` `2.x` for multi-batch. For now, `geomstats` signature is kept unchanged and the calling to `numpy` is manipulated.
NB: main tests run with `numpy 2.x`, while scripts run with `numpy 1.x` due to `tensorflow` dependency.
=> Fix numpy backend for 2.x

geomstats/geometry/full_rank_correlation_matrices.py, geomstats/numerics/optimization.py, tests/tests_geomstats/test_geometry/data/full_rank_correlation_matrices.py, tests/tests_geomstats/test_geometry/test_full_rank_correlation_matrices.py
This PR fixes the positiveness issue found by @olivierbisson for the `SPDScalingFinder` (optimization was returning negative elements, whereas they must be positive) (this follows from #2024).
The solution consists in using a damped Newton method (@olivierbisson can you suggest a reference for this?), as suggested by @olivierbisson.
Additional positiveness tests have been added and are now passing consistently.
=> Fix positiveness issue in spd scaling finder

geomstats/geometry/manifold.py, geomstats/geometry/spd_matrices.py, geomstats/test_cases/geometry/matrices.py
Added a check for `equip` argument type in the `Manifold` class. 
#2032 Without such check, if a metric class is passed as `equip`, which seems a reasonable mistake (that I was making), no error will be raised, and the manifold will be initialized with the default metric instead of the passed metric.
I also added the `equip` parameter to the SPDMatrices docstring. The `equip` parameter is missing from the doscrings of all other manifolds I checked, I don't know if there's a motivation for this. It could be desirable to add `equip` to the docstring of all specific manifold classes, and specify there what is the default metric for the manifold.
closes #2032
=> Check type of `equip` in Manifold __init__

.gitattributes
This PR ignores notebooks for languages percentage distribution, since this is a python package and notebooks are used only for documentation.
This is particular important when we search github for e.g. `"manifold statistics  language:Python"`: `geomstats` does not appear as currently its main language is not python.
=> Ignore notebooks as a language

geomstats/geometry/spd_matrices.py
I implemented a more efficient version of the Bures Wasserstein squared distance. The new method is 2 to 4 times faster than the original one.
The improved efficiency comes from the `cross_term`, which is the trace of matrix C, which is the square root of matrix C_sq = (A^{1/2} @ B @ A^{1/2}). Matrix C_sq is symmetric positive definite, so the eigenvalues of C are the square root of the eigenvalues of C_sq. Because tr(C) equals the sum of the eigenvalues of C, we compute tr(C) by:
- Computing eigenvalues of C2
- Taking their square root
- Adding the resulting eigenvalues
This procedure does not require actually computing C, but only the eigenvalues of C_sq.
The original method actually computed C, which requires computing both eigenvalues and eigenvectors of C_sq.
I also changed the …
=> More efficient Bures Wasserstein distance computation in SPD manifold

geomstats/geometry/fiber_bundle.py, geomstats/numerics/_common.py, geomstats/numerics/geodesic.py, geomstats/numerics/optimization/__init__.py, geomstats/numerics/optimization/_optimization.py, geomstats/numerics/optimization/_scipy.py, geomstats/numerics/optimization/_torch.py, geomstats/numerics/optimization/_torchmin.py, pyproject.toml, tests/tests_geomstats/test_numerics/test_optimization.py
This PR reorganizes `numerics.optimization` and adds `torch` minimizers.
In particular, it wraps [torch.optim.LBFGS](https://pytorch.org/docs/stable/generated/torch.optim.LBFGS.html#lbfgs) and [torchmin.minimize](https://pytorch-minimize.readthedocs.io/en/latest/api/index.html#functional-api).
=> Add torch optimizers

docs/conf.py
This PR adds the  [sphinx intersphinx](https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html) extension, which creates clickable hyperlinks between Python libraries when they are referenced in the documentation (for example like this page in the [MNE-Python](https://mne.tools/1.8/generated/mne.decoding.CSP.html#mne.decoding.CSP) documentation).
Using the TangentPCA module as an example, one can now click through to the Scikit-Learn page when it is referenced in the documentation:
| Branch | Rendered code |
|---------|---------|
| Main      |  <img width="600" alt="Screenshot 2025-02-07 at 7 15 26 PM" src="https://github.com/user-attachments/assets/a02abc7d-7dda-4e93-895f-09c23d77fdfa" />
| This PR |  <img width="600" alt="Screenshot 2025-02-07 at 7 14 48 PM" …
=> DOC: Use the intersphinx extension

geomstats/_backend/autograd/__init__.py, geomstats/_backend/numpy/__init__.py
- [ X] My pull request has a clear and explanatory title.
- [ X] If necessary, my code is [vectorized](https://www.geeksforgeeks.org/vectorization-in-python/).
- [ X] My PR follows [PEP8](https://peps.python.org/pep-0008/) guidelines. (refer to comment below)
- [ X] I linked to issues and PRs that are relevant to this PR.
In the `backend numpy/__init__.py` and `autograd/__init__.py` files, either `trapz` or `trapezoid` is imported, depending on the numpy version.
Solves https://github.com/geomstats/geomstats/issues/2048#issue-2866746478
=> Import trapz or trapezoid in mupy backend depending on numpy version

geomstats/geometry/discrete_surfaces.py
This PR fixes vertex area computation in discrete surfaces. Bug resulted from a confusion between tile and repeat while reshaping. (It is small, but important.)
=> Fix vertex areas in discrete surfaces

geomstats/geometry/product_manifold.py
This PR fixes an issue with the computation of the indices for the product manifold projection. Instead of using the factor dimension, it uses the product of the factor shape.
=> Fix ProductManifold projection
